<option value="">--</option>
<option value="alimentation">Alimentation</option>
<option value="couverture">Couvertures</option>
<option value="douche">Douche</option>
<option value="matelas">Matelas</option>
<option value="vetements">Vêtements</option>
<option value="loyer">Loyer</option>
<option value="transport">Frais de transport</option>
<option value="retour">Aide au retour</option>
<option value="couches">Couches</option>
<option value="creche">Crèche</option>
<option value="naissance">Kit naissance</option>
<option value="lait">Lait infantile</option>
<option value="autre">Autres</option>
