<option value="">--</option>
<option value="agriculture_agroalimentaire">Agriculture, agroalimentaire</option>
<option value="animation_sport">Animation, sport</option>
<option value="arts_culture">Arts, culture</option>
<option value="art_traditionnel">Art traditionnel</option>
<option value="batiment_travaux publics">Bâtiment, travaux publics</option>
<option value="commerce_tourisme_hotellerie">Commerce, tourisme, hôtellerie</option>
<option value="droit_economie_gestion_comptabilite">Droit, économie, gestion, comptabilité</option>
<option value="gestion de production_qualite">Gestion de production, qualité</option>
<option value="informatique_electronique_electricite_energetique">Informatique, électronique, électricité, énergétique</option>
<option value="information_communication">Information, communication</option>
<option value="lettres_langues vivantes_sciences humaines">Lettres, langues vivantes, sciences humaines</option>
<option value="mecanique_microtechnique">Mécanique, microtechnique</option>
<option value="maintenance_materiaux">Maintenance, matériaux</option>
<option value="offshoring">Offshoring</option>
<option value="sante_social">Santé, social</option>
<option value="physique_chimie_biologie">Physique, chimie, biologie</option>
<option value="securite_environnement">Sécurité, environnement</option>
<option value="sciences_technologies">Sciences, technologies</option>
<option value="textile_habillement">Textile et Habillement</option>
<option value="transport_logistique">Transport, logistique</option>
