<option value="">--</option>
<option value="deplacement">Déplacements</option>
<option value="nationalieminoritaire">Nationalité minoritaire</option>
<option value="sante">Etat de santé</option>
<option value="lgbti">LGBTI</option>
<option value="traitehumanie">Traite humaine</option>
<option value="religion">Discrimination religieuse</option>
<option value="couleurpeau">Couleur de peau</option>
<option value="persecution">Personnes persecutées sur place</option>
<option value="grossesse">Grossesse</option>
<option value="enfant">Enfant en bas-âge</option>
