<option value="">--</option>
<option value="1">Amis - Famille</option>
<option value="2">Communauté</option>
<option value="3">Associations</option>
<option value="5">Autre service Caritas</option>
<option value="6">Agence ONU</option>
<option value="7">Église</option>
<option value="8">Structures publiques</option>
<option value="9">Autre centre de Caritas</option>
<option value="10">Autre</option>
