<option value="aghzdiss">Aghzdiss</option>
<option value="ait_el_mouden+ait_taoukte">Ait El Mouden+Ait Taoukte</option>
<option value="al_machroua_al_ijtimaai">Al Machroua Al Ijtimaai</option>
<option value="al_wahda">Al Wahda</option>
<option value="amicales_des_fonctionnaires">Amicales Des Fonctionnaires</option>
<option value="amsernate">Amsernate</option>
<option value="anahda">Anahda</option>
<option value="annexe_faculte_ibn_zohr">Annexe Faculte Ibn Zohr</option>
<option value="hay_najah">Hay Najah</option>
<option value="ancien_port">Ancien Port</option>
<option value="anwar_souss">Anwar Souss</option>
<option value="anza_centre">Anza Centre</option>
<option value="aswak_assalam">Aswak Assalam</option>
<option value="av_hassan_ii">Av Hassan II</option>
<option value="camping_international">Camping International</option>
<option value="cap_ghir">Cap Ghir</option>
<option value="carriere_al_guinig">Carriere Al Guinig</option>
<option value="charaf">Charaf</option>
<option value="corniche_tawada">Corniche -Tawada</option>
<option value="château_d_eau">Château D'eau</option>
<option value="cite_balneaire">Cite Balneaire</option>
<option value="cite_municipale">Cite Municipale</option>
<option value="cite_suisse">Cite Suisse</option>
<option value="cite_universitaire">Cite Universitaire</option>
<option value="complexe_ait_souss">Complexe Ait Souss</option>
<option value="cooperative_artisanale">Cooperative Artisanale</option>
<option value="cos_one">Cos -One</option>
<option value="hay_dakhla_bloc_c">Hay Dakhla Bloc C</option>
<option value="hay_dakhla_bloc_d">Hay Dakhla Bloc D</option>
<option value="hay_dakhla_bloc_e">Hay Dakhla Bloc E</option>
<option value="hay_dakhla_bloc_f">Hay Dakhla Bloc F</option>
<option value="hay_dakhla_bloc_g">Hay Dakhla Bloc G</option>
<option value="hay_dakhla_bloc_h">Hay Dakhla Bloc H</option>
<option value="derb_ait_el_arbi">Derb Ait El Arbi</option>
<option value="derb_ali_ben_el_qaid">Derb Ali Ben El Qaid</option>
<option value="derb_aouk">Derb Aouk</option>
<option value="derb_baadi">Derb Baadi</option>
<option value="derb_el_hemmam">Derb El Hemmam</option>
<option value="derb_el_issaoui">Derb El Issaoui</option>
<option value="derb_m_barek">Derb M'barek</option>
<option value="derb_taaissate">Derb Taaissate</option>
<option value="diour_jdad">Diour Jdad</option>
<option value="douarahlaka">DouarAhlaka</option>
<option value="douar_rjafllah">Douar Rjafllah</option>
<option value="el_kasbah">El Kasbah</option>
<option value="el_khiyam_i">El Khiyam I</option>
<option value="el_khiyam_ii">El Khiyam II</option>
<option value="ensemble_immeubles_el_menzeh_/_cgi">Ensemble Immeubles El Menzeh / Cgi</option>
<option value="extension_massira">Extension Massira</option>
<option value="erac_bouargane">Erac Bouargane</option>
<option value="erac_ihchach">Erac Ihchach</option>
<option value="extensionx">ExtensionX</option>
<option value="extension_dakhla">Extension Dakhla</option>
<option value="gare_routiere">Gare Routiere</option>
<option value="habitat_ameliore">Habitat Ameliore</option>
<option value="haut_founty">Haut Founty</option>
<option value="hay_al_amal">Hay Al Amal</option>
<option value="hay_al_houda">Hay Al Houda</option>
<option value="hay_al_ismante">Hay Al Ismante</option>
<option value="hay_al_massira">Hay Al Massira</option>
<option value="hay_al_qods">Hay Al Qods</option>
<option value="hay_al_wafa">Hay Al Wafa</option>
<option value="hay_dakhla">Hay Dakhla</option>
<option value="hay_el_farha">Hay El Farha</option>
<option value="hay_el_fidiya">Hay El Fidiya</option>
<option value="hay_essalam">Hay Essalam</option>
<option value="hay_founty">Hay Founty</option>
<option value="hay_hassani">Hay Hassani</option>
<option value="hay_mohammadi">Hay Mohammadi</option>
<option value="hay_sidi_med">Hay Sidi Med</option>
<option value="hay_sidi_youssef">Hay Sidi Youssef</option>
<option value="hopital_hassan_ii">Hopital Hassan II</option>
<option value="ighil_ou_dardour">Ighil Ou Dardour</option>
<option value="imounssisse">Imounssisse</option>
<option value="institut_al_qalam">Institut Al Qalam</option>
<option value="jiouar_al_kahrabaa">Jiouar Al Kahrabaa</option>
<option value="jiouar_al_malaab">Jiouar Al Malaab</option>
<option value="jiouar_krara">Jiouar Krara</option>
<option value="jiouar_proj_et_social">Jiouar Proj et Social</option>
<option value="jiouar_rigada">Jiouar Rigada</option>
<option value="jiouar_souk">Jiouar Souk</option>
<option value="jiouar_unimer_et_amer">Jiouar Unimer et amer</option>
<option value="laazib_tahtani">Laazib Tahtani</option>
<option value="lakhyam_al_jadid">Lakhyam Al Jadid</option>
<option value="lazar">Lazar</option>
<option value="les_facultes_universite_ibn_zohr">Les Facultes Universite Ibn Zohr</option>
<option value="logement_social_el_khiam">Logement Social El Khiam</option>
<option value="lotissement_afoulki">Lotissement Afoulki</option>
<option value="lotissement_agharass">Lotissement Agharass</option>
<option value="lotissement_hassania">Lotissement Hassania</option>
<option value="lotissement_faiz">Lotissement Faiz</option>
<option value="lotissement_lagouira">Lotissement Lagouira</option>
<option value="marche_massira">Marche Massira</option>
<option value="marina">Marina</option>
<option value="hay_moulay_rachid">Hay Moulay Rachid</option>
<option value="nouveau_port">Nouveau Port</option>
<option value="nouveau_quartier_desadministrations_publiques">Nouveau Quartier DesAdministrations Publiques</option>
<option value="nouveau_talborjt">Nouveau Talborjt</option>
<option value="programme_ifrane_2">Programme Ifrane 2</option>
<option value="programmes_mabrouka_+_al_wid">Programmes : Mabrouka + Al Wid</option>
<option value="programmes_riad_ahl_souss_+_al_boustane">Programmes : Riad Ahl Souss + Al Boustane</option>
<option value="place_des_taxis">Place Des Taxis</option>
<option value="programme_al_mokhtar_assoussi">Programme Al Mokhtar Assoussi</option>
<option value="programme_zerktouni_i">Programme Zerktouni I</option>
<option value="quartier_administratif">Quartier Administratif</option>
<option value="quartier_iligh">Quartier Iligh</option>
<option value="quartier_industriel_boutchakat">Quartier Industriel Boutchakat</option>
<option value="quartier_indutriel_anza">Quartier Indutriel Anza</option>
<option value="quartier_marins_pecheurs">Quartier Marins Pecheurs</option>
<option value="quartier_usines">Quartier Usines</option>
<option value="riad_assalam">Riad Assalam</option>
<option value="secteur_balneaire">Secteur Balneaire</option>
<option value="secteur_mixte">Secteur Mixte</option>
<option value="secteur_residentiel">Secteur Residentiel</option>
<option value="souk_al_massira_namoudaji">Souk Al Massira Namoudaji</option>
<option value="souk_el_had">Souk El Had</option>
<option value="tadart_ii">Tadart II</option>
<option value="tadarte_anza">Tadarte Anza</option>
<option value="taddarte_1">Taddarte 1</option>
<option value="talborjt">Talborjt</option>
<option value="tildi">Tildi</option>
<option value="ville_nouvelle">Ville Nouvelle</option>
<option value="zone_touristique">Zone Touristique</option>
<option value="zraibe_anza">Zraibe Anza</option>