<option value="ain_asserdoune">Ain Asserdoune</option>
<option value="ancienne_medina">Ancienne Medina</option>
<option value="atlas">Atlas</option>
<option value="cite_bellvue">Cite Bellvue</option>
<option value="couperative_elf_et_h">Couperative Elf et h</option>
<option value="douar_ait_eddaw">Douar Ait Eddaw</option>
<option value="douar_ait_felha_ex_douar_belkaid">Douar Ait Felha Ex Douar Belkaid</option>
<option value="douar_ben_chouia">Douar Ben Chouia</option>
<option value="douar_cyclice">Douar Cyclice</option>
<option value="douar_jghou">Douar Jghou</option>
<option value="douar_outata">Douar Outata</option>
<option value="douar_zaarati">Douar Zaarati</option>
<option value="dour_elhadj_mbarek">Dour Elhadj Mbarek</option>
<option value="el_houda">El Houda</option>
<option value="essafa">Essafa</option>
<option value="hay_almaghrib_alarabi">Hay Almaghrib Alarabi</option>
<option value="hay_atlas">Hay Atlas</option>
<option value="hay_atlas_zone_villa">Hay Atlas Zone Villa</option>
<option value="hay_charaf">Hay Charaf</option>
<option value="hay_eladdarissa">Hay Eladdarissa</option>
<option value="hay_elamal">Hay Elamal</option>
<option value="hay_elamal_6">Hay Elamal 6</option>
<option value="hay_elf_et_th_ex_dourlarbi_laajej">Hay Elf et th Ex DourLarbi Laajej</option>
<option value="hay_elhanaa">Hay Elhanaa</option>
<option value="hay_eljahad">Hay Eljahad</option>
<option value="hay_elmorabitine">Hay Elmorabitine</option>
<option value="hay_elwafa">Hay Elwafa</option>
<option value="hay_errachad">Hay Errachad</option>
<option value="hay_essalem_ex_boulegroune">Hay Essalem Ex Boulegroune</option>
<option value="hay_houda_16_groupes">Hay Houda 16 Groupes</option>
<option value="hay_kastor">Hay Kastor</option>
<option value="hay_ksar_eghzefat">Hay Ksar Eghzefat</option>
<option value="hay_ksar_ghzefate">Hay Ksar Ghzefate</option>
<option value="hay_lalla_aicha_ex_elinache_elwatani">Hay Lalla Aicha Ex Elinache Elwatani</option>
<option value="hay_mohammadi_n_2">Hay Mohammadi N°2</option>
<option value="hay_nouail_elmekhzene16_groupes">Hay Nouail Elmekhzene16 Groupes</option>
<option value="hay_ourbia">Hay Ourbia</option>
<option value="hay_riad_elatlas">Hay Riad Elatlas</option>
<option value="hay_riad_esselam">Hay Riad Esselam</option>
<option value="hay_si_salem_26_bloc">Hay Si Salem 26 Bloc</option>
<option value="hay_soumia">Hay Soumia</option>
<option value="hay_zitoune">Hay Zitoune</option>
<option value="houda_zone_villa">Houda Zone Villa</option>
<option value="kissariat_baarib">Kissariat Baarib</option>
<option value="ksar_2_bibane">Ksar 2 Bibane</option>
<option value="ksar_belkheir">Ksar Belkheir</option>
<option value="ksar_ben_hammou">Ksar Ben Hammou</option>
<option value="lot_18_novembre">Lot 18 Novembre</option>
<option value="lot_3_mars">Lot 3 Mars</option>
<option value="lot_abourraja">Lot Abourraja</option>
<option value="lot_ain_asserdoune">Lot Ain Asserdoune</option>
<option value="lot_ain_asserdoune_ben_kirane">Lot Ain Asserdoune Ben Kirane</option>
<option value="lot_ait_elkorchi">Lot Ait Elkorchi</option>
<option value="lot_allal_ben_nacer">Lot Allal Ben Nacer</option>
<option value="lot_ammaria">Lot Ammaria</option>
<option value="lot_anwal">Lot Anwal</option>
<option value="lot_asmaa">Lot Asmaa</option>
<option value="lot_baarib">Lot Baarib</option>
<option value="lot_bab_aikheir">Lot Bab Aikheir</option>
<option value="lot_babay">Lot Babay</option>
<option value="lot_bader">Lot Bader</option>
<option value="lot_bahija">Lot Bahija</option>
<option value="lot_ben_alla">Lot Ben Alla</option>
<option value="lot_ben_zeroual">Lot Ben Zeroual</option>
<option value="lot_benchakroune_ben_kirane">Lot Benchakroune Ben Kirane</option>
<option value="lot_chaabi">Lot Chaabi</option>
<option value="lot_chawki">Lot Chawki</option>
<option value="lot_chemes_1_et_2">Lot Chemes_1 et 2</option>
<option value="lot_dar_jdida">Lot Dar Jdida</option>
<option value="lot_darkoum">Lot Darkoum</option>
<option value="lot_echoker">Lot Echoker</option>
<option value="lot_elamal_7">Lot Elamal 7</option>
<option value="lot_elarsa">Lot Elarsa</option>
<option value="lot_elbaraka">Lot Elbaraka</option>
<option value="lot_elfadele">Lot Elfadele</option>
<option value="lot_elhassani">Lot Elhassani</option>
<option value="lot_elhassania_ex_oukacha">Lot Elhassania Ex Oukacha</option>
<option value="lot_elhawat">Lot Elhawat</option>
<option value="lot_elhissen">Lot Elhissen</option>
<option value="lot_eljoud">Lot Eljoud</option>
<option value="lot_elkheir">Lot Elkheir</option>
<option value="lot_elmahrek">Lot Elmahrek</option>
<option value="lot_elmehdi">Lot Elmehdi</option>
<option value="lot_elquods">Lot Elquods</option>
<option value="lot_elwarda">Lot Elwarda</option>
<option value="lot_ennajat">Lot Ennajat</option>
<option value="lot_ennakhil">Lot Ennakhil</option>
<option value="lot_ennour">Lot Ennour</option>
<option value="lot_errachidia">Lot Errachidia</option>
<option value="lot_erraja">Lot Erraja</option>
<option value="lot_et_tissir">Lot et tissir</option>
<option value="lot_ezzaitoune_benkirane”">Lot Ezzaitoune Benkirane”</option>
<option value="lot_f_1">Lot F 1</option>
<option value="lot_f_2_et_3">Lot F 2 et 3</option>
<option value="lot_fares">Lot Fares</option>
<option value="lot_fedan_nouail">Lot Fedan Nouail</option>
<option value="lot_ferdaous">Lot Ferdaous</option>
<option value="lot_ghita">Lot Ghita</option>
<option value="lot_ghita_ben_kirane">Lot Ghita Ben Kirane</option>
<option value="lot_ghizlane">Lot Ghizlane</option>
<option value="lot_hadria">Lot Hadria</option>
<option value="lot_hamdania_2">Lot Hamdania 2</option>
<option value="lot_hamdania_1">Lot Hamdania 1</option>
<option value="lot_hasna">Lot Hasna</option>
<option value="lot_hay_elymoune">Lot Hay Elymoune</option>
<option value="lot_innas">Lot Innas</option>
<option value="lot_jamal">Lot Jamal</option>
<option value="lot_jamila">Lot Jamila</option>
<option value="lot_jil_elmoustakbel">Lot Jil Elmoustakbel</option>
<option value="lot_jnan_tahar">Lot Jnan Tahar</option>
<option value="lot_joulali">Lot Joulali</option>
<option value="lot_kadi_ayad">Lot Kadi Ayad</option>
<option value="lot_kamal_ou_elyasmina 3">Lot Kamal Ou Elyasmina 3</option>
<option value="lot_karima">Lot Karima</option>
<option value="lot_khalifa">Lot Khalifa</option>
<option value="lot_lalla_hasna">Lot Lalla Hasna</option>
<option value="lot_latifa">Lot Latifa</option>
<option value="lot_laymoune_benkirane">Lot Laymoune Benkirane</option>
<option value="lot_lebdegue">Lot Lebdegue</option>
<option value="lot_leghzafia">Lot Leghzafia</option>
<option value="lot_lmssalah">Lot Lmssalah</option>
<option value="lot_loukilia">Lot Loukilia</option>
<option value="lot_maakil">Lot Maakil</option>
<option value="lot_maataoui">Lot Maataoui</option>
<option value="lot_mabrouka">Lot Mabrouka</option>
<option value="lot_maktoub">Lot Maktoub</option>
<option value="lot_mehdia">Lot Mehdia</option>
<option value="lot_mobarek_dris">Lot Mobarek Dris</option>
<option value="lot_mostakbel_2">Lot Mostakbel 2</option>
<option value="lot_mouhssine">Lot Mouhssine</option>
<option value="lot_mounjid">Lot Mounjid</option>
<option value="lot_mourabit">Lot Mourabit</option>
<option value="lot_mourabit_benkirane">Lot Mourabit Benkirane</option>
<option value="lot_naima">Lot Naima</option>
<option value="lot_nakhla_ex_elamal">Lot Nakhla Ex Elamal</option>
<option value="lot_nawal">Lot Nawal</option>
<option value="lot_niama">Lot Niama</option>
<option value="lot_nisrine">Lot Nisrine</option>
<option value="lot_nizar">Lot Nizar</option>
<option value="lot_nour">Lot Nour</option>
<option value="lot_nourane">Lot Nourane</option>
<option value="lot_oumerrabia">Lot Oumerrabia</option>
<option value="lot_oumnia">Lot Oumnia</option>
<option value="lot_ouzoud">Lot Ouzoud</option>
<option value="lot_rabia">Lot Rabia</option>
<option value="lot_raha">Lot Raha</option>
<option value="lot_rahmoune">Lot Rahmoune</option>
<option value="lot_raja">Lot Raja</option>
<option value="lot_raja_et_fouzia">Lot Raja et Fouzia</option>
<option value="lot_ramz">Lot Ramz</option>
<option value="lot_riad_assa">Lot Riad Assa</option>
<option value="lot_riad1">Lot Riad1</option>
<option value="lot_rihl_et_enneser">Lot Rihl et Enneser</option>
<option value="lot_souad">Lot Souad</option>
<option value="lot_soumia">Lot Soumia</option>
<option value="lot_tasemm_et_benkirane">Lot Tasemm et benkirane</option>
<option value="lot_tawfik">Lot Tawfik</option>
<option value="lot_touta">Lot Touta</option>
<option value="lot_villa_zoize_ex_elymoune">Lot Villa Zoize Ex Elymoune</option>
<option value="lot_wacil">Lot Wacil</option>
<option value="lot_walfa">Lot Walfa</option>
<option value="lot_yasmina">Lot Yasmina</option>
<option value="lot_yasmine_ben_kirane">Lot Yasmine Ben Kirane</option>
<option value="lot_youssef">Lot Youssef</option>
<option value="lot_zehouani">Lot Zehouani</option>
<option value="lotcharaf">Lotcharaf</option>
<option value="mghilahay_erroumen">MghilaHay Erroumen</option>
<option value="mghila_hay_ezaitoune">Mghila Hay Ezaitoune</option>
<option value="oulad_hamdan">Oulad Hamdan</option>
<option value="place_bir_anzarane">Place Bir Anzarane</option>
<option value="place_elmassira">Place Elmassira</option>
<option value="place_kaid_elasri">Place Kaid Elasri</option>
<option value="place_liberte">Place Liberté</option>
<option value="quartier_abourraja">Quartier Abourraja</option>
<option value="quartier_administratif">Quartier Administratif</option>
<option value="quartier_ait_soltana">Quartier Ait Soltana</option>
<option value="quartier_ait_thaich">Quartier Ait Thaich</option>
<option value="quartier_asef_et_serhani">Quartier Asef et Serhani</option>
<option value="quartier_ayat">Quartier Ayat</option>
<option value="quartier_bab_ftouh">Quartier Bab Ftouh</option>
<option value="quartier_benaddi_n_1">Quartier Benaddi N°1</option>
<option value="quartier_benaddi_n_2">Quartier Benaddi N°2</option>
<option value="quartier_biad">Quartier Biad</option>
<option value="quartier_blad_baarib">Quartier Blad Baarib</option>
<option value="quartier_bled_ahmed_ben_salem">Quartier Bled Ahmed Ben Salem</option>
<option value="quartier_bled_sassaoui">Quartier Bled Sassaoui</option>
<option value="quartier_dakhlaayat">Quartier Dakhlaayat</option>
<option value="quartier_dar_dbagh">Quartier Dar Dbagh</option>
<option value="quartier_dchira">Quartier Dchira</option>
<option value="quartier_elamria_1">Quartier Elamria 1</option>
<option value="quartier_elamria_2">Quartier Elamria 2</option>
<option value="quartier_elbouharraoui">Quartier Elbouharraoui</option>
<option value="quartier_elgouaichia">Quartier Elgouaichia</option>
<option value="quartier_elhassaniaex_quartier_industriel">Quartier Elhassaniaex Quartier Industriel</option>
<option value="quartier_elinbiaate">Quartier Elinbiaate</option>
<option value="quartier_eljabalia_4_bloc">Quartier Eljabalia 4 Bloc</option>
<option value="quartier_elkassimi_ex_sommaa">Quartier Elkassimi Ex Sommaa</option>
<option value="quartier_elkheir">Quartier Elkheir</option>
<option value="quartier_elmassira">Quartier Elmassira</option>
<option value="quartier_elmassira_n_1">Quartier Elmassira N°1</option>
<option value="quartier_elmourabitine">Quartier Elmourabitine</option>
<option value="quartier_ennacer">Quartier Ennacer</option>
<option value="quartier_ennaser_ex_bouachouch">Quartier Ennaser Ex Bouachouch</option>
<option value="quartier_essafa_4_bloc">Quartier Essafa 4 Bloc</option>
<option value="quartier_foughal">Quartier Foughal</option>
<option value="quartier_hay_mohammadi_ex_bouchrait">Quartier Hay Mohammadi Ex Bouchrait</option>
<option value="quartier_iben_sina">Quartier Iben Sina</option>
<option value="quartier_kharrouba">Quartier Kharrouba</option>
<option value="quartier_massira_n_2">Quartier Massira N°2</option>
<option value="quartier_mdioula">Quartier Mdioula</option>
<option value="quartier_miftah">Quartier Miftah</option>
<option value="quartier_mimouna_4_bloc">Quartier Mimouna 4 Bloc</option>
<option value="quartier_moderne">Quartier Moderne</option>
<option value="quartier_nkhila_n_1_et_2">Quartier Nkhila N°1 et 2</option>
<option value="quartier_oulad_ayad_lagrabzia">Quartier Oulad Ayad Lagrabzia</option>
<option value="quartier_oulad_ayad_oulad_slimene">Quartier Oulad Ayad Oulad Slimene</option>
<option value="quartier_oulad_hamdane_nezzala">Quartier Oulad Hamdane Nezzala</option>
<option value="quartier_oulad_hamdane_sekkakine">Quartier Oulad Hamdane Sekkakine</option>
<option value="quartier_oulad_zehra">Quartier Oulad Zehra</option>
<option value="quartier_oumdhar">Quartier Oumdhar</option>
<option value="quartier_rmila">Quartier Rmila</option>
<option value="quartier_rmila_somaa">Quartier Rmila Somaa</option>
<option value="quartier_saada">Quartier Saada</option>
<option value="quartier_takadoum_30_bloc">Quartier Takadoum 30 Bloc</option>
<option value="quartier_takadoum_n_2">Quartier Takadoum N°2</option>
<option value="quartier_tamegnount">Quartier Tamegnount</option>
<option value="quartier_yacoub_elmansour">Quartier Yacoub Elmansour</option>
<option value="quartier_zitoune_elmhale">Quartier Zitoune Elmhale</option>
<option value="residance_donia">Résidance Donia</option>
<option value="residance_houria">Résidance Houria</option>
<option value="residance_kenza">Résidance Kenza</option>
<option value="residance_lmsallah">Résidance Lmsallah</option>
<option value="residance_raja">Résidance Raja</option>
<option value="residancemerwane">Résidancemerwane</option>
<option value="riad_salam">Riad Salam</option>
<option value="yay_rannia_1_et_2">Yay Rannia 1 et 2</option>
<option value="zone_industrielle">Zone Industrielle</option>