<option value="addamane">Addamane</option>
<option value="quartier_administratif">Quartier Administratif</option>
<option value="agence_urbaine">Agence Urbaine</option>
<option value="ahl_loghlam">Ahl Loghlam</option>
<option value="ain_borja">Ain Borja</option>
<option value="ain_chifa_ii_et_iii">Ain Chifa II et III</option>
<option value="ain_chok">Ain Chok</option>
<option value="ain_diab">Ain Diab</option>
<option value="ain_sebaa">Ain Sebaa</option>
<option value="al_amal">Al Amal</option>
<option value="al_azhar">Al Azhar</option>
<option value="al_baida">Al Baida</option>
<option value="al_fadl">Al Fadl</option>
<option value="al_firdous">Al Firdous</option>
<option value="al_fouarate">Al Fouarate</option>
<option value="al_idaa">Al Idaa</option>
<option value="al_kaoutar">Al Kaoutar</option>
<option value="al_kodia">Al Kodia</option>
<option value="al_masira">Al Masira</option>
<option value="al_mawlid">Al Mawlid</option>
<option value="al_moustakbal">Al Moustakbal</option>
<option value="al_mouwahddine">Al Mouwahddine</option>
<option value="al_osre">Al Osre</option>
<option value="al_qods">Al Qods</option>
<option value="al_ward">Al Ward</option>
<option value="aladarissa">Aladarissa</option>
<option value="alhnaa">Alhnaa</option>
<option value="alothmania">Alothmania</option>
<option value="amal">Amal</option>
<option value="amine">Amine</option>
<option value="anassi">Anassi</option>
<option value="ancienne_medina">Ancienne Medina</option>
<option value="andalouss_i">Andalouss I</option>
<option value="andalouss_ii">Andalouss II</option>
<option value="andaloussia">Andaloussia</option>
<option value="anfa_ii">Anfa II</option>
<option value="anfa_superieur">Anfa Supérieur</option>
<option value="annakhil_diar_al_hana">Annakhil Diar Al Hana</option>
<option value="artizana_c_djemaa_bloc_1_a16">Artizana C Djemaa Bloc 1 à16</option>
<option value="assafa">Assafa</option>
<option value="attacharouks1">AttacharoukS1</option>
<option value="attacharouk_s2">Attacharouk S2</option>
<option value="attadamoune">Attadamoune</option>
<option value="attaoun">Attaoun</option>
<option value="attayssir">Attayssir</option>
<option value="azhari">Azhari</option>
<option value="bachkou">Bachkou</option>
<option value="baladia">Baladia</option>
<option value="baraka">Baraka</option>
<option value="baraka_2">Baraka 2</option>
<option value="beau_lieu">Beau Lieu</option>
<option value="beaucite">Beaucite</option>
<option value="beaucite_halima">Beaucite Halima</option>
<option value="beausejour">Beausejour</option>
<option value="ben_jdia_liberte">Ben Jdia, Liberté</option>
<option value="ben_slimane">Ben Slimane</option>
<option value="berger">Berger</option>
<option value="bernoussi_2">Bernoussi 2</option>
<option value="biada">Biada</option>
<option value="bine_lamdoune">Bine Lamdoune</option>
<option value="bir_anzarane">Bir Anzarane</option>
<option value="bloc_hofra_bloc_khlifa_cd">Bloc Hofra Bloc Khlifa Cd</option>
<option value="blocs_far">Blocs Far</option>
<option value="bouchra">Bouchra</option>
<option value="boujdour">Boujdour</option>
<option value="bourgogne">Bourgogne</option>
<option value="california">California</option>
<option value="carrier_ghlia">Carrier Ghlia</option>
<option value="carrier_rhamner">Carrier Rhamner</option>
<option value="carrier_sokouila">Carrier Sokouila</option>
<option value="carrier_zaraba">Carrier Zaraba</option>
<option value="carriere_thomas">Carriere Thomas</option>
<option value="casa_plaisance">Casa Plaisance</option>
<option value="castor">Castor</option>
<option value="chahdia">Chahdia</option>
<option value="chantimar">Chantimar</option>
<option value="charaf">Charaf</option>
<option value="chdia">Chdia</option>
<option value="chikass">Chikass</option>
<option value="chnider">Chnider</option>
<option value="chrifa">Chrifa</option>
<option value="ciel">Ciel</option>
<option value="cite_courtin">Cité Courtin</option>
<option value="cite_de_l_air">Cité De L'air</option>
<option value="cite_dejmaa_bloc_20_a_23">Cite Dejmaa Bloc 20 à 23</option>
<option value="cite_dejmaa_bloc_30_a_36">Cite Dejmaa Bloc 30 à 36</option>
<option value="cite_dejmaa_bloc_7_a_29">Cite Dejmaa Bloc 7 à 29</option>
<option value="cite_dejmaa_bloc_abcden">Cite Dejmaa Bloc Abcden</option>
<option value="cite_djemaa_bloc_fgimhkl">Cite Djemaa Bloc Fgimhkl</option>
<option value="cite_djemaa_bloc18_et_19_et_37a42">Cite Djemaa Bloc18 et 19 et 37 à 42</option>
<option value="cite_plateau">Cite Plateau</option>
<option value="dandoune">Dandoune</option>
<option value="dar_laman">Dar Laman</option>
<option value="derb_baladia">Derb Baladia</option>
<option value="derb_bouchountouf">Derb Bouchountouf</option>
<option value="derb_chourfa">Derb Chourfa</option>
<option value="derb_douma">Derb Douma</option>
<option value="derb_el_kabir">Derb El Kabir</option>
<option value="derb_el_kheir">Derb El Kheir</option>
<option value="derb_el_manjra">Derb El Manjra</option>
<option value="derb_el_mitre">Derb El Mitre</option>
<option value="derb_fokara">Derb Fokara</option>
<option value="derb_fraiha">Derb Fraiha</option>
<option value="derb_ghleff">Derb Ghleff</option>
<option value="derb_jdid">Derb Jdid</option>
<option value="derb_khalid">Derb Khalid</option>
<option value="derb_khalifa_ben_msik">Derb Khalifa Ben Msik</option>
<option value="derb_khlid">Derb Khlid</option>
<option value="derb_korea">Derb Korea</option>
<option value="derb_laadam">Derb Laadam</option>
<option value="derb_laalou_h_al_houda">Derb Laalou H Al Houda</option>
<option value="derb_lahjar">Derb Lahjar</option>
<option value="derb_manjra">Derb Manjra</option>
<option value="derb_mimouna">Derb Mimouna</option>
<option value="derb_my_charif">Derb My Charif</option>
<option value="derb_omar_secteur_1">Derb Omar Secteur 1</option>
<option value="derb_omar_secteur_2">Derb Omar Secteur 2</option>
<option value="derb_sadni">Derb Sadni</option>
<option value="derb_salama">Derb Salama</option>
<option value="deux_mars">Deux Mars</option>
<option value="diyar">Diyar</option>
<option value="douar_ouled_jmel">Douar Ouled Jmel</option>
<option value="douar_si_ghanem">Douar Si Ghanem</option>
<option value="douar_sidi_ahmed_belhcen">Douar Sidi Ahmed Belhcen</option>
<option value="douar_sidi_brahim">Douar Sidi Brahim</option>
<option value="drissia_i_et_iii">Drissia I et III</option>
<option value="drissia_ii_et_iv">Drissia II et IV</option>
<option value="eddouha_al_faal">Eddouha Al Faal</option>
<option value="el_alia">El Alia</option>
<option value="el_hadika_hay_rahmani">El Hadika-Hay Rahmani</option>
<option value="el_hana">El Hana</option>
<option value="el_hank">El Hank</option>
<option value="el_manar">El Manar</option>
<option value="el_mansour">El Mansour</option>
<option value="emerance_2">Emerance 2</option>
<option value="esperence_1_et_2">Espérence 1 et 2</option>
<option value="essaada">Essaada</option>
<option value="essafa">Essafa</option>
<option value="famille_française">Famille Française</option>
<option value="farida">Farida</option>
<option value="ferara">Ferara</option>
<option value="ferme_br_et_anne">Ferme Br et anne</option>
<option value="fida">Fida</option>
<option value="florida_imb">Florida"Imb"</option>
<option value="florida_villa">Florida"Villa"</option>
<option value="france_ville">France Ville</option>
<option value="ghautier">Ghautier</option>
<option value="grigouane">Grigouane</option>
<option value="habiba">Habiba</option>
<option value="habous">Habous</option>
<option value="hadakat_oum_rabii">Hadakat Oum Rabii</option>
<option value="haddaouia">Haddaouia</option>
<option value="hadikat_oum_rabir">Hadikat Oum Rabir</option>
<option value="haj_fateh">Haj Fateh</option>
<option value="hakar_1_2_3">Hakar 1-2-3</option>
<option value="hamza">Hamza</option>
<option value="hassania">Hassania</option>
<option value="hat_al_houria">Hat Al Houria</option>
<option value="hay_al_fath_3">Hay Al Fath 3</option>
<option value="hay_al_jawhra">Hay Al Jawhra</option>
<option value="hay_al_karia">Hay Al Karia</option>
<option value="hay_al_manssour">Hay Al Manssour</option>
<option value="hay_al_ourda">Hay Al Ourda</option>
<option value="hay_amal">Hay Amal</option>
<option value="hay_chabab">Hay Chabab</option>
<option value="hay_dakhla">Hay Dakhla</option>
<option value="hay_el_baraka_al_houda">Hay El Baraka Al Houda</option>
<option value="hay_el_farah">Hay El Farah</option>
<option value="hay_el_hana">Hay El Hana</option>
<option value="hay_el_masjid">Hay El Masjid</option>
<option value="hay_ennour">Hay Ennour</option>
<option value="hay_falah_massira_iii">Hay Falah Massira III</option>
<option value="hay_hassani">Hay Hassani</option>
<option value="hay_la_gare">Hay La Gare</option>
<option value="hay_la_vill_et_te">Hay La Vill et te</option>
<option value="hay_mohammadi">Hay Mohammadi</option>
<option value="hay_moustabano">Hay Moustabano</option>
<option value="hay_my_abdellah">Hay My Abdellah</option>
<option value="hay_omar_ibn_khattab">Hay Omar Ibn Khattab</option>
<option value="hay_palestine">Hay Palestine</option>
<option value="hay_raja">Hay Raja</option>
<option value="hay_rakboute">Hay Rakboute</option>
<option value="hay_roche_noires">Hay Roche Noires</option>
<option value="hay_sadri">Hay Sadri</option>
<option value="hay_sadri_my_rachid_i">Hay Sadri My Rachid I</option>
<option value="hay_salama_i">Hay Salama I</option>
<option value="hay_salama_iii">Hay Salama III</option>
<option value="hay_sarazane">Hay Sarazane</option>
<option value="hay_tissir">Hay Tissir</option>
<option value="hay_tiznit">Hay Tiznit</option>
<option value="hdioui">Hdioui</option>
<option value="quartier_hopitaux">Quartier Hopitaux</option>
<option value="houria">Houria</option>
<option value="housni">Housni</option>
<option value="ibn_khldoune">Ibn Khldoune</option>
<option value="ideal">Idéal</option>
<option value="ifriquia_hakam2">Ifriquia Hakam2</option>
<option value="inara_i">Inara I</option>
<option value="inara_ii">Inara II</option>
<option value="itissal_1_2_3">Itissal 1-2-3</option>
<option value="jamila">Jamila</option>
<option value="jamila_1">Jamila 1</option>
<option value="jamila_1_massoudia">Jamila 1 Massoudia</option>
<option value="jamila_3">Jamila 3</option>
<option value="jamila_4">Jamila 4</option>
<option value="jamila_4_jamila_5">Jamila 4 Jamila 5</option>
<option value="jamila_5">Jamila 5</option>
<option value="jamila_7_et_6">Jamila 7 et 6</option>
<option value="jamila1_ksar_bhar">Jamila1 Ksar Bhar</option>
<option value="jawadi_alhad_aljadid">Jawadi Alhad Aljadid</option>
<option value="jnanate">Jnanate</option>
<option value="kalojira_hassania_1_2_3">Kalojira Hassania 1-2-3</option>
<option value="kasbat_amine">Kasbat Amine</option>
<option value="kastor">Kastor</option>
<option value="katafa">Katafa</option>
<option value="khawrizmi">Khawrizmi</option>
<option value="khouzama">Khouzama</option>
<option value="krikere_al_adarissa">Krikere Al Adarissa</option>
<option value="krimate">Krimate</option>
<option value="la_coline_(sidi_maarouf)">La Coline (Sidi Maarouf)</option>
<option value="laayoune">Laayoune</option>
<option value="lagidonde">Lagidonde</option>
<option value="lahjajma">Lahjajma</option>
<option value="lalla_meriem">Lalla Meriem</option>
<option value="lanchang">Lanchang</option>
<option value="laroussi_chama">Laroussi - Chama</option>
<option value="laya">Laya</option>
<option value="laymoune">Laymoune</option>
<option value="les_champs_d_anfa">Les Champs D'anfa</option>
<option value="lina">Lina</option>
<option value="lissassfa_1">Lissassfa 1</option>
<option value="lissassfa_2_3">Lissassfa 2, 3</option>
<option value="lot_al_warda">Lot Al Warda</option>
<option value="lot_azemmouri">Lot Azemmouri</option>
<option value="lot_chefchaouini">Lot Chefchaouini</option>
<option value="lot_fadl_et_safia">Lot Fadl et Safia</option>
<option value="lot_meryem">Lot Meryem</option>
<option value="lot_reda">Lot Réda</option>
<option value="lot_reyane">Lot Reyane</option>
<option value="lot_sikibia">Lot Sikibia</option>
<option value="maaguize">Maaguize</option>
<option value="maarif">Maarif</option>
<option value="maarif_extention">Maarif Extention</option>
<option value="mabrouka">Mabrouka</option>
<option value="mabrouka_d_samia">Mabrouka D Samia</option>
<option value="mabrouka_my_larbi_alaoui">Mabrouka My Larbi Alaoui</option>
<option value="mabrouka_salama_iii">Mabrouka Salama III</option>
<option value="madinat_ennour">Madinat Ennour</option>
<option value="madinati">Madinati</option>
<option value="mahdia">Mahdia</option>
<option value="mandarona">Mandarona</option>
<option value="mandarouna">Mandarouna</option>
<option value="massira">Massira</option>
<option value="massira_ii_hay_raja_ii">Massira II Hay Raja II</option>
<option value="massira_jdida">Massira Jdida</option>
<option value="mazola">Mazola</option>
<option value="mçalla">Mçalla</option>
<option value="mechouar">Mechouar</option>
<option value="medina_1">Medina 1</option>
<option value="medina_2">Medina 2</option>
<option value="mers_sultan">Mers Sultan</option>
<option value="mers_sultan_secteur_1">Mers Sultan Secteur 1</option>
<option value="mers_sultan_secteur_2">Mers Sultan Secteur 2</option>
<option value="mimarza">Mimarza</option>
<option value="mimousas">Mimousas</option>
<option value="missimi">Missimi</option>
<option value="my_rachid_(immeble)">My Rachid (Immeble)</option>
<option value="my_rachid_g3">My Rachid G3</option>
<option value="my_rachid_g5_et_6">My Rachid G5 et 6</option>
<option value="my_rachid_group_1">My Rachid Group 1</option>
<option value="my_rachid_ii_diar_essalam">My Rachid II Diar Essalam</option>
<option value="my_thami">My Thami</option>
<option value="m_zouga">M'zouga</option>
<option value="nadia">Nadia</option>
<option value="najam">Najam</option>
<option value="nassim">Nassim</option>
<option value="nejma">Nejma</option>
<option value="nezha">Nezha</option>
<option value="oasis">Oasis</option>
<option value="omaria">Omaria</option>
<option value="operation_lissassfa">Operation Lissassfa</option>
<option value="ouled_taleb">Ouled Taleb</option>
<option value="oulfa">Oulfa</option>
<option value="palmier">Palmier</option>
<option value="paloma_1_et_2">Paloma 1 et 2</option>
<option value="pam">Pam</option>
<option value="panorama">Panorama</option>
<option value="paranfa">Paranfa</option>
<option value="parc_de_la_league_arabe">Parc De La League Arabe</option>
<option value="partie_de_casa_gare">Partie De Casa Gare</option>
<option value="polo">Polo</option>
<option value="proj_et_hassan_ii">Proj et Hassan II</option>
<option value="racine">Racine</option>
<option value="raha">Raha</option>
<option value="raja">Raja</option>
<option value="residanceal_itimade">RésidanceAl Itimade</option>
<option value="residance_al_amal_al_waha">Résidance Al Amal Al Waha</option>
<option value="residance_anssae">Résidance Anssae</option>
<option value="residance_charaf_taroudante">Résidance Charaf Taroudante</option>
<option value="residance_karam_dalia">Résidance Karam Dalia</option>
<option value="residance_mers_zineb_1_et_2">Résidance Mers Zineb 1 et 2</option>
<option value="residance_yakine_al_al_alaa">Résidance Yakine Al Al Alaa</option>
<option value="riad_california">Riad California</option>
<option value="riad_el_ali">Riad El Ali</option>
<option value="riad_oulfa">Riad Oulfa</option>
<option value="riviera">Riviera</option>
<option value="riyad_anfa">Riyad Anfa</option>
<option value="r_milla">R'milla</option>
<option value="rokia">Rokia</option>
<option value="romandie">Romandie</option>
<option value="route_ben_slimane_km_65_a_82">Route Ben Slimane Km 65 à 82</option>
<option value="s.othmane_baladia">S.Othmane Baladia</option>
<option value="s.othmane_jdid">S.Othmane Jdid</option>
<option value="saad_la_khier">Saad La Khier</option>
<option value="saada">Saada</option>
<option value="salaj">Salaj</option>
<option value="salama_iii">Salama III</option>
<option value="salmia_i_h_ennour_i">Salmia I H Ennour I</option>
<option value="salmia_ii">Salmia II</option>
<option value="salmia_ii_ferreille">Salmia II Ferreille</option>
<option value="sdi_bernoussi">Sdi Bernoussi</option>
<option value="sidi_abdellah_ben_lhaj">Sidi Abdellah Ben Lhaj</option>
<option value="sidi_abderrahmane">Sidi Abderrahmane</option>
<option value="sidi_belyout_horloge">Sidi Belyout, Horloge</option>
<option value="sidi_bernoussi">Sidi Bernoussi</option>
<option value="sidi_khadir">Sidi Khadir</option>
<option value="sidi_maarouf_5">Sidi Maarouf 5</option>
<option value="sidi_maartouf_4_et_6">Sidi Maartouf 4 et 6</option>
<option value="sidi_moumen_jdid_g_7_8_9">Sidi Moumen Jdid G 7-8-9</option>
<option value="sidi_moumen_jdid_g1_2">Sidi Moumen Jdid G1-2</option>
<option value="sidi_moumen_jdid_g3_4_5">Sidi Moumen Jdid G3-4-5</option>
<option value="sidi_moumen_lakdim">Sidi Moumen Lakdim</option>
<option value="sidi_othmane">Sidi Othmane</option>
<option value="smara">Smara</option>
<option value="soufiane">Soufiane</option>
<option value="souk_korea">Souk Korea</option>
<option value="takadoum">Takadoum</option>
<option value="tarik">Tarik</option>
<option value="tarik_el_kheir">Tarik El Kheir</option>
<option value="tassahoul">Tassahoul</option>
<option value="touloute_braicha">Touloute Braicha</option>
<option value="val_d_anfa">Val D'anfa</option>
<option value="val_fleurie">Val Fleurie</option>
<option value="warda">Warda</option>
<option value="wiam">Wiam</option>
<option value="widad">Widad</option>
<option value="wifak_1_et_2">Wifak 1 et 2</option>
<option value="wifak_3_et_4">Wifak 3 et 4</option>
<option value="yasmina">Yasmina</option>
<option value="z_i_hay_rahma">Z I Hay Rahma</option>
<option value="z.i_ain_sebaa">Z.I Ain Sebaa</option>
<option value="z.i_bernoussi">Z.I Bernoussi</option>
<option value="zakia">Zakia</option>
<option value="zarhoune_walili">Zarhoune Walili</option>
<option value="zenata">Zenata</option>
<option value="zineb">Zineb</option>
<option value="zone_industrielle">Zone Industrielle</option>
<option value="zone_industrielle_oukacha">Zone Industrielle Oukacha</option>
<option value="zoubair">Zoubair</option>