<option value="3ieme_arrodissement">3Ième Arrodissement</option>
<option value="4eme_arrondissement">4Ème Arrondissement</option>
<option value="assalam">Assalam</option>
<option value="avenuebir_an_zarane_cite_al_qods">AvenueBir An Zarane Cité Al Qods</option>
<option value="avenuemohamed_raffi">AvenueMohamed Raffi</option>
<option value="avenue_abderrahman_doukali">Avenue Abderrahman Doukali</option>
<option value="avenue_boucahib_doukkali_(les_impaire_de_1a69)">Avenue Boucahib Doukkali (Les Impaire De 1à69)</option>
<option value="avenue_boucahib_doukkali_(les_paires_de_2a_84)">Avenue Boucahib Doukkali (Les Paires De 2à 84)</option>
<option value="avenue_boucahib_doukkali_(les_impaire_de_71a133)">Avenue Boucahib Doukkali (Les Impaire De 71à133)</option>
<option value="avenue_boucahib_doukkali_(les_paires_de_86_a_148)">Avenue Boucahib Doukkali (Les Paires De 86 à 148)</option>
<option value="avenue_aderrahman_doukali">Avenue Aderrahman Doukali</option>
<option value="avenue_ahmed_chawki">Avenue Ahmed Chawki</option>
<option value="avenue_al_qods">Avenue Al Qods</option>
<option value="avenue_b_badis_cite_al_qods">Avenue B Badis Cité Al Qods</option>
<option value="avenue_baghdad">Avenue Baghdad</option>
<option value="avenue_bandoeng_1ere_partie">Avenue Bandoeng 1Ère Partie</option>
<option value="avenue_bir_anzarane_cote_gauch">Avenue Bir Anzarane :Coté Gauch</option>
<option value="cite_des_cadres_ocp">Cité Des Cadres Ocp</option>
<option value="citee_des_hors_cadre_ocp">Citée Des Hors Cadre Ocp</option>
<option value="avenue_bir_anzarane_cote_droit">Avenue Bir Anzarane Coté Droit</option>
<option value="avenue_biranzarane">Avenue Biranzarane</option>
<option value="avenue_brahim_roudani">Avenue Brahim Roudani</option>
<option value="avenue_chouhada_(lalla_zahra)">Avenue Chouhada (Lalla Zahra)</option>
<option value="avenue_chouhada_(villa)">Avenue Chouhada (Villa)</option>
<option value="avenue_des_far(de_47a35)">Avenue Des Far(De 47à35)</option>
<option value="avenue_des_far_(de_2_a_14)">Avenue Des Far (De 2 à 14)</option>
<option value="avenue_des_fars_de_5a_19">Avenue Des Fars De 5à 19</option>
<option value="avenue_des_nation_unies">Avenue Des Nation Unies</option>
<option value="avenue_el_massira">Avenue El Massira</option>
<option value="avenue_ennakhil">Avenue Ennakhil</option>
<option value="avenue_hassan_ii">Avenue Hassan II</option>
<option value="avenue_houman_fatouaki">Avenue Houman Fatouaki</option>
<option value="avenue_ibn_badis_n_1a_11">Avenue Ibn Badis N°1à 11</option>
<option value="avenue_ibn_khaldoune">Avenue Ibn Khaldoune</option>
<option value="avenue_ibn_toumert">Avenue Ibn Toumert</option>
<option value="avenue_jamia_arabia">Avenue Jamia Arabia</option>
<option value="avenue_khalil_jabrane">Avenue Khalil Jabrane</option>
<option value="avenue_laaayoune">Avenue Laaayoune</option>
<option value="avenue_les_arbres">Avenue Les Arbres</option>
<option value="avenue_maghreb_el_arabi">Avenue Maghreb El Arabi</option>
<option value="avenue_mly_abdelhafid">Avenue Mly Abdelhafid</option>
<option value="avenue_mohamed_rafai)">Avenue Mohamed Rafai)</option>
<option value="avenue_mohamed_trii">Avenue Mohamed Trii</option>
<option value="avenue_mohamed_vde_2_a2_72">Avenue Mohamed VDe 2 à2 72</option>
<option value="avenue_mohamed_vde_3_a_279">Avenue Mohamed VDe 3 à 279</option>
<option value="avenue_mohamed_v_(les_paires)">Avenue Mohamed V (Les Paires)</option>
<option value="avenue_mouahidine">Avenue Mouahidine</option>
<option value="avenue_moukawama">Avenue Moukawama</option>
<option value="avenue_my_arbi_alaoui">Avenue My Arbi Alaoui</option>
<option value="avenue_pasteur">Avenue Pasteur</option>
<option value="avenue_rif">Avenue Rif</option>
<option value="avenue_sanabil">Avenue Sanabil</option>
<option value="avenue_tahrir">Avenue Tahrir</option>
<option value="avenue_tahrir_prolonge">Avenue Tahrir Prolongé</option>
<option value="avenue_varenne">Avenue Varenne</option>
<option value="avenue_woroud">Avenue Woroud</option>
<option value="avenue_zarktouni_de_419_a_19">Avenue Zarktouni De 419 à 19</option>
<option value="avenue_zerktouni_de_2_a_278_(paires)">Avenue Zerktouni De 2 à 278 (Paires)</option>
<option value="bd_mohamed_vde">Bd Mohamed VDe</option>
<option value="bd_suez">Bd Suèz</option>
<option value="bir_al_kharba">Bir Al Kharba</option>
<option value="bvd_ennasr">Bvd Ennasr</option>
<option value="bvd_madina_mounawara">Bvd Madina Mounawara</option>
<option value="bvd_mly_smail">Bvd Mly Smail</option>
<option value="bvd_traii">Bvd Traii</option>
<option value="camping_international">Camping International</option>
<option value="carriere_hassan">Carrière Hassan</option>
<option value="carriere_khadija">Carrière Khadija</option>
<option value="central_laitiaire">Central Laitiaire</option>
<option value="centre_commercial_acima">Centre Commercial Acima</option>
<option value="centre_commercial_kodiat_ben_driss">Centre Commercial Kodiat Ben Driss</option>
<option value="centre_commercial_saada">Centre Commercial Saada</option>
<option value="centre_commercil_central">Centre Commercil Central</option>
<option value="chariaa_a.bn_tabit">Chariaa A.Bn Tabit</option>
<option value="cite_comm_mosque_immam_ali">Cité Comm Mosqué Immam Ali</option>
<option value="cite_des_cadres_ocp">Cité Des Cadres Ocp</option>
<option value="citeeoncf">CitéeOncf</option>
<option value="citee_des_hors_cadre">Citée Des Hors Cadre</option>
<option value="citee_el_quods">Citée El Quods</option>
<option value="citee_kodiat_ben_driss">Citée Kodiat Ben Driss:</option>
<option value="club_tenis">Club Ténis</option>
<option value="cncervation_fonciere">Cncervation Fonciere</option>
<option value="college_abdelkarim_khattabi">College Abdelkarim Khattabi</option>
<option value="college_al_qods">Collège Al Qods</option>
<option value="college_elhansali">Collége ElHansali</option>
<option value="college_el_manar">Collège El Manar</option>
<option value="college_moujahi_el_ayachi">Collège Moujahi El Ayachi</option>
<option value="complexe_touristique">Complexe Touristique</option>
<option value="coopmly_rachid">CoopMly Rachid</option>
<option value="coop_nour">Coop Nour</option>
<option value="coop_abdelmoumen_mouahidi">Coop Abdelmoumen Mouahidi</option>
<option value="coop_abderrahmane_doukkali">Coop Abderrahmane Doukkali</option>
<option value="coop_al_amal">Coop Al Amal</option>
<option value="coop_al_majd">Coop Al Majd</option>
<option value="coop_al_mital">Coop Al Mital</option>
<option value="coop_amane">Coop Amane</option>
<option value="coop_assanad">Coop Assanad</option>
<option value="coop_badre">Coop Badre</option>
<option value="coop_el_khair">Coop El Khair</option>
<option value="coop_el_wahda">Coop El Wahda</option>
<option value="coop_el_wiam">Coop El Wiam</option>
<option value="coop_ennahda">Coop Ennahda</option>
<option value="coop_essabil">Coop Essabil</option>
<option value="coop_essafa">Coop Essafa</option>
<option value="coop_essalam">Coop Essalam</option>
<option value="coop_housna">Coop Housna</option>
<option value="coop_ibn_khaldoun">Coop Ibn Khaldoun</option>
<option value="coop_massira_al_khadra">Coop Massira Al Khadra</option>
<option value="coop_mly_abdellah">Coop Mly Abdellah</option>
<option value="coop_mohamadia_nd">Coop Mohamadia Nd</option>
<option value="coop_mouhit">Coop Mouhit</option>
<option value="coop_nour_el_mouhit">Coop Nour El Mouhit</option>
<option value="coop_raja">Coop Raja</option>
<option value="coop_sana_fidiya _de_1_a_211">Coop Sana Fidiya :De 1 à 211</option>
<option value="coop_tadamoun">Coop Tadamoun</option>
<option value="coop_taraj">Coop Taraj</option>
<option value="coop_tit">Coop Tit</option>
<option value="coop_waha">Coop Waha</option>
<option value="dar_chabab">Dar Chabab</option>
<option value="delegation_d’artisana">Délégation D’artisana</option>
<option value="delegation_de_l’artisana">Delegation De L’artisana</option>
<option value="delegation_de_l’habitat">Délégation De L’habitat</option>
<option value="depot_aboulfraj">Depot Aboulfraj</option>
<option value="depot_bomenzal">Depot Bomenzal</option>
<option value="der_el_khayala">Der El Khayala</option>
<option value="derb_ben_dagha">Derb Ben Dagha</option>
<option value="derb_ben_driss">Derb Ben Driss</option>
<option value="derb_ben_slimane">Derb Ben Slimane</option>
<option value="derb_el_aarsa">Derb El Aarsa</option>
<option value="derb_el_arsa">Derb El Arsa</option>
<option value="derb_el_barkaoui">Derb El Barkaoui</option>
<option value="derb_el_ferrane">Derb El Ferrane</option>
<option value="derb_el_gabbas">Derb El Gabbas</option>
<option value="derb_el_hajjar">Derb El Hajjar</option>
<option value="derb_el_hajjar ">Derb El Hajjar :</option>
<option value="derb_el_jirari_2_partie">Derb El Jirari 2°Partie</option>
<option value="derb_el_jirari_3_partie">Derb El Jirari 3°Partie</option>
<option value="derb_fquih_belhaiba">Derb Fquih Belhaiba</option>
<option value="derb_haj_chaoui">Derb Haj Chaoui</option>
<option value="derb_jdid">Derb Jdid</option>
<option value="derb_jirrari_1_partie">Derb Jirrari 1°Partie</option>
<option value="derb_lafquih_el_mendili">Derb Lafquih El Mendili</option>
<option value="derb_lahlali">Derb Lahlali</option>
<option value="derb_mohamed_chaoui_guerrab">Derb Mohamed Chaoui Guerrab</option>
<option value="derb_my_ahmed_tahiri">Derb My Ahmed Tahiri</option>
<option value="derb_ouadoudi_haboul">Derb Ouadoudi Haboul</option>
<option value="derb_si_tibari">Derb Si Tibari</option>
<option value="derb_si_tibari ">Derb Si Tibari </option>
<option value="derb_touil">Derb Touil</option>
<option value="douar_al_bahara">Douar Al Bahara</option>
<option value="douar_bouali">Douar Bouali</option>
<option value="douar_charkawa">Douar Charkawa</option>
<option value="douar_lahouna">Douar Lahouna</option>
<option value="douar_lghazoua_(rue_de_1a9)">Douar Lghazoua (Rue De 1à9)</option>
<option value="ecole_abdellah_ben_charki">Ecole Abdellah Ben Charki</option>
<option value="ecole_chiraz">Ecole Chiraz</option>
<option value="ecole_hoteliere">Ecole Hotelière</option>
<option value="ecole_sidi_moussa">Ecole Sidi Moussa</option>
<option value="ecole_traii_fille">Ecole Traii Fille</option>
<option value="ecolt_trii_mixte">Ecolt Trii Mixte</option>
<option value="enregistrement_et_timbre">Enregistrement et Timbre</option>
<option value="gare_routiere">Gare Routiére</option>
<option value="ibn_sabili">Ibn Sabili</option>
<option value="imbl_dounia">Imbl Dounia</option>
<option value="immeuble_11_(a_b)">Immeuble 11 (A, B)</option>
<option value="immeuble_73_(1_2)">Immeuble 73 (1, 2)</option>
<option value="immeuble_77">Immeuble 77</option>
<option value="immeuble_78">Immeuble 78</option>
<option value="immeuble_alward">Immeuble Alward</option>
<option value="immeuble_b_lot_zahraoui">Immeuble B Lot Zahraoui</option>
<option value="immeuble_b_lot_zahraoui ">Immeuble B Lot Zahraoui :</option>
<option value="immeuble_baroudi">Immeuble Baroudi</option>
<option value="immeuble_belkouchi">Immeuble Belkouchi</option>
<option value="immeuble_ben_hamdounia">Immeuble Ben Hamdounia</option>
<option value="immeuble_breija">Immeuble Breija</option>
<option value="immeuble_chahbi">Immeuble Chahbi</option>
<option value="immeuble_el_fath">Immeuble El Fath</option>
<option value="immeuble_g _f _k ">Immeuble G ;F ;K ;</option>
<option value="immeuble_habouss_a_et_b">Immeuble Habouss A et B</option>
<option value="immeuble_harraz_b">Immeuble Harraz B</option>
<option value="immeuble_ibn_khaldoune">Immeuble Ibn Khaldoune</option>
<option value="immeuble_jaouhar">Immeuble Jaouhar</option>
<option value="immeuble_la_liberte">Immeuble La Liberté</option>
<option value="immeuble_mabrouk">Immeuble Mabrouk</option>
<option value="immeuble_mansour_billah">Immeuble Mansour Billah</option>
<option value="immeuble_meniar">Immeuble Meniar</option>
<option value="immeuble_moujib">Immeuble Moujib</option>
<option value="immeuble_ooum_aaz">Immeuble Ooum Aaz</option>
<option value="immeuble_ouasis_82">Immeuble Ouasis 82</option>
<option value="immeuble_oulfa">Immeuble Oulfa</option>
<option value="immeuble_reda">Immeuble Reda</option>
<option value="immeuble_sakif">Immeuble Sakif</option>
<option value="immeuble_sophal">Immeuble Sophal</option>
<option value="immeuble_tchikito">Immeuble Tchikito</option>
<option value="immeuble_tounsi">Immeuble Tounsi</option>
<option value="immeuble_zerriab">Immeuble Zerriab</option>
<option value="kisariat_belfakir">Kisariat Belfakir</option>
<option value="kisariat_el_fath">Kisariat El Fath</option>
<option value="kisariat_el_kadiri">Kisariat El Kadiri</option>
<option value="kisariat_souss">Kisariat Souss</option>
<option value="kissariat_ennasr">Kissariat Ennasr</option>
<option value="kissariat_nahoun">Kissariat Nahoun</option>
<option value="kissariat_nasciri">Kissariat Nasciri</option>
<option value="kissariat_oued_eddahab">Kissariat Oued Eddahab</option>
<option value="kissariat_tazi">Kissariat Tazi</option>
<option value="kissariat_tounssi">Kissariat Tounssi</option>
<option value="kissariat_yassin">Kissariat Yassin</option>
<option value="kissariat_zaryab*immeuble_zaryab">Kissariat Zaryab*Immeuble Zaryab</option>
<option value="kodiat_basio_(lahlou)">Kodiat Basio (Lahlou)</option>
<option value="l’entraide_nationale">L’entraide Nationale</option>
<option value="l’hygienne">L’hygienne</option>
<option value="laboratoire_fayzar">Laboratoire Fayzar</option>
<option value="lotal_ghazoua">LotAl Ghazoua</option>
<option value="lot_240_(ocp)">Lot 240 (Ocp)</option>
<option value="lot_al_adarissa">Lot Al Adarissa</option>
<option value="lot_al_andalous">Lot Al Andalous</option>
<option value="lot_al_assdikae">Lot Al Assdikae</option>
<option value="lot_al_majd">Lot Al Majd</option>
<option value="lot_al_manar">Lot Al Manar</option>
<option value="lot_al_manar_z1_z2_z9">Lot Al Manar Z1 Z2 Z9</option>
<option value="lot_al_manzah _souprija _de_a_at">Lot Al Manzah :Souprija :De A àt</option>
<option value="lot_al_wafa_de_1_a_64">Lot Al Wafa De 1 à 64</option>
<option value="lot_al_ward">Lot Al Ward</option>
<option value="lot_annajd_i_b1ab10_a4aa2_c1">Lot Annajd I: B1àb10, A4àa2, C1</option>
<option value="lot_annajd_ii">Lot Annajd II</option>
<option value="lot_annassim ">Lot Annassim :</option>
<option value="lot_annouar">Lot Annouar</option>
<option value="lot_annouzha">Lot Annouzha</option>
<option value="lot_assadaka">Lot Assadaka</option>
<option value="lot_assafa">Lot Assafa</option>
<option value="lot_assalam_ext_1">Lot Assalam Ext 1</option>
<option value="lot_assalam_ext_2">Lot Assalam Ext 2</option>
<option value="lot_asslam">Lot Asslam</option>
<option value="lot_ati_llah">Lot Ati Llah:</option>
<option value="lot_bel_attar">Lot Bel Attar</option>
<option value="lot_ben_dahan">Lot Ben Dahan</option>
<option value="lot_benomar">Lot Benomar</option>
<option value="lot_bir_anzarane">Lot Bir Anzarane</option>
<option value="lot_chems">Lot Chems</option>
<option value="lot_cherkawa_i_ii _etiii">Lot Cherkawa I, II  etIII</option>
<option value="lot_d’ahbitation_moukawama">Lot D’ahbitation Moukawama</option>
<option value="lot_des_far">Lot Des Far</option>
<option value="lot_el_hilal">Lot El Hilal</option>
<option value="lot_el_kheir">Lot El Kheir</option>
<option value="lot_deffar">Lot Deffar</option>
<option value="lot_ennaouras">Lot Ennaouras</option>
<option value="lot_ennasr">Lot Ennasr</option>
<option value="lot_ennouste">Lot Ennouste</option>
<option value="lot_erraja">Lot Erraja</option>
<option value="lot_farah">Lot Farah</option>
<option value="lot_fath_faycal">Lot Fath Faycal</option>
<option value="lot_faycal">Lot Faycal</option>
<option value="lot_ferdaous">Lot Ferdaous</option>
<option value="lot_harraz">Lot Harraz</option>
<option value="lot_hassania">Lot Hassania</option>
<option value="lot_hind">Lot Hind</option>
<option value="lot_ibno_nafis">Lot Ibno Nafis</option>
<option value="lot_imane">Lot Imane</option>
<option value="lot_karam">Lot Karam</option>
<option value="lot_karima">Lot Karima</option>
<option value="lot_kenza">Lot Kenza</option>
<option value="lot_kohen">Lot Kohen</option>
<option value="lot_lahlou">Lot Lahlou</option>
<option value="lot_lamia">Lot Lamia</option>
<option value="lot_les_vagues">Lot Les Vagues</option>
<option value="lot_melk_si_bachir ">Lot Melk Si Bachir :</option>
<option value="lot_mostakbal">Lot Mostakbal</option>
<option value="lot_mouahidine">Lot Mouahidine</option>
<option value="lot_naim_allah ">Lot Naim Allah :</option>
<option value="lot_najah_ii">Lot Najah II</option>
<option value="lot_nakhl">Lot Nakhl</option>
<option value="lot_nouress_i_et_ii">Lot Nouress I et II</option>
<option value="lot_nouzha">Lot Nouzha</option>
<option value="lot_palestino">Lot Palestino</option>
<option value="lot_rafaii">Lot Rafaii</option>
<option value="lot_saada_i">Lot Saada I</option>
<option value="lot_saada_ii">Lot Saada II</option>
<option value="lot_saada_iii">Lot Saada III</option>
<option value="lot_sania">Lot Sania</option>
<option value="lot_sidi_moussa">Lot Sidi Moussa</option>
<option value="lot_sofia">Lot Sofia</option>
<option value="lot_tazi">Lot Tazi</option>
<option value="lot_tissir_allah">Lot Tissir Allah</option>
<option value="lot_tissir ">Lot Tissir </option>
<option value="lot_wardia">Lot Wardia</option>
<option value="lot_wifak">Lot Wifak</option>
<option value="lot_yakout_i_et_ii">Lot Yakout I et II</option>
<option value="lot_zakaria_rte_de_casa">Lot Zakaria Rte De Casa</option>
<option value="lot_zhar">Lot Zhar</option>
<option value="lot_zoubair">Lot Zoubair</option>
<option value="lotissement_al_fath">Lotissement Al Fath</option>
<option value="lotissement_aman_allah">Lotissement Aman Allah</option>
<option value="lotissement_anoaur">Lotissement Anoaur</option>
<option value="lotissement_atiallah ">Lotissement Atiallah :</option>
<option value="lotissement_bendagha">Lotissement Bendagha</option>
<option value="lotissement_brik">Lotissement Brik</option>
<option value="lotissement_dachra_2/3">Lotissement Dachra 2/3</option>
<option value="lotissement_el_amal_1_et_2">Lotissement El Amal 1 et 2</option>
<option value="lotissement_el_harraz">Lotissement El Harraz</option>
<option value="lotissement_el_khadra">Lotissement El Khadra</option>
<option value="lotissement_el_mahdi">Lotissement El Mahdi</option>
<option value="lotissement_essadaka">Lotissement Essadaka</option>
<option value="lotissement_essalam">Lotissement Essalam</option>
<option value="lotissement_fadlallah">Lotissement Fadlallah</option>
<option value="lotissement_fadlallah_f_e_b_c">Lotissement Fadlallah F E B C</option>
<option value="lotissement_fadlallah_ii_a_et_b">Lotissement Fadlallah II A et B</option>
<option value="lotissement_guessous">Lotissement Guessous</option>
<option value="lotissement_hajja_yezza">Lotissement Hajja Yezza</option>
<option value="lotissement_hakima_1_et_2">Lotissement Hakima 1 et 2</option>
<option value="lotissement_jamila">Lotissement Jamila</option>
<option value="lotissement_jaouhara">Lotissement Jaouhara</option>
<option value="lotissement_lamiae">Lotissement Lamiae</option>
<option value="lotissement_lamilha_1ere_partie">Lotissement Lamilha 1Ère Partie</option>
<option value="lotissement_lamilha_2ere_partie">Lotissement Lamilha 2Ère Partie</option>
<option value="lotissement_lamilha_3ere_partie">Lotissement Lamilha 3Ère Partie</option>
<option value="lotissement_lamilha_4ere_partie">Lotissement Lamilha 4Ère Partie</option>
<option value="lotissement_maamora">Lotissement Maamora</option>
<option value="lotissement_maghrib_bina ">Lotissement Maghrib Bina :</option>
<option value="lotissement_mahrach">Lotissement Mahrach</option>
<option value="lotissement_melk_cheikh+_lotissement_asmae_1_et_2 ">Lotissement Melk Cheikh+ Lotissement Asmae 1 et 2 :</option>
<option value="lotissement_nahoun_znati">Lotissement Nahoun Znati</option>
<option value="lotissement_narjiss">Lotissement Narjiss</option>
<option value="lotissement_nasr_mina_allah">Lotissement Nasr Mina Allah</option>
<option value="lotissement_oliv_et_te">Lotissement Oliv et te</option>
<option value="lotissement_reda">Lotissement Réda</option>
<option value="lotissement_safa ">Lotissement Safa :</option>
<option value="lotissement_safi _touri">Lotissement Safi : Touri</option>
<option value="lotissement_samij">Lotissement Samij</option>
<option value="lotissement_soujda_a_et_b">Lotissement Soujda A et B</option>
<option value="lotissement_tibari">Lotissement Tibari</option>
<option value="lotissement_tradville">Lotissement Tradville</option>
<option value="lotissement_trii">Lotissement Trii</option>
<option value="lotissement_yanoubi">Lotissement Yanoubi</option>
<option value="lotissement_zahraoui">Lotissement Zahraoui</option>
<option value="lotissement_zakariua">Lotissement Zakariua</option>
<option value="lotissement_zhiligua">Lotissement Zhiligua</option>
<option value="lotissemey_rjafellah ">Lotissemey Rjafellah :</option>
<option value="lotissemeznt_ennasr">Lotissemeznt Ennasr</option>
<option value="lotissemnt_zouhour">Lotissemnt Zouhour</option>
<option value="lotissment_jack_et_jean">Lotissment Jack et Jean</option>
<option value="lycee_bir_anzarane">Lycée Bir Anzarane</option>
<option value="lycee_l’angebleu.">Lycée L’angeBleu.</option>
<option value="lycee_technique">Lycée Téchnique</option>
<option value="maison_renault">Maison Renault</option>
<option value="marche_central">Marche Central</option>
<option value="marche_de_gros">Marché De Gros</option>
<option value="mellah_46_rues ">Mellah 46 Rues :</option>
<option value="nahj_al_imam_maklik">Nahj Al Imam Maklik</option>
<option value="nahj_kacem_al_iraki">Nahj Kacem Al Iraki</option>
<option value="najmat_al_janoub_ii">Najmat Al Janoub II</option>
<option value="najmat_al_janoub_iii">Najmat Al Janoub III</option>
<option value="passage_1">Passage 1</option>
<option value="passage_2">Passage 2</option>
<option value="perception_plateau">Perception Plateau</option>
<option value="place_abdelkrim_khattabi">Place Abdelkrim Khattabi</option>
<option value="place_allal_el_kacemi">Place Allal El Kacemi</option>
<option value="place_chouaib_doukkali">Place Chouaib Doukkali</option>
<option value="place_de_canissa">Place De Canissa</option>
<option value="place_de_france">Place De France</option>
<option value="place_el_hansali">Place El Hansali</option>
<option value="place_general_k_et_tani">Place Général K et tani</option>
<option value="place_grande_mosque">Place Grande Mosqué</option>
<option value="place_mly_el_hassan">Place Mly El Hassan</option>
<option value="place_mohamed_v">Place Mohamed V</option>
<option value="place_my_youssef">Place My Youssef</option>
<option value="place_port_said">Place Port Said</option>
<option value="place_sidi_mohamed_ben_abdellah">Place Sidi Mohamed Ben Abdellah</option>
<option value="polyclinique_cnss">Polyclinique Cnss</option>
<option value="port_d’el_jadida">Port D’el Jadida</option>
<option value="quartier_meskiya ">Quartier Méskiya :</option>
<option value="radeej">Radeej</option>
<option value="res_abla">Rés Abla</option>
<option value="resid_najmat_al_janoub_1">Résid Najmat Al Janoub 1</option>
<option value="resid_najmat_al_janoub_2">Résid Najmat Al Janoub 2</option>
<option value="resid_najmat_al_janoub_3">Résid Najmat Al Janoub 3</option>
<option value="resid_najmat_al_janoub_4">Résid Najmat Al Janoub 4</option>
<option value="residanceabla">RésidanceAbla</option>
<option value="residanceamine">RésidanceAmine</option>
<option value="residanceazziyara">RésidanceAzziyara</option>
<option value="residancenajah">RésidanceNajah</option>
<option value="residancenour">RésidanceNour</option>
<option value="residancerachida_(a_b)">RésidanceRachida (A, B)</option>
<option value="residance_al_wafa">Résidance Al Wafa</option>
<option value="residance_al_wifaq">Résidance Al Wifaq</option>
<option value="residance_houdaa1_a2_a3_a4_b1_b2_b3_b">Résidance Houdaa1, A2, A3, A4;B1, B2, B3, B</option>
<option value="residance_rafai">Résidance Rafai</option>
<option value="residence11_janvier">Résidence11 Janvier</option>
<option value="residenceannour">RésidenceAnnour</option>
<option value="residencearraja">RésidenceArraja</option>
<option value="residenceel_jadida">RésidenceEl Jadida</option>
<option value="residenceennojoum">RésidenceEnnojoum</option>
<option value="residencerabiaa">RésidenceRabiaa</option>
<option value="residenceal_amal">RésidenceAl Amal</option>
<option value="residenceamira">RésidenceAmira</option>
<option value="residenceannour_2">RésidenceAnnour 2</option>
<option value="residenceannour_benani">RésidenceAnnour Benani</option>
<option value="residencenadia_(a_b)">RésidenceNadia (A, B)</option>
<option value="residencenaoufal">RésidenceNaoufal</option>
<option value="residencenouzha">RésidenceNouzha</option>
<option value="residence_abou_bakr">Résidence Abou Bakr</option>
<option value="residence_al_amana">Résidence Al Amana</option>
<option value="residence_al_khair">Résidence Al Khair</option>
<option value="residence_al_wafa">Résidence Al Wafa</option>
<option value="residence_al_yousr">Résidence Al Yousr</option>
<option value="residence_amine">Résidence Amine</option>
<option value="residence_anas">Résidence Anas</option>
<option value="residence_annassim">Résidence Annassim</option>
<option value="residence_annouzha">Résidence Annouzha</option>
<option value="residence_arraja_b20">Résidence Arraja B20</option>
<option value="residence_azilal_(a_b)">Résidence Azilal (A, B)</option>
<option value="residence_azzaytoune">Résidence Azzaytoune</option>
<option value="residence_basma">Résidence Basma</option>
<option value="residence_ben_sina">Résidence Ben Sina</option>
<option value="residence_doha">Résidence Doha</option>
<option value="residence_el_khair">Résidence El Khair</option>
<option value="residence_ezzohour">Résidence Ezzohour</option>
<option value="residence_firdaous">Résidence Firdaous</option>
<option value="residence_habiba">Résidence Habiba</option>
<option value="residence_hilal">Résidence Hilal</option>
<option value="residence_ibn_haytam">Résidence Ibn Haytam</option>
<option value="residence_inass_i_et_ii">Résidence Inass I et II</option>
<option value="residence_jamila">Résidence Jamila</option>
<option value="residence_jawhara_272">Résidence Jawhara 272</option>
<option value="residence_kerdous">Résidence Kerdous</option>
<option value="residence_mimousa">Résidence Mimousa</option>
<option value="residence_mouna">Résidence Mouna</option>
<option value="residence_najmat_al_janoub_i">Résidence Najmat Al Janoub I</option>
<option value="residence_oulfa_1_et_2">Résidence Oulfa 1 et 2</option>
<option value="residence_oum_rabiaa">Résidence Oum Rabiaa</option>
<option value="residence_ousra">Résidence Ousra</option>
<option value="residence_reda_allah_a_et_b">Résidence Reda Allah A et B</option>
<option value="residence_riad">Résidence Riad</option>
<option value="residence_salma">Résidence Salma</option>
<option value="residence_sanea_(a_b)">Résidence Sanea (A, B)</option>
<option value="residence_soujdaii">Résidence Soujdaii</option>
<option value="rezsidence_bouchra_de_1_a6">Rézsidence Bouchra De 1 à6</option>
<option value="route_de_l’aviationresidence_al_atlas">Route De L’aviationrésidence Al Atlas</option>
<option value="ru_ahmed_labat_(1a5_2a6)">Ru Ahmed Labat (1à5-2à6)</option>
<option value="ru_moussa_belafakir">Ru Moussa Belafakir</option>
<option value="rua_ahmed_ben_driss">Rua Ahmed Ben Driss</option>
<option value="rua_fkih_el_youssi">Rua Fkih El Youssi</option>
<option value="saada">Saada</option>
<option value="saniat_al_mourakib">Saniat Al Mourakib</option>
<option value="souk_allal_kasmi">Souk Allal Kasmi</option>
<option value="station_afrikia">Station Afrikia</option>
<option value="station_mobile_n">Station Mobile N</option>
<option value="station_shell_plac_de_france_n_12">Station Shell Plac De France N°12</option>
<option value="station_total">Station Total</option>
<option value="suppermarche_ocean">SuppérMarché Océan</option>
<option value="tribunal">Tribunal</option>
<option value="wilaya_sn">Wilaya Sn</option>
<option value="zone_industrielle">Zone Industrielle</option>