<option value="adarissa">Adarissa</option>
<option value="agadir">Agadir</option>
<option value="ain_azaltin">Ain Azaltin</option>
<option value="ain_harroune">Ain Harroune</option>
<option value="ain_kadous">Ain Kadous</option>
<option value="ain_laaroussi">Ain Laaroussi</option>
<option value="ain_noukbi">Ain Noukbi</option>
<option value="ain_skatou">Ain Skatou</option>
<option value="ain_tokbi">Ain Tokbi</option>
<option value="ait_squatou">Ait Squatou</option>
<option value="al_atlas">Al Atlas</option>
<option value="al_wifaq">Al Wifaq</option>
<option value="ancienne_medina">Ancienne Medina</option>
<option value="arrachidia">Arrachidia</option>
<option value="av._des_far">Av. Des Far</option>
<option value="av._des_palestines">Av. Des Palestines</option>
<option value="av._lalla_hassna">Av. Lalla Hassna</option>
<option value="av._lalla_meryem">Av. Lalla Meryem</option>
<option value="av._les_allaouites">Av. Les Allaouites</option>
<option value="av._les_almohades">Av. Les Almohades</option>
<option value="av._moulay_youssef">Av. Moulay Youssef</option>
<option value="av._saint_louis">Av. Saint Louis</option>
<option value="awinate_el_hajaje">Awinate El Hajaje</option>
<option value="aze_ellah_hay_saadiyine">Aze Ellah Hay Saadiyine</option>
<option value="bab_el_hamra">Bab El Hamra</option>
<option value="bab_essafir">Bab Essafir</option>
<option value="bab_ftouh">Bab Ftouh</option>
<option value="bab_gaisa">Bab Gaisa</option>
<option value="bab_khoukha">Bab Khoukha</option>
<option value="bab_mahrouk">Bab Mahrouk</option>
<option value="bab_seffer">Bab Seffer</option>
<option value="babe_el_ghoule">Babe El Ghoule</option>
<option value="badr">Badr</option>
<option value="batha">Batha</option>
<option value="bd_allal_ben_abdellah">Bd Allal Ben Abdellah</option>
<option value="bd_ibnou_el_khateb">Bd Ibnou El Khateb</option>
<option value="bd._ahmed_chaouki">Bd. Ahmed Chaouki</option>
<option value="bd._allal_ben_abdellah">Bd. Allal Ben Abdellah</option>
<option value="bd._hassan_ii">Bd. Hassan II</option>
<option value="bd._ibnou_khateb">Bd. Ibnou Khateb</option>
<option value="bd._imam_ali">Bd. Imam Ali</option>
<option value="bd._mohamed_v">Bd. Mohamed V</option>
<option value="bd._moulay_rachid">Bd. Moulay Rachid</option>
<option value="bd._oubaida_bnou_el_jarah">Bd. Oubaida Bnou El Jarah</option>
<option value="bd._slaoui">Bd. Slaoui</option>
<option value="belkhiate">Belkhiate</option>
<option value="ben_debbab">Ben Debbab</option>
<option value="ben_slimane">Ben Slimane</option>
<option value="ben_souda_centre">Ben Souda Centre</option>
<option value="bensouda">Bensouda</option>
<option value="benzakour">Benzakour</option>
<option value="bled_ain_edrissi">Bled Ain Edrissi</option>
<option value="bled_ben_hayoun">Bled Ben Hayoun</option>
<option value="bled_ben_mekhlouf">Bled Ben Mekhlouf</option>
<option value="bled_ben_sliman">Bled Ben Sliman</option>
<option value="bled_ben_souda">Bled Ben Souda</option>
<option value="bled_benani">Bled Benani</option>
<option value="bled_chadi">Bled Chadi</option>
<option value="bled_chami">Bled Chami</option>
<option value="bled_el_habouss">Bled El Habouss</option>
<option value="bled_eliraki">Bled Eliraki</option>
<option value="bled_guenoun">Bled Guenoun</option>
<option value="bled_hamouda_slaoui">Bled Hamouda Slaoui</option>
<option value="bled_jabri">Bled Jabri</option>
<option value="bled_lahlou">Bled Lahlou</option>
<option value="bled_megzari">Bled Megzari</option>
<option value="bled_rahri">Bled Rahri</option>
<option value="bled_rais">Bled Rais</option>
<option value="bled_sadani">Bled Sadani</option>
<option value="bled_sakiyine">Bled Sakiyine</option>
<option value="bled_skali">Bled Skali</option>
<option value="bled_sklia">Bled Sklia</option>
<option value="bled_slaoui">Bled Slaoui</option>
<option value="bled_tazi">Bled Tazi</option>
<option value="bled_yahriyine">Bled Yahriyine</option>
<option value="bou_jloud">Bou Jloud</option>
<option value="bouajjara">Bouajjara</option>
<option value="boudeher">Boudeher</option>
<option value="bourjoue">Bourjoue</option>
<option value="bourmana">Bourmana</option>
<option value="bourniyate">Bourniyate</option>
<option value="carriere_el_hajoui">Carrière El Hajoui</option>
<option value="centre_ville">Centre Ville</option>
<option value="champs_de_course">Champs De Course</option>
<option value="charaybi">Charaybi</option>
<option value="cite_jardin_de_fes_i_et_ii">Cité Jardin De Fès I et II</option>
<option value="dehere_erricha">Dehere Erricha</option>
<option value="dhare_mahraze">Dhare Mahraze</option>
<option value="dike_siloune">Dike Siloune</option>
<option value="doha">Doha</option>
<option value="dokkarate">Dokkarate</option>
<option value="douah_riafa">Douah Riafa</option>
<option value="douar_bir">Douar Bir</option>
<option value="douar_el_handia">Douar El Handia</option>
<option value="douar_el_oudaya">Douar El Oudaya</option>
<option value="douar_gueriou">Douar Gueriou</option>
<option value="douar_riafa">Douar Riafa</option>
<option value="douar_skiri">Douar Skiri</option>
<option value="douh">Douh</option>
<option value="echara">Echara</option>
<option value="el_adarissa">El Adarissa</option>
<option value="el_amal_route_ain_chekef">El Amal Route Ain Chekef</option>
<option value="el_bathaa">El Bathaa</option>
<option value="el_borj">El Borj</option>
<option value="el_bourniate">El Bourniate</option>
<option value="el_farah">El Farah</option>
<option value="el_handia">El Handia</option>
<option value="el_hay_el_hassani">El Hay El Hassani</option>
<option value="el_hay_el_mohammadi">El Hay El Mohammadi</option>
<option value="el_jadid">El Jadid</option>
<option value="el_loujeriyine">El Loujeriyine</option>
<option value="el_makhfia">El Makhfia</option>
<option value="el_mariniyine">El Mariniyine</option>
<option value="el_massira">El Massira</option>
<option value="el_mellah">El Mellah</option>
<option value="el_menzeh">El Menzeh</option>
<option value="el_merja">El Merja</option>
<option value="ennakhil_route_ain_semene">Ennakhil Route Ain Semene</option>
<option value="essalam">Essalam</option>
<option value="_et_tazi"> et tazi</option>
<option value="fes_jadid">Fes Jadid</option>
<option value="gzira">Gzira</option>
<option value="hay_al_azhar">Hay Al Azhar</option>
<option value="hay_anass_i">Hay Anass I</option>
<option value="hay_anass_ii_iii_iv_&_v">Hay Anass II, III, IV & V</option>
<option value="hay_az_allah">Hay Az Allah</option>
<option value="hay_badr">Hay Badr</option>
<option value="hay_ben_lkheyat">Hay Ben Lkheyat</option>
<option value="hay_ben_selimane">Hay Ben Selimane</option>
<option value="hay_bennis">Hay Bennis</option>
<option value="hay_bourmmana_(prince_heritier)">Hay Bourmmana (Prince Héritier)</option>
<option value="hay_daiaa">Hay Daiaa</option>
<option value="hay_dayaa_i_et_ii">Hay Dayaa I et II</option>
<option value="hay_el_amal">Hay El Amal</option>
<option value="hay_el_amal_champs_de_course">Hay El Amal Champs De Course</option>
<option value="hay_el_jadid">Hay El Jadid</option>
<option value="hay_el_jdid_dokkarate">Hay El Jdid Dokkarate</option>
<option value="hay_el_messefer">Hay El Messefer</option>
<option value="hay_el_morabitine">Hay El Morabitine</option>
<option value="hay_el_mouadafine">Hay El Mouadafine</option>
<option value="hay_el_ouahda">Hay El Ouahda</option>
<option value="hay_el_oufae_i_ii_&_iii">Hay El Oufae I, II & III</option>
<option value="hay_el_qods_ben_souda">Hay El Qods Ben Souda</option>
<option value="hay_ennakhil">Hay Ennakhil</option>
<option value="hay_ennassim">Hay Ennassim</option>
<option value="hay_essalam">Hay Essalam</option>
<option value="hay_grillo">Hay Grillo</option>
<option value="hay_hassani_ben_debbab">Hay Hassani Ben Debbab</option>
<option value="hay_hassani_errac">Hay Hassani Errac</option>
<option value="hay_hassani_i_et_ii">Hay Hassani I et II</option>
<option value="hay_jdid_ben_souda">Hay Jdid Ben Souda</option>
<option value="hay_lalla_soukaina">Hay Lalla Soukaina</option>
<option value="hay_lemssellah">Hay Lemssellah</option>
<option value="hay_lmohamadi">Hay Lmohamadi</option>
<option value="hay_mabrouka">Hay Mabrouka</option>
<option value="hay_mimousa">Hay Mimousa</option>
<option value="hay_noure">Hay Noure</option>
<option value="hay_qods_(allal_ben_abdellah)">Hay Qods (Allal Ben Abdellah)</option>
<option value="hay_raha">Hay Raha</option>
<option value="hay_read">Hay Read</option>
<option value="hay_riyad">Hay Riyad</option>
<option value="hay_rorate">Hay Rorate</option>
<option value="hay_saida">Hay Saida</option>
<option value="hay_sid_el_hadi">Hay Sid El Hadi</option>
<option value="hay_taqadoum">Hay Taqadoum</option>
<option value="hay_teghat">Hay Teghat</option>
<option value="hay_zaza">Hay Zaza</option>
<option value="iliass_bnou_maouaouiya">Iliass Bnou Maouaouiya</option>
<option value="jenane_lahrichi">Jenane Lahrichi</option>
<option value="jnanate">Jnanate</option>
<option value="jnane_lahrichi_ain_noukbi">Jnane Lahrichi Ain Noukbi</option>
<option value="jnane_lahrichi_ben_debbab">Jnane Lahrichi Ben Debbab</option>
<option value="jnane_tbib">Jnane Tbib</option>
<option value="joutea_haffa_my_driss">Joutea Haffa My Driss</option>
<option value="kariane_el_hajoui">Kariane El Hajoui</option>
<option value="karim_el_amrani">Karim El Amrani</option>
<option value="kasbat_chems_bab_riyafa">Kasbat Chems Bab Riyafa</option>
<option value="kasbat_nouar">Kasbat Nouar</option>
<option value="labita">Labita</option>
<option value="labitat_dhar_khmiss">Labitat Dhar Khmiss</option>
<option value="lhadiqua">Lhadiqua</option>
<option value="lot_al_mamounia">Lot Al Mamounia</option>
<option value="lot_daoula">Lot Daoula</option>
<option value="lot_hajwi">Lot Hajwi</option>
<option value="lot_jabal">Lot Jabal</option>
<option value="lot_luci">Lot Luci</option>
<option value="lot_mabrouka">Lot Mabrouka</option>
<option value="lot_moulay_driss">Lot Moulay Driss</option>
<option value="lot_najah">Lot Najah</option>
<option value="lot_zitoune">Lot Zitoune</option>
<option value="louizate">Louizate</option>
<option value="miko">Miko</option>
<option value="mojamaa_sakani_tajmouati">Mojamaa Sakani Tajmouati</option>
<option value="mont_fleuri_i_&_ii">Mont-Fleuri I & II</option>
<option value="moulay_abdellah">Moulay Abdellah</option>
<option value="moulay_el_kamal">Moulay El Kamal</option>
<option value="moulay_hfid">Moulay Hfid</option>
<option value="msala">Msala</option>
<option value="narjis">Narjis</option>
<option value="nouveau_secteur_ain_kadous">Nouveau Secteur Ain Kadous</option>
<option value="ouali_al_aahd">Ouali Al Aahd</option>
<option value="oued_fes">Oued Fes</option>
<option value="place_al_atlas_(allal_el_fassi)">Place Al Atlas (Allal El Fassi)</option>
<option value="quartier_industrielain_noukbi">Quartier IndustrielAin Noukbi</option>
<option value="quartier_industriel_ben_souda">Quartier Industriel Ben Souda</option>
<option value="quartier_industrielsidi_brahim">Quartier IndustrielSidi Brahim</option>
<option value="qods_errac">Qods-Errac</option>
<option value="quartier_industriel_dokkarate">Quartier Industriel Dokkarate</option>
<option value="raja">Raja</option>
<option value="ras_jnane">Ras Jnane</option>
<option value="rcif">Rcif</option>
<option value="res_salam_route_d_imouzzer">Res Salam Route D'imouzzer</option>
<option value="residence_omnia">Résidence Omnia</option>
<option value="route_ain_chekaf">Route Ain Chekaf</option>
<option value="route_ain_chkef_cote_droit">Route Ain Chkef Coté Droit</option>
<option value="route_ain_chkef_cote_gauche">Route Ain Chkef Coté Gauche</option>
<option value="route_ain_smen">Route Ain Smen</option>
<option value="route_de_sefrou">Route De Sefrou</option>
<option value="route_de_sefrou_cote_droit">Route De Sefrou Coté Droit</option>
<option value="route_d_imouzzer">Route D'imouzzer</option>
<option value="rue_abdelaziz_boutaleb">Rue Abdelaziz Boutaleb</option>
<option value="rue_al_hociema">Rue Al Hociema</option>
<option value="rue_zerktouni_(ex_rue_de_cunee)">Rue Zerktouni (Ex Rue De Cunée)</option>
<option value="saada">Saada</option>
<option value="sagha">Sagha</option>
<option value="sahrij_gnaoua">Sahrij Gnaoua</option>
<option value="sehb_el_ouard">Sehb El Ouard</option>
<option value="sehraoua">Sehraoua</option>
<option value="sekka">Sekka</option>
<option value="sidi_ali_boughaleb">Sidi Ali Boughaleb</option>
<option value="sidi_amir">Sidi Amir</option>
<option value="sidi_boujida">Sidi Boujida</option>
<option value="sidi_brahim">Sidi Brahim</option>
<option value="sidi_el_hadi">Sidi El Hadi</option>
<option value="tajziat_borj">Tajziat Borj</option>
<option value="tajziat_najah">Tajziat Najah</option>
<option value="talaa">Talaa</option>
<option value="tareq_i_et_ii">Tareq I et II</option>
<option value="teghate">Teghate</option>
<option value="trois_sources">Trois Sources</option>
<option value="wislane">Wislane</option>
<option value="yasmine">Yasmine</option>
<option value="zanjafour">Zanjafour</option>
<option value="ziat">Ziat</option>
<option value="zouagha">Zouagha</option>
<option value="zouagha_al_oulia">Zouagha Al Oulia</option>
<option value="zouagha_haut">Zouagha Haut</option>