<option value="aghroude_bensergao">Aghroude Bensergao</option>
<option value="ait_el_qadi">Ait El Qadi</option>
<option value="ait_ighiousse">Ait Ighiousse</option>
<option value="ait_kiwane">Ait Kiwane</option>
<option value="al_jihadia_al_filahia">Al Jihadia Al Filahia</option>
<option value="al_ouidadiate">Al Ouidadiate</option>
<option value="al_wifaq_i_et_ii">Al Wifaq I et II</option>
<option value="assaisse">Assaisse</option>
<option value="assaka">Assaka</option>
<option value="assergale">Assergale</option>
<option value="azaytoune">Azaytoune</option>
<option value="bensergao">Bensergao</option>
<option value="bicha">Bicha</option>
<option value="bir_anzarane">Bir Anzarane</option>
<option value="boutassra">Boutassra</option>
<option value="cite_des_oiseaux_les_chal_et_s">Cite Des Oiseaux-Les Chal et s</option>
<option value="cite_marins">Cite Marins</option>
<option value="dcheira_jihadiya">Dcheira Jihadiya</option>
<option value="derb_ait_elarbi">Derb Ait Elarbi</option>
<option value="derb_ait_oubih">Derb Ait Oubih</option>
<option value="derb_bouachra">Derb Bouachra</option>
<option value="derb_hfid">Derb Hfid</option>
<option value="derb_lalla_taazza">Derb Lalla Taazza</option>
<option value="derb_tazmayt">Derb Tazmayt</option>
<option value="diour_safrine">Diour Safrine</option>
<option value="douar_ait_mhand">Douar Ait Mhand</option>
<option value="douar_al_arab">Douar Al Arab</option>
<option value="douar_al_banane">Douar Al Banane</option>
<option value="douar_al_fouqani">Douar Al Fouqani</option>
<option value="douar_al_ousstani">Douar Al Ousstani</option>
<option value="douar_amzil">Douar Amzil</option>
<option value="douar_bouhssine">Douar Bouhssine</option>
<option value="douar_jdid">Douar Jdid</option>
<option value="douar_lmaalem_ali">Douar Lmaalem Ali</option>
<option value="douar_sidi_fares">Douar Sidi Fares</option>
<option value="el_hajeb_al_fokani">El Hajeb Al Fokani</option>
<option value="el_hajeb_atahtani">El Hajeb Atahtani</option>
<option value="el_mers">El Mers</option>
<option value="fadesa_tafoukte">Fadesa Tafoukte</option>
<option value="hammam_tayeb">Hammam Tayeb</option>
<option value="hay_ait_daoud">Hay Ait Daoud</option>
<option value="hay_ait_oussiyaghe">Hay Ait Oussiyaghe</option>
<option value="hay_ait_taleb">Hay Ait Taleb</option>
<option value="hay_al_farah">Hay Al Farah</option>
<option value="hay_al_moustachfa">Hay Al Moustachfa</option>
<option value="hay_amougay">Hay Amougay</option>
<option value="hay_annahda">Hay Annahda</option>
<option value="hay_anoude">Hay Anoude</option>
<option value="hay_bounaamane">Hay Bounaamane</option>
<option value="hay_bounailate">Hay Bounailate</option>
<option value="hay_cafe_el_haj">Hay Cafe El Haj</option>
<option value="hay_el_hassani_taghzoute">Hay El Hassani Taghzoute</option>
<option value="hay_ennour">Hay Ennour</option>
<option value="hay_igromaai">Hay Igromaai</option>
<option value="hay_iguiferden">Hay Iguiferden</option>
<option value="hay_iguiwaki">Hay Iguiwaki</option>
<option value="hay_imich">Hay Imich</option>
<option value="hay_irehalen">Hay Irehalen</option>
<option value="hay_jorf">Hay Jorf</option>
<option value="hay_oualhouri">Hay Oualhouri</option>
<option value="hay_pam">Hay Pam</option>
<option value="hay_rmel">Hay Rmel</option>
<option value="hay_rouchdi">Hay Rouchdi</option>
<option value="hay_saada_pergola">Hay Saada Pergola</option>
<option value="hay_slaoui">Hay Slaoui</option>
<option value="hay_tabarine">Hay Tabarine</option>
<option value="hay_tagante_tarraste">Hay Tagante Tarraste</option>
<option value="hay_takerkourte">Hay Takerkourte</option>
<option value="hay_tarraste">Hay Tarraste</option>
<option value="hay_tigmi_oufella">Hay Tigmi Oufella</option>
<option value="hay_zitoune">Hay Zitoune</option>
<option value="hy_moulay_rachid">Hy Moulay Rachid</option>
<option value="inzegane_centre">Inzegane Centre</option>
<option value="j_et_sakane">J et Sakane</option>
<option value="km_8_av_des_far">Km 8 Av Des Far</option>
<option value="kokay">Kokay</option>
<option value="laghyaten">Laghyaten</option>
<option value="lotissement_adib">Lotissement Adib</option>
<option value="lotissement_adwaa_anouar_ittifaq">Lotissement Adwaa Anouar Ittifaq</option>
<option value="lotissement_ait_el_qadi">Lotissement Ait El Qadi</option>
<option value="lotissement_al_faiz">Lotissement Al Faiz</option>
<option value="lotissement_beni_iznassen">Lotissement Beni Iznassen</option>
<option value="lotissement_dalila">Lotissement Dalila</option>
<option value="lotissement_dgss">Lotissement Dgss</option>
<option value="lotissement_el_arsa">Lotissement El Arsa</option>
<option value="lotissement_nakhla">Lotissement Nakhla</option>
<option value="lotissement_zaitoune">Lotissement Zaitoune</option>
<option value="lotisssment_militaire">Lotisssment Militaire</option>
<option value="marche_gros">Marche Gros</option>
<option value="mesdoura">Mesdoura</option>
<option value="naourat_ait_idder">Naourat Ait Idder</option>
<option value="naourat_sbai">Naourat Sbai</option>
<option value="programme_ibn_khaldoun">Programme Ibn Khaldoun</option>
<option value="sidi_abdeljalil">Sidi Abdeljalil</option>
<option value="sidi_el_wali">Sidi El Wali</option>
<option value="souk_tl_et_e">Souk Tl et e</option>
<option value="tikiouine">Tikiouine</option>
<option value="tilila">Tilila</option>
<option value="zone_industriele_tassila_1_2">Zone Industriele Tassila 1 - 2</option>
<option value="zone_industrielle_tassila_3">Zone Industrielle Tassila 3</option>