<option value="al_hay_al_aaskari">Al Hay Al Aaskari</option>
<option value="centre_ville">Centre Ville</option>
<option value="el_mellah">El Mellah</option>
<option value="hay_al_aamala">Hay Al Aamala</option>
<option value="hay_al_baladiya">Hay Al Baladiya</option>
<option value="hay_al_minaa">Hay Al Minaa</option>
<option value="le_village">Le Village</option>
<option value="afca">Afca</option>
<option value="avenue_riada">Avenue Riada</option>
<option value="chaabi">Chaabi</option>
<option value="chohadaa">Chohadaa</option>
<option value="diour_el_baladia">Diour El Baladia</option>
<option value="diour_el_makhzen">Diour El Makhzen</option>
<option value="el_inara">El Inara</option>
<option value="el_khabazate">El Khabazate</option>
<option value="hay_al_basatine">Hay Al Basatine</option>
<option value="la_cygogne">La Cygogne</option>
<option value="quartier_industriel">Quartier Industriel</option>
<option value="mimoza">Mimoza</option>
<option value="ville_haute">Ville Haute</option>
<option value="el_fath">El Fath</option>
<option value="hay_el_amal">Hay El Amal</option>
<option value="hay_el_wahda">Hay El Wahda</option>
<option value="hay_essalam">Hay Essalam</option>
<option value="hay_lalla_meryem">Hay Lalla Meryem</option>
<option value="hay_nasma">Hay Nasma</option>
<option value="hay_nasr">Hay Nasr</option>
<option value="hay_ourida">Hay Ourida</option>
<option value="hay_rabia">Hay Rabia</option>
<option value="hay_rajaa">Hay Rajaa</option>
<option value="nahda">Nahda</option>
<option value="diour_10000">Diour 10000</option>
<option value="hay_el_jadid">Hay El Jadid</option>
<option value="les_groupes">Les Groupes</option>
<option value="pam_1">Pam 1</option>
<option value="pam_2">Pam 2</option>
<option value="al_hay_el_idari">Al Hay El Idari</option>
<option value="el_irchade">El Irchade</option>
<option value="hay_al_wafaa">Hay Al Wafaa</option>
<option value="maamora">Maamora</option>
<option value="ain_sbaa">Ain Sbaa</option>
<option value="douarassam">DouarAssam</option>
<option value="douar_mkhalif_ain_sebaa">Douar Mkhalif Ain Sebaa</option>
<option value="douar_nkhakhsa">Douar Nkhakhsa</option>
<option value="douar_oulad_arfa">Douar Oulad Arfa</option>
<option value="douar_oulad_moussa">Douar Oulad Moussa</option>
<option value="douar_salah_rachid">Douar Salah Rachid</option>
<option value="hay_el_fouarat">Hay El Fouarat</option>
<option value="hay_rahma">Hay Rahma</option>
<option value="hay_safaa">Hay Safaa</option>
<option value="al_ismailia">Al Ismailia</option>
<option value="arsat_herbouze">Arsat Herbouze</option>
<option value="azharoune">Azharoune</option>
<option value="cite_des_urgences">Cite Des Urgences</option>
<option value="el_haddada">El Haddada</option>
<option value="el_haouzia">El Haouzia</option>
<option value="hay_salam">Hay Salam</option>
<option value="korcica">Korcica</option>
<option value="litissementsalama">LitissementSalama</option>
<option value="lotissement_al_filaha">Lotissement Al Filaha</option>
<option value="sayad">Sayad</option>
<option value="sayad_ii">Sayad II</option>
<option value="taibia">Taibia</option>
<option value="valfleuri">Valfleuri</option>
<option value="oulad_oujih">Oulad Oujih</option>
<option value="bir_rami_est">Bir Rami Est</option>
<option value="bir_rami_ouest">Bir Rami Ouest</option>
<option value="douar_el_hancha">Douar El Hancha</option>
<option value="douar_oulad_mbarek">Douar Oulad Mbarek</option>
<option value="hay_el_menzeh">Hay El Menzeh</option>
<option value="maghrib_arabi">Maghrib Arabi</option>
<option value="quartier_industriel_bir_rami">Quartier Industriel Bir Rami</option>