<option value="bd.abou_tammam_1_et_2">Bd.Abou Tammam 1 et 2</option>
<option value="bd.oued_makhazine">Bd.Oued Makhazine</option>
<option value="bd._allal_ben_abdellah_(côte_est)">Bd. Allal Ben Abdellah (Côte Est)</option>
<option value="bd._allal_ben_abdellah_(côte_ouest)">Bd. Allal Ben Abdellah (Côte Ouest)</option>
<option value="bd._chouaib_doukkali">Bd. Chouaib Doukkali</option>
<option value="bd._hassan_1er">Bd. Hassan 1Er</option>
<option value="bd._ibn_sina">Bd. Ibn Sina</option>
<option value="bd._kadiayad">Bd. KadiAyad</option>
<option value="bd._mohamed_v_(côte_est)">Bd. Mohamed V (Côté Est)</option>
<option value="bd._mohamed_v_(côte_ouest)">Bd. Mohamed V (Côté Ouest)</option>
<option value="bd._mohamed_v_(côte_sud)">Bd. Mohamed V (Côté Sud)</option>
<option value="bd._mohamed_zerktouni">Bd. Mohamed Zerktouni</option>
<option value="cgi">Cgi</option>
<option value="cite_anciens_combattants">Cite Anciens Combattants</option>
<option value="diour_chouhada">Diour Chouhada</option>
<option value="hay_essalam">Hay Essalam</option>
<option value="hay_idari">Hay Idari</option>
<option value="hay_imane">Hay Imane</option>
<option value="hay_izihar">Hay Izihar</option>
<option value="hay_k_et_tania">Hay K et tania</option>
<option value="hay_maamoura">Hay Maamoura</option>
<option value="hay_nahda">Hay Nahda</option>
<option value="hay_najah">Hay Najah</option>
<option value="hay_nasr">Hay Nasr</option>
<option value="hay_saada">Hay Saada</option>
<option value="hay_saada2">Hay Saada2</option>
<option value="hay_wahda">Hay Wahda</option>
<option value="hay_zahra_1">Hay Zahra 1</option>
<option value="hay_zahra_2_et_3">Hay Zahra 2 et 3</option>
<option value="karama1_et_2">Karama1 et 2</option>
<option value="lot_al_wafa">Lot Al Wafa</option>
<option value="lot_al_yasmine_1">Lot Al Yasmine 1</option>
<option value="lot_al_yasmine_2">Lot Al Yasmine 2</option>
<option value="lot_almouna">Lot Almouna</option>
<option value="lot_archane">Lot Archane</option>
<option value="lot_bassatine">Lot Bassatine</option>
<option value="lot_benkirane">Lot Benkirane</option>
<option value="lot_boubia">Lot Boubia</option>
<option value="lot_hakamate">Lot Hakamate</option>
<option value="lot_ittihad">Lot Ittihad</option>
<option value="lot_st_marguar_et_te">Lot St Marguar et te</option>
<option value="lot_tadart">Lot Tadart</option>
<option value="lot_warda">Lot Warda</option>
<option value="lot_wouroud">Lot Wouroud</option>
<option value="quartierzimermane">QuartierZimermane</option>
<option value="rue_de_la_genarmerie">Rue De La Genarmerie</option>
<option value="rue_de_rabat">Rue De Rabat</option>
<option value="rue_e_la_poste">Rue E La Poste</option>
<option value="rue_mbarek_bekkay">Rue Mbarek Bekkay</option>
<option value="yasmine_3">Yasmine 3</option>
<option value="yasmine_4">Yasmine 4</option>
<option value="zone_villas">Zone Villas</option>