<option value="_el_hassan"> El Hassan</option>
<option value="abdellaoui">Abdellaoui</option>
<option value="achbarou">Achbarou</option>
<option value="administratif">Administratif</option>
<option value="ahattab">Ahattab</option>
<option value="ait_haddou_n_hlima">Ait Haddou N'hlima</option>
<option value="al_azhar">Al Azhar</option>
<option value="al_masjid_hassan_ii">Al Masjid Hassan II</option>
<option value="al_mouhtadoune">Al Mouhtadoune</option>
<option value="amal">Amal</option>
<option value="amalou_ighriben">Amalou Ighriben</option>
<option value="andalous">Andalous</option>
<option value="assaka">Assaka</option>
<option value="atlas">Atlas</option>
<option value="attajdid">Attajdid</option>
<option value="azlou">Azlou</option>
<option value="azzahra">Azzahra</option>
<option value="bouazzou">Bouazzou</option>
<option value="boudraa">Boudraa</option>
<option value="boufoulloussene">Boufoulloussene</option>
<option value="boulahya">Boulahya</option>
<option value="bouymahaguenne">Bouymahaguenne</option>
<option value="centre_ville">Centre Ville</option>
<option value="el_arz">El Arz</option>
<option value="el_baraka">El Baraka</option>
<option value="el_fija">El Fija</option>
<option value="el_massira">El Massira</option>
<option value="equipement">Equipement</option>
<option value="errachidia">Errachidia</option>
<option value="essalam">Essalam</option>
<option value="faiza">Faiza</option>
<option value="far">Far</option>
<option value="farra">Farra</option>
<option value="fath_miaammi">Fath Miaammi</option>
<option value="fillahi">Fillahi</option>
<option value="hamria">Hamria</option>
<option value="hanane">Hanane</option>
<option value="hay_el_hassane">Hay El Hassane</option>
<option value="ikhamene">Ikhamene</option>
<option value="industriel">Industriel</option>
<option value="ingenieurs">Ingenieurs</option>
<option value="ismailia">Ismailia</option>
<option value="jamila">Jamila</option>
<option value="kaid_driss">Kaid Driss</option>
<option value="karima">Karima</option>
<option value="la_course">La Course</option>
<option value="la_seirie">La Seirie</option>
<option value="lailla">Lailla</option>
<option value="lalla_zineb">Lalla Zineb</option>
<option value="larmoud">Larmoud</option>
<option value="mabrouka_ouskar">Mabrouka Ouskar</option>
<option value="m_daghri">M'daghri</option>
<option value="m_et_chifssane">M' et chifssane</option>
<option value="m_ghari">M'ghari</option>
<option value="mouha_ou_bouazza">Mouha Ou Bouazza</option>
<option value="m_ssalah">M'ssalah</option>
<option value="nacim">Nacim</option>
<option value="najah">Najah</option>
<option value="najd">Najd</option>
<option value="narjis">Narjis</option>
<option value="nazaha">Nazaha</option>
<option value="oued_eddahab">Oued Eddahab</option>
<option value="oum_errabiaa">Oum Errabiaa</option>
<option value="oumnia">Oumnia</option>
<option value="oushak">Oushak</option>
<option value="ouzzine">Ouzzine</option>
<option value="rahma">Rahma</option>
<option value="saada">Saada</option>
<option value="safssaf">Safssaf</option>
<option value="sidi_bouknadel">Sidi Bouknadel</option>
<option value="sidi_boutzouguarht">Sidi Boutzouguarht</option>
<option value="tamoumente">Tamoumente</option>
<option value="tiallaline">Tiallaline</option>
<option value="tichout_ben_akka">Tichout Ben Akka</option>
<option value="younes">Younes</option>
<option value="zitoune">Zitoune</option>