<option value="amicale_zellaga">Amicale Zellaga</option>
<option value="ancenne_medina">Ancenne Medina</option>
<option value="ancien_souk">Ancien Souk</option>
<option value="ancienne_medina_sechage">Ancienne Medina Sechage</option>
<option value="atelieroncf">AtelierOncf</option>
<option value="avenuelaayoune">AvenueLaayoune</option>
<option value="avenuemokhtar_essoussi">AvenueMokhtar Essoussi</option>
<option value="avenue_de_la_residance">Avenue De La Résidance</option>
<option value="avenue_des_alaouites">Avenue Des Alaouites</option>
<option value="baina">Baina</option>
<option value="batiment_sejjali">Batiment Sejjali</option>
<option value="bd_11_janvier">Bd 11 Janvier</option>
<option value="bd_16_novembre">Bd 16 Novembre</option>
<option value="bd_abderrahim_bouaabid">Bd Abderrahim Bouaabid</option>
<option value="bd_ahmed_el_hiba">Bd Ahmed El Hiba</option>
<option value="bd_allal_al_fassi">Bd Allal Al Fassi</option>
<option value="bd_caid_omari">Bd Caid Omari</option>
<option value="bd_cheikh_ahmed_el_hiba">Bd Cheikh Ahmed El Hiba</option>
<option value="bd_el_mokawama">Bd El Mokawama</option>
<option value="bd_haj_maati_ben_cheikh">Bd Haj Maati Ben Cheikh</option>
<option value="bd_mohamed_sidki">Bd Mohamed Sidki</option>
<option value="bd_mohamed_v">Bd Mohamed V</option>
<option value="bd_moudoune_arabia">Bd Moudoune Arabia</option>
<option value="bd_zellaka_156a_170">Bd Zellaka 156A 170</option>
<option value="bd_zellaqua">Bd Zellaqua</option>
<option value="bdbrahim_roudani">Bdbrahim Roudani</option>
<option value="bdel_mokawama">Bdel Mokawama</option>
<option value="bdpalestine">Bdpalestine</option>
<option value="bdzellaqua">Bdzellaqua</option>
<option value="bloc_c.g.f_n.l.o.n.l.m.kh.f.u.a.s">Bloc C.G.F N.L.O.N.L.M.Kh.F.U.A.S</option>
<option value="bloc_jamila">Bloc Jamila</option>
<option value="bloc_m.j.d.c.b">Bloc M.J.D.C.B</option>
<option value="centre_ville">Centre Ville</option>
<option value="cerealier">Cerealier</option>
<option value="chantier_marocaine">Chantier Marocaine</option>
<option value="cite_al_masjid">Cite Al Masjid</option>
<option value="cite_de_police">Cite De Police</option>
<option value="cite_hopital_ocp">Cite Hopital Ocp</option>
<option value="cite_jamila">Cite Jamila</option>
<option value="cite_riad">Cite Riad</option>
<option value="club_boules">Club Boules</option>
<option value="club_des_ingenieur_nouvelle_construction">Club Des Ingenieur Nouvelle Construction</option>
<option value="club_ock">Club Ock</option>
<option value="college_ben_khaldoune">College Ben Khaldoune</option>
<option value="coopessalam">CoopEssalam</option>
<option value="coopmoustakbal">CoopMoustakbal</option>
<option value="coop_des_fonctionnaires">Coop Des Fonctionnaires</option>
<option value="cooperative_al_amal">Cooperative Al Amal</option>
<option value="cooperative_el_ouifak">Cooperative El Ouifak</option>
<option value="cooperative_el_qods">Cooperative El Qods</option>
<option value="cooperative_saada">Cooperative Saada</option>
<option value="derb_bouaazza_ben_ali">Derb Bouaazza Ben Ali</option>
<option value="derb_haj_hirech">Derb Haj Hirech</option>
<option value="derb_od_haj_el_mokhtar">Derb Od Haj El Mokhtar</option>
<option value="derb_old_aroui">Derb Old Aroui</option>
<option value="derb_oled_si_bouaabid">Derb Oled Si Bouaabid</option>
<option value="derb_si_bouchaib">Derb Si Bouchaib</option>
<option value="des_palmiers">Des Palmiers</option>
<option value="diour_chouhada">Diour Chouhada</option>
<option value="douar_allal">Douar Allal</option>
<option value="douar_ben_barraque">Douar Ben Barraque</option>
<option value="douar_ben_jelloune">Douar Ben Jelloune</option>
<option value="douar_lemterif">Douar Lemterif</option>
<option value="douar_mokhaznia">Douar Mokhaznia</option>
<option value="ecole_khawarizmi">Ecole Khawarizmi</option>
<option value="eue_de_casablanca">Eue De Casablanca</option>
<option value="for_et_dominale">For et Dominale</option>
<option value="garconniere_ocp">Garconniere Ocp</option>
<option value="gendarmerie">Gendarmerie</option>
<option value="hay_mabchour">Hay Mabchour</option>
<option value="hay_al_amal">Hay Al Amal</option>
<option value="hay_al_massira">Hay Al Massira</option>
<option value="hay_dakhla">Hay Dakhla</option>
<option value="hay_el_faoum">Hay El Faoum</option>
<option value="hay_el_farah_rue_el_azhar">Hay El Farah Rue El Azhar</option>
<option value="hay_el_faraj">Hay El Faraj</option>
<option value="hay_el_mostakbel">Hay El Mostakbel</option>
<option value="hay_el_qods_i">Hay El Qods I</option>
<option value="hay_essalamii">Hay EssalamII</option>
<option value="hay_essalam_al_massira">Hay Essalam Al Massira</option>
<option value="hay_hassania">Hay Hassania</option>
<option value="hay_iraq">Hay Iraq</option>
<option value="hay_karam">Hay Karam</option>
<option value="hay_l_hopîtal_provincial">Hay L Hopîtal Provincial</option>
<option value="hay_nahda">Hay Nahda</option>
<option value="hay_rachadi_ii_iii">Hay RachadI-II -III</option>
<option value="hay_salam_ocp">Hay Salam Ocp</option>
<option value="hay_yassmina_ii">Hay Yassmina II</option>
<option value="hotel_de_paris">Hotel De Paris</option>
<option value="immam_chadli">Immam Chadli</option>
<option value="immam_sayouti">Immam Sayouti</option>
<option value="immeuble_adour">Immeuble Adour</option>
<option value="immeuble_anouar">Immeuble Anouar</option>
<option value="immeuble_far">Immeuble Far</option>
<option value="immeuble_oncfar_ay">Immeuble OncfAr -Ay</option>
<option value="immeuble_yasmina">Immeuble Yasmina</option>
<option value="immmeuble_sophal">Immmeuble Sophal</option>
<option value="impots_urbain">Impots Urbain</option>
<option value="khouadriajdad">KhouadriaJdad</option>
<option value="khwadria_kdam">Khwadria Kdam</option>
<option value="kissariatmoulay_messaoud">KissariatMoulay Messaoud</option>
<option value="kissariat_cherradi">Kissariat Cherradi</option>
<option value="kissariat_dakhla_od_eddahab">Kissariat Dakhla Od Eddahab</option>
<option value="kissariat_tanger">Kissariat Tanger</option>
<option value="lot_al_allalia">Lot Al Allalia</option>
<option value="lot_al_fath">Lot Al Fath</option>
<option value="lot_al_hana">Lot Al Hana</option>
<option value="lot_al_maghrib_al_arabi">Lot Al Maghrib Al Arabi</option>
<option value="lot_al_maidane">Lot Al Maidane</option>
<option value="lot_al_mokawama">Lot Al Mokawama</option>
<option value="lot_al_mostaqbal">Lot Al Mostaqbal</option>
<option value="lot_ard_al_khair">Lot Ard Al Khair</option>
<option value="lot_el_ali">Lot El Ali</option>
<option value="lot_el_haoud">Lot El Haoud</option>
<option value="lot_el_kird">Lot El Kird</option>
<option value="lot_ezzahra">Lot Ezzahra</option>
<option value="lot_haizoune">Lot Haizoune</option>
<option value="lot_ibn_khaldoune">Lot Ibn Khaldoune</option>
<option value="lot_iqbal">Lot Iqbal</option>
<option value="lot_lahssinia">Lot Lahssinia</option>
<option value="lot_louiza">Lot Louiza</option>
<option value="lot_nakhil">Lot Nakhil</option>
<option value="lot_nasr">Lot Nasr</option>
<option value="lot_nour">Lot Nour</option>
<option value="lot_oum_lkora">Lot Oum Lkora</option>
<option value="lot_qods_ii">Lot Qods II</option>
<option value="lot_qods_iip2">Lot Qods IIP2</option>
<option value="lot_raqi">Lot Raqi</option>
<option value="lot_saada">Lot Saada</option>
<option value="lot_salama">Lot Salama</option>
<option value="lot_skhour">Lot Skhour</option>
<option value="lot_souk">Lot Souk</option>
<option value="lot_wifak">Lot Wifak</option>
<option value="lot_yassmina_1_2">Lot Yassmina 1-2</option>
<option value="maison_des_gendarmes">Maison Des Gendarmes</option>
<option value="marche_aux_grains">Marche Aux Grains</option>
<option value="marche_de_gros">Marche De Gros</option>
<option value="mosqueehassan_ii">MosqueeHassan II</option>
<option value="municipalite">Municipalite</option>
<option value="nahda">Nahda</option>
<option value="nouveaux_logements">Nouveaux Logements</option>
<option value="nouvelle_extention">Nouvelle Extention</option>
<option value="nouvelle_medina_de_sechage">Nouvelle Medina De Sechage</option>
<option value="ocp">Ocp</option>
<option value="oum_rabia">Oum Rabia</option>
<option value="parc_municipal">Parc Municipal</option>
<option value="pepiniere">Pepiniere</option>
<option value="perception">Perception</option>
<option value="placemouritanie">PlaceMouritanie</option>
<option value="place_de_l_independance">Place De L Independance</option>
<option value="place_de_l_istiqlal">Place De L Istiqlal</option>
<option value="place_de_la_gare">Place De La Gare</option>
<option value="place_de_la_liberte">Place De La Liberte</option>
<option value="place_des_martyrs">Place Des Martyrs</option>
<option value="place_el_qods">Place El Qods</option>
<option value="place_mojahidine">Place Mojahidine</option>
<option value="place_nations_unis_rue_tafilelt_rue_dokkala">Place Nations Unis Rue Tafilelt Rue Dokkala</option>
<option value="qods1">Qods1</option>
<option value="quartier_brique">Quartier Brique</option>
<option value="quartier_cerealier">Quartier Cerealier</option>
<option value="quartier_warak">Quartier Warak</option>
<option value="quatre_chemins">Quatre Chemins</option>
<option value="route_hayane">Route Hayane</option>
<option value="rueghazzane">RueGhazzane</option>
<option value="ruezonitinia">RueZonitinia</option>
<option value="rue_16_rue_nouakchout">Rue 16 Rue Nouakchout</option>
<option value="rue_20_aout">Rue 20 Aout</option>
<option value="rue_21_aout">Rue 21 Aout</option>
<option value="rue_7_derb_j._mokhtar">Rue 7 Derb J. Mokhtar</option>
<option value="rue_abda">Rue Abda</option>
<option value="rue_abdelkader_el_allal">Rue Abdelkader El Allal</option>
<option value="rue_abdelkader_torres">Rue Abdelkader Torres</option>
<option value="rue_abdelkrim_el_khattabi">Rue Abdelkrim El Khattabi</option>
<option value="rue_abdellah_ben_yassine">Rue Abdellah Ben Yassine</option>
<option value="rue_abderrahmane">Rue Abderrahmane</option>
<option value="rue_abou_dabie">Rue Abou Dabie</option>
<option value="rue_abou_hanifa">Rue Abou Hanifa</option>
<option value="rue_abtih">Rue Abtih</option>
<option value="rue_adan">Rue Adan</option>
<option value="rue_aghmate">Rue Aghmate</option>
<option value="rue_ahmed_rguibi">Rue Ahmed Rguibi</option>
<option value="rue_aicha_oum_mouminine">Rue Aicha Oum Mouminine</option>
<option value="rue_ain_kaicher">Rue Ain Kaicher</option>
<option value="rue_akaba">Rue Akaba</option>
<option value="rue_akjouja">Rue Akjouja</option>
<option value="rue_al_aroussiyine">Rue Al Aroussiyine</option>
<option value="rue_alaouites">Rue Alaouites</option>
<option value="rue_alfarede_beauge">Rue Alfarede Beauge</option>
<option value="rue_allal_ben_abdellah">Rue Allal Ben Abdellah</option>
<option value="rue_amal">Rue Amal</option>
<option value="rue_amghala">Rue Amghala</option>
<option value="rue_amman">Rue Amman</option>
<option value="rue_amria">Rue Amria</option>
<option value="rue_andalous">Rue Andalous</option>
<option value="rue_ankara">Rue Ankara</option>
<option value="rue_anoual">Rue Anoual</option>
<option value="rue_anouam">Rue Anouam</option>
<option value="rue_aounate">Rue Aounate</option>
<option value="rue_araba">Rue Araba</option>
<option value="rue_arbaoua">Rue Arbaoua</option>
<option value="rue_argoub">Rue Argoub</option>
<option value="rue_asni_rue_maati_b_salah">Rue Asni Rue Maati B Salah</option>
<option value="rue_assa">Rue Assa</option>
<option value="rue_atlas">Rue Atlas</option>
<option value="rue_ayoub">Rue Ayoub</option>
<option value="rue_azemmour">Rue Azemmour</option>
<option value="rue_azrou">Rue Azrou</option>
<option value="rue_baalabak">Rue Baalabak</option>
<option value="rue_babil">Rue Babil</option>
<option value="rue_bagdad">Rue Bagdad</option>
<option value="rue_bahja">Rue Bahja</option>
<option value="rue_bahreine">Rue Bahreine</option>
<option value="rue_bajaja">Rue Bajaja</option>
<option value="rue_basma">Rue Basma</option>
<option value="rue_basra">Rue Basra</option>
<option value="rue_batha">Rue Batha</option>
<option value="rue_bayt_lahm">Rue Bayt Lahm</option>
<option value="rue_ben_ahmed">Rue Ben Ahmed</option>
<option value="rue_ben_ghazi">Rue Ben Ghazi</option>
<option value="rue_ben_guerrier">Rue Ben Guerrier</option>
<option value="rue_ben_khaldoun">Rue Ben Khaldoun</option>
<option value="rue_beni_amir">Rue Beni Amir</option>
<option value="rue_beni_chegdal">Rue Beni Chegdal</option>
<option value="rue_beni_hassan">Rue Beni Hassan</option>
<option value="rue_beni_khirane">Rue Beni Khirane</option>
<option value="rue_beni_marine">Rue Beni Marine</option>
<option value="rue_beni_meskine">Rue Beni Meskine</option>
<option value="rue_beni_moussa">Rue Beni Moussa</option>
<option value="rue_beni_smir">Rue Beni Smir</option>
<option value="rue_beni_yakhlef">Rue Beni Yakhlef</option>
<option value="rue_benzart">Rue Benzart</option>
<option value="rue_b_et_tah">Rue B et tah</option>
<option value="rue_beyrout">Rue Beyrout</option>
<option value="rue_bir_lahlou">Rue Bir Lahlou</option>
<option value="rue_bni_amir">Rue Bni Amir</option>
<option value="rue_boujaad">Rue Boujaad</option>
<option value="rue_boujniba">Rue Boujniba</option>
<option value="rue_boukodia">Rue Boukodia</option>
<option value="rue_boukraa">Rue Boukraa</option>
<option value="rue_boulanoir">Rue Boulanoir</option>
<option value="rue_bouregreg">Rue Bouregreg</option>
<option value="rue_brahim_roudani">Rue Brahim Roudani</option>
<option value="rue_brakssa">Rue Brakssa</option>
<option value="rue_brija">Rue Brija</option>
<option value="rue_cadi_ayad">Rue Cadi Ayad</option>
<option value="rue_caid_ahmed_cherradi">Rue Caid Ahmed Cherradi</option>
<option value="rue_caid_driss_cherradi">Rue Caid Driss Cherradi</option>
<option value="rue_cair">Rue Cair</option>
<option value="rue_chafaka">Rue Chafaka</option>
<option value="rue_changuit">Rue Changuit</option>
<option value="rue_charika">Rue Charika</option>
<option value="rue_chatilla">Rue Chatilla</option>
<option value="rue_cheikh_chouaib_doukkali">Rue Cheikh Chouaib Doukkali</option>
<option value="rue_chellah">Rue Chellah</option>
<option value="rue_chougrane">Rue Chougrane</option>
<option value="rue_cote_d_ivoire">Rue Cote D IVoire</option>
<option value="rue_d_agadir">Rue D Agadir</option>
<option value="rue_d_alger">Rue D Alger</option>
<option value="rue_d_ifni">Rue D Ifni</option>
<option value="rue_dakar">Rue Dakar</option>
<option value="rue_damas">Rue Damas</option>
<option value="rue_daraa_rue_el_jadida">Rue Daraa Rue El Jadida</option>
<option value="rue_day">Rue Day</option>
<option value="rue_dchira">Rue Dchira</option>
<option value="rue_de_chine">Rue De Chine</option>
<option value="rue_de_chourafa">Rue De Chourafa</option>
<option value="rue_de_la_gare">Rue De La Gare</option>
<option value="rue_de_la_girande">Rue De La Girande</option>
<option value="rue_de_marrakech">Rue De Marrakech</option>
<option value="rue_de_oujda">Rue De Oujda</option>
<option value="rue_de_rabat">Rue De Rabat</option>
<option value="rue_de_safi">Rue De Safi</option>
<option value="rue_de_tabger">Rue De Tabger</option>
<option value="rue_des_alacais">Rue Des Alacais</option>
<option value="rue_des_almohades">Rue Des Almohades</option>
<option value="rue_des_amandiers">Rue Des Amandiers</option>
<option value="rue_des_cebres">Rue Des Cebres</option>
<option value="rue_des_chenes">Rue Des Chenes</option>
<option value="rue_des_idrissides">Rue Des Idrissides</option>
<option value="rue_des_mimouza">Rue Des Mimouza</option>
<option value="rue_des_muniers">Rue Des Muniers</option>
<option value="rue_des_olives_hay_nahda">Rue Des Olives Hay Nahda</option>
<option value="rue_des_oranges">Rue Des Oranges</option>
<option value="rue_des_pins">Rue Des Pins</option>
<option value="rue_des_pompiersrue">Rue Des Pompiersrue</option>
<option value="rue_des_saules">Rue Des Saules</option>
<option value="rue_des_vigniers">Rue Des Vigniers</option>
<option value="rue_dir_yassine">Rue Dir Yassine</option>
<option value="rue_djibouti">Rue Djibouti</option>
<option value="rue_douha">Rue Douha</option>
<option value="rue_doukkala">Rue Doukkala</option>
<option value="rue_du_afoughal">Rue Du Afoughal</option>
<option value="rue_du_four">Rue Du Four</option>
<option value="rue_du_souk">Rue Du Souk</option>
<option value="rue_echorouk">Rue Echorouk</option>
<option value="rue_eddoha">Rue Eddoha</option>
<option value="rue_el_afrah">Rue El Afrah</option>
<option value="rue_el_aounate">Rue El Aounate</option>
<option value="rue_el_brouj">Rue El Brouj</option>
<option value="rue_el_gabon">Rue El Gabon</option>
<option value="rue_el_hachimia">Rue El Hachimia</option>
<option value="rue_el_hajeb">Rue El Hajeb</option>
<option value="rue_el_ikhlasse">Rue El Ikhlasse</option>
<option value="rue_el_inchirah">Rue El Inchirah</option>
<option value="rue_el_jabal">Rue El Jabal</option>
<option value="rue_el_khalil">Rue El Khalil</option>
<option value="rue_el_khzazra">Rue El Khzazra</option>
<option value="rue_el_kiraoune">Rue El Kiraoune</option>
<option value="rue_el_mahbes">Rue El Mahbes</option>
<option value="rue_el_mansouria">Rue El Mansouria</option>
<option value="rue_el_maroua">Rue El Maroua</option>
<option value="rue_el_masjid">Rue El Masjid</option>
<option value="rue_el_mehbes">Rue El Mehbes</option>
<option value="rue_el_rueffaf">Rue El Rueffaf</option>
<option value="rue_el_yamama">Rue El Yamama</option>
<option value="rue_ennasr">Rue Ennasr</option>
<option value="rue_ennassiria">Rue Ennassiria</option>
<option value="rue_errachad">Rue Errachad</option>
<option value="rue_erriche">Rue Erriche</option>
<option value="rue_escalya">Rue Escalya</option>
<option value="rue_essafa">Rue Essafa</option>
<option value="rue_essaouira">Rue Essaouira</option>
<option value="rue_essidik">Rue Essidik</option>
<option value="rue_essilm">Rue Essilm</option>
<option value="rue_essoussa">Rue Essoussa</option>
<option value="rue_farah">Rue Farah</option>
<option value="rue_fatima_oum_banine">Rue Fatima Oum Banine</option>
<option value="rue_fouarate">Rue Fouarate</option>
<option value="rue_garconniaires">Rue Garconniaires</option>
<option value="rue_gharnata">Rue Gharnata</option>
<option value="rue_ghaza">Rue Ghaza</option>
<option value="rue_ghouroub">Rue Ghouroub</option>
<option value="rue_gnadiz">Rue Gnadiz</option>
<option value="rue_guelmima">Rue Guelmima</option>
<option value="rue_guelt_et_zemmour">Rue Guelt et Zemmour</option>
<option value="rue_guidir">Rue Guidir</option>
<option value="rue_guisser">Rue Guisser</option>
<option value="rue_haifa">Rue Haifa</option>
<option value="rue_hamam">Rue Hamam</option>
<option value="rue_hamamaf_et_ouaki">Rue HamamaF et ouaki</option>
<option value="rue_hansali">Rue Hansali</option>
<option value="rue_hariri">Rue Hariri</option>
<option value="rue_hassan_1_er">Rue Hassan 1 Er</option>
<option value="rue_hassan_ii">Rue Hassan II</option>
<option value="rue_ibn_amir">Rue Ibn Amir</option>
<option value="rue_ibn_batouta">Rue Ibn Batouta</option>
<option value="rue_ibn_rochd">Rue Ibn Rochd</option>
<option value="rue_ibnou_ali_zaraa">Rue Ibnou Ali Zaraa</option>
<option value="rue_ibnou_khaldoune">Rue Ibnou Khaldoune</option>
<option value="rue_ibnou_sina">Rue Ibnou Sina</option>
<option value="rue_ibtissam">Rue Ibtissam</option>
<option value="rue_ifni">Rue Ifni</option>
<option value="rue_imam_chafii">Rue Imam Chafii</option>
<option value="rue_imam_ghazali">Rue Imam Ghazali</option>
<option value="rue_imam_malek">Rue Imam Malek</option>
<option value="rue_imam_malik">Rue Imam Malik</option>
<option value="rue_impassa_mauriere">Rue Impassa Mauriere</option>
<option value="rue_inblat">Rue Inblat</option>
<option value="rue_iraq">Rue Iraq</option>
<option value="rue_ismailia">Rue Ismailia</option>
<option value="rue_italia">Rue Italia</option>
<option value="rue_izdihou">Rue Izdihou</option>
<option value="rue_jamal_eddine_afghani">Rue Jamal Eddine Afghani</option>
<option value="rue_jbel_bani">Rue Jbel Bani</option>
<option value="rue_jbel_habri">Rue Jbel Habri</option>
<option value="rue_jbel_toubkal">Rue Jbel Toubkal</option>
<option value="rue_jebel_saghro">Rue Jebel Saghro</option>
<option value="rue_jeddah">Rue Jeddah</option>
<option value="rue_jorf_lasfer">Rue Jorf Lasfer</option>
<option value="rue_juli_et_te">Rue Juli et te</option>
<option value="rue_kalaa_sraghna">Rue Kalaa Sraghna</option>
<option value="rue_kalaat_m_gouna">Rue Kalaat M Gouna</option>
<option value="rue_kenitra">Rue Kenitra</option>
<option value="rue_kenya">Rue Kenya</option>
<option value="rue_khalid_ben_lwalid">Rue Khalid Ben Lwalid</option>
<option value="rue_khatouat">Rue Khatouat</option>
<option value="rue_khortoum">Rue Khortoum</option>
<option value="rue_khourassane">Rue Khourassane</option>
<option value="rue_kinchassa">Rue Kinchassa</option>
<option value="rue_kiraouane">Rue Kiraouane</option>
<option value="rue_koraiche">Rue Koraiche</option>
<option value="rue_kouassem">Rue Kouassem</option>
<option value="rue_koudia">Rue Koudia</option>
<option value="rue_koufa">Rue Koufa</option>
<option value="rue_kowait">Rue Kowait</option>
<option value="rue_la_ligue_arabe">Rue La Ligue Arabe</option>
<option value="rue_lakwasse">Rue Lakwasse</option>
<option value="rue_larache">Rue Larache</option>
<option value="rue_lemfassis">Rue Lemfassis</option>
<option value="rue_lemsid">Rue Lemsid</option>
<option value="rue_lot_yassmina_ii_2_eme_tranche">Rue Lot Yassmina II 2 Eme Tranche</option>
<option value="rue_loukous">Rue Loukous</option>
<option value="rue_m_hamid_ghizlan">Rue M Hamid Ghizlan</option>
<option value="rue_m_zab">Rue M Zab</option>
<option value="rue_maadna">Rue Maadna</option>
<option value="rue_maarif">Rue Maarif</option>
<option value="rue_madaoui">Rue Madaoui</option>
<option value="rue_maghrib_arabi">Rue Maghrib Arabi</option>
<option value="rue_malizia">Rue Malizia</option>
<option value="rue_mansour_dahbi">Rue Mansour Dahbi</option>
<option value="rue_masquit">Rue Masquit</option>
<option value="rue_medina">Rue Medina</option>
<option value="rue_mehdi_b_toumerte">Rue Mehdi B Toumerte</option>
<option value="rue_meknes">Rue Meknes</option>
<option value="rue_melila">Rue Melila</option>
<option value="rue_menara">Rue Menara</option>
<option value="rue_michlifen">Rue Michlifen</option>
<option value="rue_missour">Rue Missour</option>
<option value="rue_mohamed_abdou">Rue Mohamed Abdou</option>
<option value="rue_mohamed_el_ayachi">Rue Mohamed El Ayachi</option>
<option value="rue_mokhtar_essoussi">Rue Mokhtar Essoussi</option>
<option value="rue_monnastire">Rue Monnastire</option>
<option value="rue_motanabi">Rue Motanabi</option>
<option value="rue_moulayabdellah">Rue MoulayAbdellah</option>
<option value="rue_moulayhassan">Rue MoulayHassan</option>
<option value="rue_moulay_abderrahmane">Rue Moulay Abderrahmane</option>
<option value="rue_moulay_driss">Rue Moulay Driss</option>
<option value="rue_moulay_ismail">Rue Moulay Ismail</option>
<option value="rue_moulay_rachid">Rue Moulay Rachid</option>
<option value="rue_moulay_youssef">Rue Moulay Youssef</option>
<option value="rue_moyen_orient">Rue Moyen Orient</option>
<option value="rue_nabatia">Rue Nabatia</option>
<option value="rue_nables">Rue Nables</option>
<option value="rue_nablous">Rue Nablous</option>
<option value="rue_nador_rue_tiznit">Rue Nador Rue Tiznit</option>
<option value="rue_nahj_bel_houda">Rue Nahj Bel Houda</option>
<option value="rue_namaa">Rue Namaa</option>
<option value="rue_nfis">Rue Nfis</option>
<option value="rue_nousser">Rue Nousser</option>
<option value="rue_od_amrane">Rue Od Amrane</option>
<option value="rue_od_boukhadou">Rue Od Boukhadou</option>
<option value="rue_od_fennane">Rue Od Fennane</option>
<option value="rue_oiffa">Rue Oiffa</option>
<option value="rue_old_ayad">Rue Old Ayad</option>
<option value="rue_old_ayoub">Rue Old Ayoub</option>
<option value="rue_old_boughadi">Rue Old Boughadi</option>
<option value="rue_old_brahim">Rue Old Brahim</option>
<option value="rue_old_faress">Rue Old Faress</option>
<option value="rue_old_ftata">Rue Old Ftata</option>
<option value="rue_old_said">Rue Old Said</option>
<option value="rue_oled_brahim">Rue Oled Brahim</option>
<option value="rue_omar_el_khayam">Rue Omar El Khayam</option>
<option value="rue_ouarkziz">Rue Ouarkziz</option>
<option value="rue_ouarzazate">Rue Ouarzazate</option>
<option value="rue_oudaya">Rue Oudaya</option>
<option value="rue_oued_akrache">Rue Oued Akrache</option>
<option value="rue_oued_baht">Rue Oued Baht</option>
<option value="rue_oued_cherrat">Rue Oued Cherrat</option>
<option value="rue_oued_el_abid">Rue Oued El Abid</option>
<option value="rue_oued_grou">Rue Oued Grou</option>
<option value="rue_oued_ikem">Rue Oued Ikem</option>
<option value="rue_oued_kourifla">Rue Oued Kourifla</option>
<option value="rue_oued_makhazin">Rue Oued Makhazin</option>
<option value="rue_oued_molawya">Rue Oued Molawya</option>
<option value="rue_oued_naime">Rue Oued Naime</option>
<option value="rue_oued_zem">Rue Oued Zem</option>
<option value="rue_oughanda">Rue Oughanda</option>
<option value="rue_ouihrane">Rue Ouihrane</option>
<option value="rue_oulad_azzouz">Rue Oulad Azzouz</option>
<option value="rue_ouled_abdoune">Rue Ouled Abdoune</option>
<option value="rue_ouled_jaafar">Rue Ouled Jaafar</option>
<option value="rue_ouled_m_rah">Rue Ouled M Rah</option>
<option value="rue_ouloud">Rue Ouloud</option>
<option value="rue_oum_darmane">Rue Oum Darmane</option>
<option value="rue_oum_driga">Rue Oum Driga</option>
<option value="rue_oum_el_kora">Rue Oum El Kora</option>
<option value="rue_pakistan">Rue Pakistan</option>
<option value="rue_palestine">Rue Palestine</option>
<option value="rue_polonia">Rue Polonia</option>
<option value="rue_rachad">Rue Rachad</option>
<option value="rue_rachidia">Rue Rachidia</option>
<option value="rue_rafah">Rue Rafah</option>
<option value="rue_raha">Rue Raha</option>
<option value="rue_rahma">Rue Rahma</option>
<option value="rue_raja">Rue Raja</option>
<option value="rue_ram_allah">Rue Ram Allah</option>
<option value="rue_rass_el_ain">Rue Rass El Ain</option>
<option value="rue_riad">Rue Riad</option>
<option value="rue_romanie">Rue Romanie</option>
<option value="rue_sabra">Rue Sabra</option>
<option value="rue_safi">Rue Safi</option>
<option value="rue_sakia_hamra">Rue Sakia Hamra</option>
<option value="rue_sanaa">Rue Sanaa</option>
<option value="rue_sanghafoura">Rue Sanghafoura</option>
<option value="rue_sebta">Rue Sebta</option>
<option value="rue_sefrou">Rue Sefrou</option>
<option value="rue_senegale">Rue Senegale</option>
<option value="rue_s_et_tat">Rue S et tat</option>
<option value="rue_sfakaiss">Rue Sfakaiss</option>
<option value="rue_sidi_ahmed_tijani">Rue Sidi Ahmed Tijani</option>
<option value="rue_sidi_hajjaj">Rue Sidi Hajjaj</option>
<option value="rue_sidi_mohamed_ben_abdellah">Rue Sidi Mohamed Ben Abdellah</option>
<option value="rue_sidi_mohamed_derb_ouled_attouch">Rue Sidi Mohamed Derb Ouled Attouch</option>
<option value="rue_sidiel_hgazouani">Rue Sidiel Hgazouani</option>
<option value="rue_sijilmassa">Rue Sijilmassa</option>
<option value="rue_sina">Rue Sina</option>
<option value="rue_slimania">Rue Slimania</option>
<option value="rue_smaala">Rue Smaala</option>
<option value="rue_smara">Rue Smara</option>
<option value="rue_soudan">Rue Soudan</option>
<option value="rue_tachraf_et">Rue Tachraf et</option>
<option value="rue_tadla">Rue Tadla</option>
<option value="rue_tafatouh">Rue Tafatouh</option>
<option value="rue_taif">Rue Taif</option>
<option value="rue_takaddoum">Rue Takaddoum</option>
<option value="rue_tanta">Rue Tanta</option>
<option value="rue_tantan">Rue Tantan</option>
<option value="rue_tarabolous">Rue Tarabolous</option>
<option value="rue_targuiste">Rue Targuiste</option>
<option value="rue_tarik_bnou_ziad">Rue Tarik Bnou Ziad</option>
<option value="rue_taroudant">Rue Taroudant</option>
<option value="rue_tata">Rue Tata</option>
<option value="rue_taza">Rue Taza</option>
<option value="rue_tichka">Rue Tichka</option>
<option value="rue_tifariti">Rue Tifariti</option>
<option value="rue_tindouf">Rue Tindouf</option>
<option value="rue_tinghir">Rue Tinghir</option>
<option value="rue_tlemcen">Rue Tlemcen</option>
<option value="rue_walaa_mahaba">Rue Walaa Mahaba</option>
<option value="rue_wiam">Rue Wiam</option>
<option value="rue_x_lot_aggadi">Rue X Lot Aggadi</option>
<option value="rue_yacoub_mansour">Rue Yacoub Mansour</option>
<option value="rue_yarmouk">Rue Yarmouk</option>
<option value="rue_youm_al_ard">Rue Youm Al Ard</option>
<option value="rue_youssef_bnou_tachfine">Rue Youssef Bnou Tachfine</option>
<option value="rue_zag">Rue Zag</option>
<option value="rue_zagora">Rue Zagora</option>
<option value="rue_zallay">Rue Zallay</option>
<option value="rue_zambia">Rue Zambia</option>
<option value="rue_zarhoune">Rue Zarhoune</option>
<option value="rue_zemama">Rue Zemama</option>
<option value="rue_ziri_ben_attia">Rue Ziri Ben Attia</option>
<option value="rur_bagdad">Rur Bagdad</option>
<option value="s.o.b.a.m.a_(immeuble)">S.O.B.A.M.A (Immeuble)</option>
<option value="section_des_boules_oncf">Section Des Boules Oncf</option>
<option value="section_oncf">Section Oncf</option>
<option value="village_ocp">Village Ocp</option>
<option value="widadiya_al_atlas">Widadiya Al Atlas</option>
<option value="widadiya_al_wattan_al_arabi">Widadiya Al Wattan Al Arabi</option>
<option value="widadiya_assidk">Widadiya Assidk</option>
<option value="widadiya_essahel">Widadiya Essahel</option>