<option value="av_allal_ben_abdellah">Av Allal Ben Abdellah</option>
<option value="av_el_bahria">Av El Bahria</option>
<option value="bloc_a">Bloc A</option>
<option value="bloc_o">Bloc O</option>
<option value="diour_chioukh">Diour Chioukh</option>
<option value="hay_al_massira">Hay Al Massira</option>
<option value="hay_chouhada">Hay Chouhada</option>
<option value="hay_el_farah">Hay El Farah</option>
<option value="hay_el_fath">Hay El Fath</option>
<option value="hay_el_fida">Hay El Fida</option>
<option value="hay_el_hassani">Hay El Hassani</option>
<option value="hay_el_issmailia">Hay El Issmailia</option>
<option value="hay_el_kassaba">Hay El Kassaba</option>
<option value="hay_el_kodss">Hay El Kodss</option>
<option value="hay_el_matar">Hay El Matar</option>
<option value="hay_el_mohammadi">Hay El Mohammadi</option>
<option value="hay_el_quassam">Hay El Quassam</option>
<option value="hay_essaada">Hay Essaada</option>
<option value="hay_et_taaoune">Hay et taaoune</option>
<option value="hay_idari">Hay Idari</option>
<option value="hay_l_irak_120_log">Hay L' Irak 120 Log</option>
<option value="hay_maatallah">Hay Maatallah</option>
<option value="hay_my_rachid_1">Hay My Rachid 1</option>
<option value="hay_my_rachid_2">Hay My Rachid 2</option>
<option value="hay_my_rachid_3">Hay My Rachid 3</option>
<option value="hay_my_rachid_4_et_5">Hay My Rachid 4 et 5</option>
<option value="hay_sidi_mohammad">Hay Sidi Mohammad</option>
<option value="khat_ramla_1">Khat Ramla 1</option>
<option value="khat_ramla_2">Khat Ramla 2</option>
<option value="lalla_yacout">Lalla Yacout</option>
<option value="lot_244">Lot 244</option>
<option value="lot_ocp">Lot Ocp</option>
<option value="lot_raha">Lot Raha</option>
<option value="lotissement_707">Lotissement 707</option>
<option value="lotissement_al_aouda">Lotissement Al Aouda</option>
<option value="lotissement_el_amal">Lotissement El Amal</option>
<option value="lotissement_el_farah">Lotissement El Farah</option>
<option value="lotissement_el_ouahda">Lotissement El Ouahda</option>
<option value="lotissement_idriss_el_harti">Lotissement Idriss El Harti</option>
<option value="rue_10">Rue 10</option>
<option value="rue_11">Rue 11</option>
<option value="rue_12">Rue 12</option>
<option value="rue_13">Rue 13</option>
<option value="rue_15_rue_16">Rue 15 Rue 16</option>
<option value="rue_21">Rue 21</option>
<option value="rue_22">Rue 22</option>
<option value="rue_23">Rue 23</option>
<option value="rue_25">Rue 25</option>
<option value="rue_26">Rue 26</option>
<option value="rue_27">Rue 27</option>
<option value="rue_28">Rue 28</option>
<option value="rue_29">Rue 29</option>
<option value="rue_30">Rue 30</option>
<option value="rue_31">Rue 31</option>
<option value="rue_32">Rue 32</option>
<option value="rue_33">Rue 33</option>
<option value="rue_34_rue_35">Rue 34 Rue 35</option>
<option value="rue_8">Rue 8</option>
<option value="rue_abi_rakrak">Rue Abi Rakrak</option>
<option value="rue_aridal">Rue Aridal</option>
<option value="rue_daraa">Rue Daraa</option>
<option value="rue_el_khandak">Rue El Khandak</option>
<option value="rue_gunidelf">Rue Gunidelf</option>
<option value="rue_hanin">Rue Hanin</option>
<option value="rue_maarakat_d_chiera">Rue Maarakat D'chiera</option>
<option value="rue_maloiya">Rue Maloiya</option>
<option value="rue_nabt">Rue Nabt</option>
<option value="rue_ouedsabou">Rue OuedSabou</option>
<option value="rue_oued_el_makhazine">Rue Oued El Makhazine</option>
<option value="rue_oued_lakbir">Rue Oued Lakbir</option>
<option value="rue_oued_loukouss">Rue Oued Loukouss</option>
<option value="rue_oued_nafiss">Rue Oued Nafiss</option>
<option value="rue_oum_rbie">Rue Oum Rbie</option>
<option value="rue_rahal_el_meskini">Rue Rahal El Meskini</option>
<option value="rue_tafoudarte">Rue Tafoudarte</option>
<option value="lot_al_wifaq">Lot Al Wifaq</option>
<option value="sahat_badr">Sahat Badr</option>
<option value="yay_essalam">Yay Essalam</option>
<option value="laayoune_el_marsa">Laayoune El Marsa</option>