<option value="_circuit_ennakhil"> Circuit Ennakhil</option>
<option value="_quartier_berrima"> Quartier Berrima</option>
<option value="aars_et_bata">Aars et Bata</option>
<option value="lot_abdellaouia">Lot Abdellaouia</option>
<option value="lot_adrar_ain_bakkal">Lot 'Adrar Ain Bakkal</option>
<option value="routeaeroport">RouteAeroport</option>
<option value="quartier_afak">Quartier Afak</option>
<option value="agdal">Agdal</option>
<option value="agdal_bahmad">Agdal Bahmad</option>
<option value="ahl_fase">Ahl Fase</option>
<option value="ain_itti">Ain Itti</option>
<option value="quartier_ain_mazouar">Quartier Ain Mazouar</option>
<option value="lot_al_fadl">Lot Al Fadl</option>
<option value="amane">Amane</option>
<option value="amerchich">Amerchich</option>
<option value="amsafah_assouel">Amsafah Assouel</option>
<option value="amsafah_diour_saboune">Amsafah Diour Saboune</option>
<option value="annakhil">Annakhil</option>
<option value="arsat_ali_salah">Arsat Ali Salah</option>
<option value="arsat_el_maach">Arsat El Maach</option>
<option value="ars_etchbani">Ars etChbani</option>
<option value="ars_et_ben_brahim">Ars et Ben Brahim</option>
<option value="ars_et_berdai">Ars et Berdai</option>
<option value="ars_et_el_baraka">Ars et El Baraka</option>
<option value="ars_et_el_houta_ars_et_laghzail">Ars et El Houta - Ars et Laghzail</option>
<option value="ars_et_el_messioui">Ars et El Messioui</option>
<option value="ars_et_ghzail">Ars et Ghzail</option>
<option value="ars_et_kortbi">Ars et Kortbi</option>
<option value="ars_et_sidi_youssef">Ars et Sidi Youssef</option>
<option value="as_et_el_mellak">As et El Mellak</option>
<option value="askejour">Askejour</option>
<option value="lot_assif">Lot Assif</option>
<option value="assouel">Assouel</option>
<option value="av_abdelkarim_al_khattabi">Av Abdelkarim Al Khattabi</option>
<option value="av_houmane_f_et_taouaki_syba">Av Houmane F et taouaki Syba</option>
<option value="av_med_5">Av Med 5</option>
<option value="av_yarcoub_el_mansour">Av Yarcoub El Mansour</option>
<option value="av._khalid_ben_el_walid">Av. Khalid Ben El Walid</option>
<option value="av._mohammed_vi">Av. Mohammed Vi</option>
<option value="avenue_golf">Avenue Golf</option>
<option value="azbazte">Azbazte</option>
<option value="azli_nord">Azli Nord</option>
<option value="azli_sud">Azli Sud</option>
<option value="azzouzia">Azzouzia</option>
<option value="bab_agnaou">Bab Agnaou</option>
<option value="bab_aylane">Bab Aylane</option>
<option value="bab_dbagh">Bab Dbagh</option>
<option value="bab_doukkala">Bab Doukkala</option>
<option value="bab_ghmate">Bab Ghmate</option>
<option value="bab_hmar">Bab Hmar</option>
<option value="bab_lakhmis">Bab Lakhmis</option>
<option value="bab_samarine">Bab Samarine</option>
<option value="bab_taghzoute">Bab Taghzoute</option>
<option value="badr">Badr</option>
<option value="bahia">Bahia</option>
<option value="baroudienne">Baroudienne</option>
<option value="bel_majad">Bel Majad</option>
<option value="ben_akil">Ben Akil</option>
<option value="ben_salah">Ben Salah</option>
<option value="borj_zitoune">Borj Zitoune</option>
<option value="bougharbal">Bougharbal</option>
<option value="boumenkar">Boumenkar</option>
<option value="boussakri">Boussakri</option>
<option value="boustane">Boustane</option>
<option value="centre_acima">Centre Acima</option>
<option value="chaouf_azzouzia">Chaouf Azzouzia</option>
<option value="charaf">Charaf</option>
<option value="chariaa_madaris">Chariaa Madaris</option>
<option value="chkili">Chkili</option>
<option value="chouf_ayadi">Chouf Ayadi</option>
<option value="chu_med_6">Chu Med 6</option>
<option value="cite_de_police">Cité De Police</option>
<option value="complexe_youssef_ben_tachfine">Complexe Youssef Ben Tachfine</option>
<option value="residence_dalia">Residence Dalia</option>
<option value="daoudiate">Daoudiate</option>
<option value="dar_al_bir_wa_alihssane">Dar Al Bir Wa Alihssane</option>
<option value="dar_hamra">Dar Hamra</option>
<option value="route_casa">Route Casa</option>
<option value="dar_saada_sidi_ghanem">Dar Saada Sidi Ghanem</option>
<option value="dar_tounsi">Dar Tounsi</option>
<option value="derb_dabachi">Derb Dabachi</option>
<option value="diour_echchouhada">Diour Echchouhada</option>
<option value="diour_el_boun">Diour El Boun</option>
<option value="douar_abiad">Douar Abiad</option>
<option value="douar_akioud">Douar Akioud</option>
<option value="douar_al_hafra">Douar Al Hafra</option>
<option value="douar_lahrach">Douar Lahrach</option>
<option value="douar_berrada">Douar Berrada</option>
<option value="douar_boulaghraib">Douar Boulaghraib</option>
<option value="douar_chaouf">Douar Chaouf</option>
<option value="douar_dirkawa_douar_jinane_ben_akil">Douar Dirkawa Douar Jinane Ben Akil</option>
<option value="douar_el_ain">Douar El Ain</option>
<option value="douar_el_askar_lkdim">Douar El Askar Lkdim</option>
<option value="douar_el_fakhara">Douar El Fakhara</option>
<option value="douarkoudia">DouarKoudia</option>
<option value="douar_el_massi_ben_akil_ben_daoud">Douar El Massi Ben Akil Ben Daoud</option>
<option value="douar_el_sifiani_i">Douar El Sifiani I</option>
<option value="douar_elfrougia">Douar Elfrougia</option>
<option value="douar_el_goumi">Douar El Goumi</option>
<option value="douar_elhameri">Douar Elhameri</option>
<option value="douar_elhofra">Douar Elhofra</option>
<option value="douar_elmaassera">Douar Elmaassera</option>
<option value="douar_sraghna">Douar Sraghna</option>
<option value="douar_grawa">Douar Grawa</option>
<option value="douar_jdid">Douar Jdid</option>
<option value="douar_machou">Douar Machou</option>
<option value="douar_m_hamid">Douar M'hamid</option>
<option value="douar_m_khaznia">Douar M'khaznia</option>
<option value="douar_sidi_dou">Douar Sidi Dou</option>
<option value="douar_soultan">Douar Soultan</option>
<option value="douar_tamsna">Douar Tamsna</option>
<option value="douar_elhamera_elmaasera_elgoumi">Douar: Elhamera -Elmaasera-Elgoumi</option>
<option value="douar_hajja_habiba_elmaassera">Douar Hajja-Habiba - Elmaassera</option>
<option value="drissia">Drissia</option>
<option value="eghli7_(m_hamid)">Eghli7 (M'hamid)</option>
<option value="el_kanariya">El Kanariya</option>
<option value="fakhara">Fakhara</option>
<option value="fhal_zafriti_ksour_bab_ftouh">Fhal Zafriti Ksour Bab Ftouh</option>
<option value="garage_ferailleur">Garage Ferailleur</option>
<option value="gueliz">Gueliz</option>
<option value="h.targa">H.Targa</option>
<option value="harouchi">Harouchi</option>
<option value="hart_soura">Hart Soura</option>
<option value="_hay_114_sud"> Hay 114 Sud</option>
<option value="hay114_nord">Hay114 Nord</option>
<option value="hay_al_bahja">Hay Al Bahja</option>
<option value="hay_el_hassani">Hay El Hassani</option>
<option value="hay_el_mohammadi">Hay El Mohammadi</option>
<option value="hay_moukaf_bin_laarassi">Hay Moukaf Bin Laarassi</option>
<option value="hay_salam">Hay Salam</option>
<option value="hay_youssef_ben_tachfin">Hay Youssef Ben Tachfin</option>
<option value="hay_zerktouni">Hay Zerktouni</option>
<option value="hivernage">Hivernage</option>
<option value="hopital_militaire">Hopital Militaire</option>
<option value="hosna">Hosna</option>
<option value="ighli_1">Ighli 1</option>
<option value="imeuble_aswak_assalam">Imeuble Aswak Assalam</option>
<option value="imeuble_habouss_bab_doukala">Imeuble Habouss Bab Doukala</option>
<option value="immeuble_atlassi">Immeuble Atlassi</option>
<option value="hay_el_inara">Hay El Inara</option>
<option value="hay_issil">Hay Issil</option>
<option value="quartier_izdihar">Quartier Izdihar</option>
<option value="hay_iziki">Hay Iziki</option>
<option value="place_jamaa_el_fna">Place Jamaa El Fna</option>
<option value="immeuble_jawahir">Immeuble Jawahir</option>
<option value="jbel_gueliz">Jbel Gueliz</option>
<option value="j_et_sakane">J et Sakane</option>
<option value="jnan_ben_chagra">Jnan Ben Chagra</option>
<option value="jnanate_3">Jnanate 3</option>
<option value="jnane_elafya">Jnane Elafya</option>
<option value="kaa_lhouma">Kaa Lhouma</option>
<option value="kaat_benahid">Kaat Benahid</option>
<option value="kachich">Kachich</option>
<option value="karia_assiyahia">Karia Assiyahia</option>
<option value="kasbah">Kasbah</option>
<option value="kbour_echou">Kbour Echou</option>
<option value="koudia_laabid">Koudia Laabid</option>
<option value="la_carelle">La Carelle</option>
<option value="la_liberte">La Libérté</option>
<option value="la_menara">La Menara</option>
<option value="la_poterne">La Potèrne</option>
<option value="laksour">Laksour</option>
<option value="logement_sociaux">Logement Sociaux</option>
<option value="loma">Loma</option>
<option value="lot_ali_ouhmad_semlalia">Lot Ali Ouhmad Semlalia</option>
<option value="lot_fondation.hassan_2">Lot Fondation.Hassan 2</option>
<option value="lot_kawtar">Lot Kawtar</option>
<option value="lot_saada_menara">Lot Saada Menara</option>
<option value="lot_yassmine">Lot Yassmine</option>
<option value="lotissement_adrar">Lotissement Adrar</option>
<option value="lotissement_al_massar">Lotissement Al Massar</option>
<option value="lotissement_andalous">Lotissement Andalous</option>
<option value="lotissement_bel_bekkar_1_et_2">Lotissement Bel Bekkar 1 et 2</option>
<option value="lotissement_belkahia">Lotissement Belkahia</option>
<option value="lotissement_bokar">Lotissement Bokar</option>
<option value="lotissement_boumesmar">Lotissement Boumesmar</option>
<option value="lotissement_ibn_khaldoun">Lotissement Ibn Khaldoun</option>
<option value="lotissement_jaouhara">Lotissement Jaouhara</option>
<option value="lotissement_laarbi">Lotissement Laarbi</option>
<option value="lotissement_laksour_route_de_casa">Lotissement Laksour Route De Casa</option>
<option value="lotissement_lalla_haya">Lotissement Lalla Haya</option>
<option value="lot_maataalah">Lot Maataalah</option>
<option value="lotissement_masmoudi">Lotissement Masmoudi</option>
<option value="lotissement_riad_salam">Lotissement Riad Salam</option>
<option value="_lotissement_riad_annakhil"> Lotissement Riad Annakhil</option>
<option value="lotissement_sidi_mbarek">Lotissement Sidi Mbarek</option>
<option value="lotissement_zakaria">Lotissement Zakaria</option>
<option value="lotissment_ikhtiyar">Lotissment Ikhtiyar</option>
<option value="mabrouka">Mabrouka</option>
<option value="majorelle">Majorelle</option>
<option value="mansour_eddahbi">Mansour Eddahbi</option>
<option value="marche_des_gros">Marché Des Gros</option>
<option value="marstane_2_3_et_4">Marstane 2, 3 et 4</option>
<option value="massira_1_a">Massira 1 A</option>
<option value="massira_1_b">Massira 1 B</option>
<option value="massira_1_c">Massira 1 C</option>
<option value="massira_1_d">Massira 1 D</option>
<option value="massira_2_d">Massira 2 D</option>
<option value="massira_2_e">Massira 2 E</option>
<option value="massira_2a">Massira 2A</option>
<option value="massira_2b">Massira 2B</option>
<option value="massira_2c">Massira 2C</option>
<option value="massira_3a">Massira 3A</option>
<option value="massira_3b">Massira 3B</option>
<option value="massira_3c">Massira 3C</option>
<option value="m_hamid3_et_4">M'hamid3 et 4</option>
<option value="mhamid_5">Mhamid 5</option>
<option value="mhamid_7">Mhamid 7</option>
<option value="mhamid_9">Mhamid 9</option>
<option value="mjatt_1">Mjatt 1</option>
<option value="mjatt_2">Mjatt 2</option>
<option value="mouassine">Mouassine</option>
<option value="msallah">Msallah</option>
<option value="my_rachid">My Rachid</option>
<option value="nahda">Nahda</option>
<option value="nassim">Nassim</option>
<option value="palemeraie">Palemeraie</option>
<option value="place_liberte">Place Liberté</option>
<option value="pompiers">Pompiers</option>
<option value="quartier_de_l_hopital">Quartier De L'hopital</option>
<option value="quartier_hara">Quartier Hara</option>
<option value="quartier_hivernage_1">Quartier Hivernage 1</option>
<option value="quartier_hivernage_2">Quartier Hivernage 2</option>
<option value="quartier_sidi_abbad_1_2_4_et_5">Quartier Sidi Abbad 1, 2, 4 et 5</option>
<option value="rahba_kadima">Rahba Kadima</option>
<option value="residence_amalkis">Residence Amalkis</option>
<option value="riad_laarrous">Riad Laarrous</option>
<option value="rmila_jbel_lakhdar">Rmila Jbel Lakhdar</option>
<option value="rouidate">Rouidate</option>
<option value="route_de_casa">Route De Casa</option>
<option value="route_souihla">Route Souihla</option>
<option value="rue_ben_aicha">Rue Ben Aicha</option>
<option value="rue_les_vieux_marrakchis">Rue Les Vieux Marrakchis</option>
<option value="rue_lobnane">Rue Lobnane</option>
<option value="rue_mohamed_el_bakkal">Rue Mohamed El Bakkal</option>
<option value="rue_rhal_ben_ahmed">Rue Rhal Ben Ahmed</option>
<option value="ryad_el_moukha">Ryad El Moukha</option>
<option value="ryad_zitounejdid">Ryad ZitouneJdid</option>
<option value="ryad_zitounelakdim">Ryad ZitouneLakdim</option>
<option value="saada_1_et_4">Saada 1 et 4</option>
<option value="saada_2_et_3">Saada 2 et 3</option>
<option value="saada_5_et_6">Saada 5 et 6</option>
<option value="saadia">Saadia</option>
<option value="sakina">Sakina</option>
<option value="sanaoubar">Sanaoubar</option>
<option value="saqqar">Saqqar</option>
<option value="sbaia">Sbaia</option>
<option value="sebtienne">Sebtienne</option>
<option value="semlalia">Semlalia</option>
<option value="sidi_aamara">Sidi Aamara</option>
<option value="sidi_abbad_3">Sidi Abbad 3</option>
<option value="sidi_abdellaziz">Sidi Abdellaziz</option>
<option value="sidi_ayoub">Sidi Ayoub</option>
<option value="sidi_ben_slimane">Sidi Ben Slimane</option>
<option value="sidi_ghanem">Sidi Ghanem</option>
<option value="sidi_mimoune">Sidi Mimoune</option>
<option value="sidi_youssef_ben_ali">Sidi Youssef Ben Ali</option>
<option value="sinko">Sinko</option>
<option value="socoma">Socoma</option>
<option value="sofia">Sofia</option>
<option value="souk_lakhmiss">Souk Lakhmiss</option>
<option value="souk_larbaa">Souk Larbaa</option>
<option value="souks">Souks</option>
<option value="souria">Souria</option>
<option value="station_d_epuration">Station D Epuration</option>
<option value="syba_1">Syba 1</option>
<option value="syba_2">Syba 2</option>
<option value="syba_3">Syba 3</option>
<option value="syba_4">Syba 4</option>
<option value="tabhirt">Tabhirt</option>
<option value="talouj_et_e_1+zaytouna">Talouj et e 1+Zaytouna</option>
<option value="targua_zdaghia">Targua Zdaghia</option>
<option value="tariq_ibnou_ziad">Tariq Ibnou Ziad</option>
<option value="tilar_et_e_un_partie_douar_slatine_douar_el_kihili">Tilar et e Un Partie Douar Slatine Douar El Kihili</option>
<option value="unite_2">Unité 2</option>
<option value="unite_4">Unité 4</option>
<option value="unite_5">Unité 5</option>
<option value="unite1">Unité1</option>
<option value="unite_3">Unité 3</option>
<option value="wirgane">Wirgane</option>
<option value="yassmine">Yassmine</option>
<option value="zaouia_abbassia">Zaouia Abbassia</option>
<option value="zaouite_lahdar">Zaouite Lahdar</option>
<option value="zone_industrielle">Zone Industrielle</option>
<option value="zouhour_1">Zouhour 1</option>
<option value="zouhour_2">Zouhour 2</option>
<option value="zraib">Zraib</option>