<option value="_la_patrouilleuse"> La Patrouilleuse</option>
<option value="agdal">Agdal</option>
<option value="ain_sefli">Ain Sefli</option>
<option value="al_izdihar">Al Izdihar</option>
<option value="alem">Alem</option>
<option value="ancienne_medina">Ancienne Medina</option>
<option value="anciens_combatants">Anciens Combatants</option>
<option value="bab_belkari">Bab Belkari</option>
<option value="bab_jdid">Bab Jdid</option>
<option value="bab_rha_zine_el_abidine">Bab Rha Zine El Abidine</option>
<option value="bab_tizimi">Bab Tizimi</option>
<option value="beni_mhamed">Beni Mhamed</option>
<option value="blad_my_bouazza">Blad My Bouazza</option>
<option value="borj_my_omar">Borj My Omar</option>
<option value="cadem">Cadem</option>
<option value="de_l_ecole">De L'ecole</option>
<option value="diour_jdad_beni_mhamed">Diour Jdad Beni Mhamed</option>
<option value="el_amane_(ex_diour_essalam)">El Amane (Ex Diour Essalam)</option>
<option value="el_atlas">El Atlas</option>
<option value="el_bassatine">El Bassatine</option>
<option value="el_houria">El Houria</option>
<option value="el_inara">El Inara</option>
<option value="el_kasba">El Kasba</option>
<option value="el_malah_lakdim">El Malah Lakdim</option>
<option value="el_manar">El Manar</option>
<option value="el_mansour">El Mansour</option>
<option value="el_ouahda">El Ouahda</option>
<option value="enasr">Enasr</option>
<option value="enassim">Enassim</option>
<option value="essaada_(ex_la_touraine)">Essaada (Ex La Touraine)</option>
<option value="essalam_my_messaoud">Essalam My Messaoud</option>
<option value="groupes_bmo">Groupes Bmo</option>
<option value="hamria">Hamria</option>
<option value="hay_akhatar">Hay Akhatar</option>
<option value="hay_el_amal">Hay El Amal</option>
<option value="hay_el_massira">Hay El Massira</option>
<option value="hay_el_mostachfa">Hay El Mostachfa</option>
<option value="hay_sahara_ii">Hay Sahara II</option>
<option value="hay_takadoum">Hay Takadoum</option>
<option value="ibn_rochd">Ibn Rochd</option>
<option value="kamilia">Kamilia</option>
<option value="kobt_souk">Kobt Souk</option>
<option value="lahboul">Lahboul</option>
<option value="l_hacienda">L'hacienda</option>
<option value="lot_el_baladia">Lot El Baladia</option>
<option value="marjane_2">Marjane 2</option>
<option value="marjane_3">Marjane 3</option>
<option value="marjane_4_et_5">Marjane 4 et 5</option>
<option value="marjane_6">Marjane 6</option>
<option value="marjane_i">Marjane I</option>
<option value="naim_(3_4_5_et_6)">Naim (3-4-5 et 6)</option>
<option value="oued_eddahab">Oued Eddahab</option>
<option value="oujeh_arous">Oujeh Arous</option>
<option value="ouljat_lamrania">Ouljat Lamrania</option>
<option value="plaisance">Plaisance</option>
<option value="quartierain_chebik">QuartierAin Chebik</option>
<option value="quartierhjaoua">QuartierHjaoua</option>
<option value="quartier_bel_air">Quartier Bel Air</option>
<option value="quartier_berrada">Quartier Berrada</option>
<option value="quartier_el_ain">Quartier El Ain</option>
<option value="quartier_el_hammam">Quartier El Hammam</option>
<option value="quartier_el_mers">Quartier El Mers</option>
<option value="quartier_industriel">Quartier Industriel</option>
<option value="quartier_la_belle_vue">Quartier La Belle Vue</option>
<option value="quartier_lahmidiyne">Quartier Lahmidiyne</option>
<option value="quartier_militaire_olm">Quartier Militaire Olm</option>
<option value="quartier_my_ismail">Quartier My Ismail</option>
<option value="quartier_sahraoua">Quartier Sahraoua</option>
<option value="quartier_tajamouati">Quartier Tajamouati</option>
<option value="riad_my_meliana">Riad My Meliana</option>
<option value="rizana_route_agouray">Rizana Route Agouray</option>
<option value="roua">Roua</option>
<option value="rouamzaine">Rouamzaine</option>
<option value="saidia">Saidia</option>
<option value="saramito">Saramito</option>
<option value="sbata">Sbata</option>
<option value="sekka">Sekka</option>
<option value="sidi_amer">Sidi Amer</option>
<option value="sidi_baba">Sidi Baba</option>
<option value="sidi_bouzkri">Sidi Bouzkri</option>
<option value="sidi_said">Sidi Said</option>
<option value="souraya">Souraya</option>
<option value="touarga">Touarga</option>
<option value="toulal">Toulal</option>
<option value="wifak">Wifak</option>
<option value="wislane">Wislane</option>
<option value="zahoua">Zahoua</option>
<option value="zarhounia">Zarhounia</option>
<option value="zitoune">Zitoune</option>