<option value="bd_des_f_a_r">Bd Des F A R</option>
<option value="bd_mly_youssef">Bd Mly Youssef</option>
<option value="bd_mohamed_v">Bd Mohamed V</option>
<option value="bd_sidi_mohamed_ben_abdellah">Bd Sidi Mohamed Ben Abdellah</option>
<option value="bd_yacoub_el_mansour">Bd Yacoub El Mansour</option>
<option value="bd_zenata">Bd Zenata</option>
<option value="bd_zerktouni">Bd Zerktouni</option>
<option value="biout_kara">Biout Kara</option>
<option value="chantier_sidi_moussa">Chantier Sidi Moussa</option>
<option value="cite_jacques">Cite Jacques</option>
<option value="cite_la_falaise">Cite La Falaise</option>
<option value="cite_strafor">Cite Strafor</option>
<option value="complexe_monjolie">Complexe Monjolie</option>
<option value="derb_agdal">Derb Agdal</option>
<option value="derb_chabab_a_et_c">Derb Chabab A et C</option>
<option value="derb_chabab_b">Derb Chabab B</option>
<option value="derb_duchemin">Derb Duchemin</option>
<option value="derb_el_fath">Derb El Fath</option>
<option value="derb_errachidia">Derb Errachidia</option>
<option value="derb_erreda">Derb Erreda</option>
<option value="derb_jamila">Derb Jamila</option>
<option value="derb_kinani">Derb Kinani</option>
<option value="derb_l_habitat">Derb L'habitat</option>
<option value="derb_marrakech">Derb Marrakech</option>
<option value="derb_mascato">Derb Mascato</option>
<option value="derb_meknes">Derb Meknes</option>
<option value="derb_r_bat">Derb R'bat</option>
<option value="derb_riad_i">Derb Riad I</option>
<option value="derb_riad_ii">Derb Riad II</option>
<option value="derb_saada">Derb Saada</option>
<option value="derb_saada_(derb_60)">Derb Saada (Derb 60)</option>
<option value="derb_selline">Derb Selline</option>
<option value="derb_wrida">Derb Wrida</option>
<option value="diiour_lakrai_rue_caid_laidi">Diiour Lakrai Rue Caid Laidi</option>
<option value="diour_butagaz">Diour Butagaz</option>
<option value="diour_chouhada">Diour Chouhada</option>
<option value="diour_doukkala">Diour Doukkala</option>
<option value="diour_el_khiria">Diour El Khiria</option>
<option value="diour_frigo">Diour Frigo</option>
<option value="diour_lakrai_rue_caid_bouchaib">Diour Lakrai Rue Caid Bouchaib</option>
<option value="diour_lakrai_rue_caid_thami">Diour Lakrai Rue Caid Thami</option>
<option value="diour_lakram">Diour Lakram</option>
<option value="diour_l_habitat">Diour L'habitat</option>
<option value="diour_nicolas">Diour Nicolas</option>
<option value="douar_ameur_samir">Douar Ameur Samir</option>
<option value="douar_cheikh">Douar Cheikh</option>
<option value="douar_chrif">Douar Chrif</option>
<option value="douar_el_haloui">Douar El Haloui</option>
<option value="douar_el_massira">Douar El Massira</option>
<option value="douar_essafi">Douar Essafi</option>
<option value="douar_frigou">Douar Frigou</option>
<option value="douar_ghazouane">Douar Ghazouane</option>
<option value="douar_hadj_bouazza">Douar Hadj Bouazza</option>
<option value="douar_labradaa">Douar Labradaa</option>
<option value="douar_lachhab">Douar Lachhab</option>
<option value="douar_ouarda">Douar Ouarda</option>
<option value="douar_oueld_lahcen_jaja">Douar Oueld Lahcen Jaja</option>
<option value="douar_rhahla">Douar Rhahla</option>
<option value="douar_zaima">Douar Zaima</option>
<option value="douar_zouaghat">Douar Zouaghat</option>
<option value="dr_hadj_miloudi">Dr Hadj Miloudi</option>
<option value="ecran_samir_(hassania)">Ecran Samir (Hassania)</option>
<option value="hassania_bloc_a">Hassania Bloc A</option>
<option value="hassania_bloc_b_c_et_d">Hassania Bloc B, C et D</option>
<option value="hassania_i_et_ii">Hassania I et II</option>
<option value="hay_el_falah">Hay El Falah</option>
<option value="hay_el_farah_i">Hay El Farah I</option>
<option value="hay_el_wahda">Hay El Wahda</option>
<option value="hay_ennasr">Hay Ennasr</option>
<option value="immeuble_fadili">Immeuble Fadili</option>
<option value="inara_iii">Inara III</option>
<option value="kasbah">Kasbah</option>
<option value="la_grande_rue">La Grande Rue</option>
<option value="la_siesta">La Siesta</option>
<option value="lot_abdelmoumen">Lot Abdelmoumen</option>
<option value="lot_amal">Lot Amal</option>
<option value="lot_amal_ezzohour">Lot Amal Ezzohour</option>
<option value="lot_anfa">Lot Anfa</option>
<option value="lot_ard_sghir">Lot Ard Sghir</option>
<option value="lot_belle_vue">Lot Belle Vue</option>
<option value="lot_ben_hamdoune">Lot Ben Hamdoune</option>
<option value="lot_chhaouta">Lot Chhaouta</option>
<option value="lot_dakhla">Lot Dakhla</option>
<option value="lot_eddahbi">Lot Eddahbi</option>
<option value="lot_el_assil">Lot El Assil</option>
<option value="lot_el_fajr">Lot El Fajr</option>
<option value="lot_el_farah_ii">Lot El Farah II</option>
<option value="lot_el_houria_i_et_ii">Lot El Houria I et II</option>
<option value="lot_el_houria_iii">Lot El Houria III</option>
<option value="lot_el_imane">Lot El Imane</option>
<option value="lot_el_massira">Lot El Massira</option>
<option value="lot_el_wafa">Lot El Wafa</option>
<option value="lot_ennakhaly">Lot Ennakhaly</option>
<option value="lot_esseddik">Lot Esseddik</option>
<option value="lot_eucaliptus">Lot Eucaliptus</option>
<option value="lot_ezzohour">Lot Ezzohour</option>
<option value="lot_grini_i_et_ii">Lot Grini I et II</option>
<option value="lot_groupe_yassmine">Lot Groupe Yassmine</option>
<option value="lot_inara_i">Lot Inara I</option>
<option value="lot_inara_ii">Lot Inara II</option>
<option value="lot_intelaka">Lot Intelaka</option>
<option value="lot_la_colline">Lot La Colline</option>
<option value="lot_la_gare">Lot La Gare</option>
<option value="lot_laayoune">Lot Laayoune</option>
<option value="lot_labhira">Lot Labhira</option>
<option value="lot_le_soleil">Lot Le Soleil</option>
<option value="lot_louma">Lot Louma</option>
<option value="lot_malak_beach">Lot Malak Beach</option>
<option value="lot_manesmane">Lot Manesmane</option>
<option value="lot_meriem">Lot Meriem</option>
<option value="lot_mesbahiate">Lot Mesbahiate</option>
<option value="lot_mesk_ellil">Lot Mesk Ellil</option>
<option value="lot_moumen">Lot Moumen</option>
<option value="lot_nice_i_et_ii">Lot Nice I et II</option>
<option value="lot_oued_eddahab">Lot Oued Eddahab</option>
<option value="lot_oued_el_maleh">Lot Oued El Maleh</option>
<option value="lot_qods">Lot Qods</option>
<option value="lot_riad_essalam">Lot Riad Essalam</option>
<option value="lot_sabl_et_te">Lot Sabl et te</option>
<option value="lot_sabre">Lot Sabre</option>
<option value="lot_sania">Lot Sania</option>
<option value="lot_sud_gare">Lot Sud Gare</option>
<option value="lot_yassmina">Lot Yassmina</option>
<option value="marsa">Marsa</option>
<option value="monica_plage">Monica Plage</option>
<option value="oulad_hami_moun">Oulad Hami Moun</option>
<option value="place_moutanabbi">Place Moutanabbi</option>
<option value="port_commercial">Port Commercial</option>
<option value="port_du_peche">Port Du Peche</option>
<option value="port_maritime">Port Maritime</option>
<option value="quartier_kasbah">Quartier Kasbah</option>
<option value="quartier_russe">Quartier Russe</option>
<option value="quartier_souk_lakdim">Quartier Souk Lakdim</option>
<option value="residance3_mars">Résidance3 Mars</option>
<option value="residanceanouar">RésidanceAnouar</option>
<option value="residanceben_khaldoune">RésidanceBen Khaldoune</option>
<option value="residanceessalama">RésidanceEssalama</option>
<option value="residancefedala_park">RésidanceFedala Park</option>
<option value="residanceibn_rochd">RésidanceIbn Rochd</option>
<option value="residancela_corniche">RésidanceLa Corniche</option>
<option value="residancemimosa">RésidanceMimosa</option>
<option value="residanceo_n_e">RésidanceO N E</option>
<option value="residanceroukaya">RésidanceRoukaya</option>
<option value="residance_9_juill_et">Résidance 9 Juill et</option>
<option value="residance_acharaf">Résidance Acharaf</option>
<option value="residance_floriane">Résidance Floriane</option>
<option value="residance_ikhlass">Résidance Ikhlass</option>
<option value="residance_khilaji">Résidance Khilaji</option>
<option value="residance_le_littoral">Résidance Le Littoral</option>
<option value="residance_le_palais">Résidance Le Palais</option>
<option value="residance_mechouar">Résidance Mechouar</option>
<option value="residance_monica">Résidance Monica</option>
<option value="residance_oued_el_makhazine">Résidance Oued El Makhazine</option>
<option value="residance_panorama">Résidance Panorama</option>
<option value="residance_porte_du_golf">Résidance Porte Du Golf</option>
<option value="residance_redouane">Résidance Redouane</option>
<option value="residance_rose_fedala">Résidance Rose Fedala</option>
<option value="residance_sebta">Résidance Sebta</option>
<option value="rue_abdelaziz_benchakroune">Rue Abdelaziz Benchakroune</option>
<option value="rue_abdelaziz_boutaleb">Rue Abdelaziz Boutaleb</option>
<option value="rue_abdelmoumen">Rue Abdelmoumen</option>
<option value="rue_abdelwahed_derraq">Rue Abdelwahed Derraq</option>
<option value="rue_abdelwahed_el_marrakchi">Rue Abdelwahed El Marrakchi</option>
<option value="rue_abderrahmane_serghini">Rue Abderrahmane Serghini</option>
<option value="rue_allal_el_fassi">Rue Allal El Fassi</option>
<option value="rue_allal_en_abdellah">Rue Allal En Abdellah</option>
<option value="rue_badis">Rue Badis</option>
<option value="rue_baghdad">Rue Baghdad</option>
<option value="rue_bir_anzarane">Rue Bir Anzarane</option>
<option value="rue_bourgogne">Rue Bourgogne</option>
<option value="rue_brahim_roudani">Rue Brahim Roudani</option>
<option value="rue_cheikh_chouaib_doukkali">Rue Cheikh Chouaib Doukkali</option>
<option value="rue_d_alger">Rue D'alger</option>
<option value="rue_d_amade">Rue D'amade</option>
<option value="rue_damas">Rue Damas</option>
<option value="rue_de_calais">Rue De Calais</option>
<option value="rue_de_fes">Rue De Fes</option>
<option value="rue_de_safi">Rue De Safi</option>
<option value="rue_de_s_et_tat">Rue De S et tat</option>
<option value="rue_de_souss">Rue De Souss</option>
<option value="rue_de_tanger">Rue De Tanger</option>
<option value="rue_d_el_gharb">Rue D'el Gharb</option>
<option value="rue_d_el_haouz">Rue D'el Haouz</option>
<option value="rue_des_villas">Rue Des Villas</option>
<option value="rue_d_ifni">Rue D'ifni</option>
<option value="rue_d_ifrane">Rue D'ifrane</option>
<option value="rue_doukkala">Rue Doukkala</option>
<option value="rue_du_caire">Rue Du Caire</option>
<option value="rue_du_port">Rue Du Port</option>
<option value="rue_du_rif">Rue Du Rif</option>
<option value="rue_el_mansour_eddahbi">Rue El Mansour Eddahbi</option>
<option value="rue_farhat_hachad">Rue Farhat Hachad</option>
<option value="rue_grenadier">Rue Grenadier</option>
<option value="rue_hansali">Rue Hansali</option>
<option value="rue_houmane_el_fatouaki">Rue Houmane El Fatouaki</option>
<option value="rue_ibn_abi_zeraa">Rue Ibn Abi Zeraa</option>
<option value="rue_ibn_batouta">Rue Ibn Batouta</option>
<option value="rue_ibn_khafaja">Rue Ibn Khafaja</option>
<option value="rue_ibn_khaldoune">Rue Ibn Khaldoune</option>
<option value="rue_ibn_tachfine">Rue Ibn Tachfine</option>
<option value="rue_ibn_toumert">Rue Ibn Toumert</option>
<option value="rue_ibn_zohr">Rue Ibn Zohr</option>
<option value="rue_ibnou_mourahhel">Rue Ibnou Mourahhel</option>
<option value="rue_imam_malik">Rue Imam Malik</option>
<option value="rue_jahid">Rue Jahid</option>
<option value="rue_kenitra">Rue Kenitra</option>
<option value="rue_la_fontaine">Rue La Fontaine</option>
<option value="rue_mauritanie">Rue Mauritanie</option>
<option value="rue_mekkah">Rue Mekkah</option>
<option value="rue_melilia">Rue Melilia</option>
<option value="rue_mly_driss">Rue Mly Driss</option>
<option value="rue_mly_ismail">Rue Mly Ismail</option>
<option value="rue_mohamed_el_qorri">Rue Mohamed El Qorri</option>
<option value="rue_nador">Rue Nador</option>
<option value="rue_nekkour">Rue Nekkour</option>
<option value="rue_oued_el_makhazine">Rue Oued El Makhazine</option>
<option value="rue_rachidi">Rue Rachidi</option>
<option value="rue_rouane">Rue Rouane</option>
<option value="rue_tafilal_et">Rue Tafilal et</option>
<option value="rue_tarik">Rue Tarik</option>
<option value="rue_tripolie">Rue Tripolie</option>
<option value="zone_industrielle">Zone Industrielle</option>