<option value="aarid">Aarid</option>
<option value="barakia">Barakia</option>
<option value="bouarourou">Bouarourou</option>
<option value="bouchouaf">Bouchouaf</option>
<option value="centre_ville">Centre Ville</option>
<option value="chaala">Chaala</option>
<option value="el_khattabi">El Khattabi</option>
<option value="el_kindi">El Kindi</option>
<option value="hay_el_askari">Hay El Askari</option>
<option value="hay_el_idari">Hay El Idari</option>
<option value="hay_el_madani">Hay El Madani</option>
<option value="hay_el_matar">Hay El Matar</option>
<option value="ichoumay">Ichoumay</option>
<option value="igounaf">Igounaf</option>
<option value="issabanen">Issabanen</option>
<option value="laarassi">Laarassi</option>
<option value="laari_cheikh">Laari Cheikh</option>
<option value="oueld_lahcen">Oueld Lahcen</option>
<option value="ouled_tayeb">Ouled Tayeb</option>
<option value="ouled_boutaib">Ouled Boutaib</option>
<option value="ouled_brahim">Ouled Brahim</option>
<option value="ouled_mimoun">Ouled Mimoun</option>
<option value="rigo_laris">Rigo Laris</option>
<option value="sidi_ali">Sidi Ali</option>
<option value="tirakaa">Tirakaa</option>
<option value="tizighine">Tizighine</option>