<option value="al_andalouss">Al Andalouss</option>
<option value="al_azhar">Al Azhar</option>
<option value="al_boustane">Al Boustane</option>
<option value="al_hanaa_1">Al Hanaa 1</option>
<option value="al_hay_askari">Al Hay Askari</option>
<option value="al_hikma">Al Hikma</option>
<option value="al_irfane">Al Irfane</option>
<option value="al_jadid">Al Jadid</option>
<option value="al_jaouhara">Al Jaouhara</option>
<option value="al_khalloufi">Al Khalloufi</option>
<option value="al_mokaouama">Al Mokaouama</option>
<option value="al_moustakbal">Al Moustakbal</option>
<option value="al_qods">Al Qods</option>
<option value="al_wafaa">Al Wafaa</option>
<option value="al_widadya">Al Widadya</option>
<option value="al_wifaq">Al Wifaq</option>
<option value="almirali">Almirali</option>
<option value="amlak_lmakhzania">Amlak Lmakhzania</option>
<option value="aouatif">Aouatif</option>
<option value="arriadi">Arriadi</option>
<option value="assaada">Assaada</option>
<option value="assalam">Assalam</option>
<option value="av._des_far_(omar_rifi)">Av. Des Far (Omar Rifi)</option>
<option value="av._mohamed_ben_mssoud">Av. Mohamed Ben Mssoud</option>
<option value="av._morabitine">Av. Morabitine</option>
<option value="azzaytoun">Azzaytoun</option>
<option value="bab_laghrbi">Bab Laghrbi</option>
<option value="bab_sidi_abdlouhab">Bab Sidi Abdlouhab</option>
<option value="barahmoune">Barahmoune</option>
<option value="barroukech">Barroukech</option>
<option value="bd_ahfir">Bd Ahfir</option>
<option value="bd_allal_ben_abdellah">Bd Allal Ben Abdellah</option>
<option value="bd_brahim_roudani">Bd Brahim Roudani</option>
<option value="bd_mohamed_v">Bd Mohamed V</option>
<option value="bd._allal_el_fassi">Bd. Allal El Fassi</option>
<option value="bd._armee_de_liberation">Bd. Armée De Libération</option>
<option value="bd._chouhada">Bd. Chouhada</option>
<option value="bd._derfoufi">Bd. Derfoufi</option>
<option value="bd._hassan_ii">Bd. Hassan II</option>
<option value="bd._loujida_moustafa">Bd. Loujida Moustafa</option>
<option value="bd._lt_benhoussine">Bd. Lt Benhoussine</option>
<option value="bd._maghrib_arabi">Bd. Maghrib Arabi</option>
<option value="bd._moulay_el_hassan">Bd. Moulay El Hassan</option>
<option value="bd._qadi_eyad">Bd. Qadi Eyad</option>
<option value="bd._yacoub_mansour">Bd. Yacoub Mansour</option>
<option value="bd._zaid_ben_soultane(route_jrada)">Bd. Zaid Ben Soultane(Route Jrada)</option>
<option value="belmrah">Belmrah</option>
<option value="ben_khirane">Ben Khirane</option>
<option value="bloc_dem">Bloc Dem</option>
<option value="boudir">Boudir</option>
<option value="bouknadel">Bouknadel</option>
<option value="byoud">Byoud</option>
<option value="caserne_militaire_lamhalla">Caserne Militaire Lamhalla</option>
<option value="centre_ville">Centre Ville</option>
<option value="dd_ahfir">Dd Ahfir</option>
<option value="derb_ali_mahmoud">Derb Ali Mahmoud</option>
<option value="derb_beroukech">Derb Beroukech</option>
<option value="derb_laarbi">Derb Laarbi</option>
<option value="dhar_lmahla">Dhar Lmahla</option>
<option value="el_amri">El Amri</option>
<option value="el_baladi">El Baladi</option>
<option value="el_baladi_souk_lkhmis">El Baladi Souk Lkhmis</option>
<option value="el_fath">El Fath</option>
<option value="el_haddad">El Haddad</option>
<option value="el_jorf_lakhdar">El Jorf Lakhdar</option>
<option value="el_kadi_ayad">El Kadi Ayad</option>
<option value="el_malaab">El Malaab</option>
<option value="el_massira">El Massira</option>
<option value="el_mharchi">El Mharchi</option>
<option value="el_mohamadi">El Mohamadi</option>
<option value="el_wahda_(cgi)">El Wahda (Cgi)</option>
<option value="ennacer">Ennacer</option>
<option value="enneggadi">Enneggadi</option>
<option value="ennilou">Ennilou</option>
<option value="ennour">Ennour</option>
<option value="essalam">Essalam</option>
<option value="essalam_dhar_lamhalla">Essalam, Dhar Lamhalla</option>
<option value="essamara">Essamara</option>
<option value="gattar">Gattar</option>
<option value="ghar_el_baroud">Ghar El Baroud</option>
<option value="habitat_et_urbanisme">Habitat et Urbanisme</option>
<option value="hakou">Hakou</option>
<option value="haynahda">HayNahda</option>
<option value="hay_agdal">Hay Agdal</option>
<option value="hay_al_enara">Hay Al Enara</option>
<option value="hay_angad">Hay Angad</option>
<option value="hay_askari">Hay Askari</option>
<option value="hay_bangladech">Hay Bangladech</option>
<option value="hay_ben_azzi">Hay Ben Azzi</option>
<option value="hay_ben_kachour">Hay Ben Kachour</option>
<option value="hay_benramdan">Hay Benramdan</option>
<option value="hay_bouarfa">Hay Bouarfa</option>
<option value="hay_boujmaa_lmerdi">Hay Boujmaa Lmerdi</option>
<option value="hay_drafife">Hay Drafife</option>
<option value="hay_ejjenfi">Hay Ejjenfi</option>
<option value="hay_el_aounia">Hay El Aounia</option>
<option value="hay_el_bassatine">Hay El Bassatine</option>
<option value="hay_el_ghoufrane">Hay El Ghoufrane</option>
<option value="hay_el_golf_isli">Hay El Golf Isli</option>
<option value="hay_el_hadiqa">Hay El Hadiqa</option>
<option value="hay_el_karama">Hay El Karama</option>
<option value="hay_el_massakine">Hay El Massakine</option>
<option value="hay_el_miloud">Hay El Miloud</option>
<option value="hay_el_ouhda">Hay El Ouhda</option>
<option value="hay_essalam">Hay Essalam</option>
<option value="hay_hakkou_i_ii_iii">Hay Hakkou I II III</option>
<option value="hay_jawhara">Hay Jawhara</option>
<option value="hay_jdid">Hay Jdid</option>
<option value="hay_koulouch_(el_hassani)">Hay Koulouch (El Hassani)</option>
<option value="hay_louz">Hay Louz</option>
<option value="hay_maamoura">Hay Maamoura</option>
<option value="hay_mgadi">Hay Mgadi</option>
<option value="hay_moulay_miloud">Hay Moulay Miloud</option>
<option value="hay_moulay_mostapha">Hay Moulay Mostapha</option>
<option value="hay_najd_i_et_ii">Hay Najd I et II</option>
<option value="hay_nour">Hay Nour</option>
<option value="hay_pam">Hay Pam</option>
<option value="hay_rja_fellah">Hay Rja Fellah</option>
<option value="hay_salama">Hay Salama</option>
<option value="hay_sidi_maafa">Hay Sidi Maafa</option>
<option value="hay_slimani">Hay Slimani</option>
<option value="hay_tanmia_i_et_ii">Hay Tanmia I et II</option>
<option value="hay_zitoune">Hay Zitoune</option>
<option value="hay_zouhour_i_et_ii">Hay Zouhour I et II</option>
<option value="ibn_khaldoun">Ibn Khaldoun</option>
<option value="ibn_khaldoun_arriadi">Ibn Khaldoun Arriadi</option>
<option value="idriss_al_akbar">Idriss Al Akbar</option>
<option value="jadda">Jadda</option>
<option value="koddan">Koddan</option>
<option value="lahbous">Lahbous</option>
<option value="laksebah">Laksebah</option>
<option value="lalla_aicha">Lalla Aicha</option>
<option value="lazar_et">Lazar et</option>
<option value="lemehalla">Lemehalla</option>
<option value="lemkssem">Lemkssem</option>
<option value="les_iriss">Les Iriss</option>
<option value="lot_ben_mimoune">Lot Ben Mimoune</option>
<option value="lot_ben_omar">Lot Ben Omar</option>
<option value="lot_benkhirane">Lot Benkhirane</option>
<option value="lot_berrichi">Lot Berrichi</option>
<option value="lot_boustane">Lot Boustane</option>
<option value="lot_chourouk">Lot Chourouk</option>
<option value="lot_el_aquel">Lot El Aquel</option>
<option value="lot_el_erfane">Lot El Erfane</option>
<option value="lot_el_hanae">Lot El Hanae</option>
<option value="lot_el_khair">Lot El Khair</option>
<option value="lot_el_moul">Lot El Moul</option>
<option value="lot_el_yatni">Lot El Yatni</option>
<option value="lot_et_talhaoui">Lot et talhaoui</option>
<option value="lot_ghioughi">Lot Ghioughi</option>
<option value="lot_haj_hmida">Lot Haj Hmida</option>
<option value="lot_hamdi">Lot Hamdi</option>
<option value="lot_hassania">Lot Hassania</option>
<option value="lot_ilham">Lot Ilham</option>
<option value="lot_kada_houssine">Lot Kada Houssine</option>
<option value="lot_khalfaoui">Lot Khalfaoui</option>
<option value="lot_laakel">Lot Laakel</option>
<option value="lot_laalej">Lot Laalej</option>
<option value="lot_laalej_dem">Lot Laalej Dem</option>
<option value="lot_lamri_i_et_ii">Lot Lamri I et II</option>
<option value="lot_manar">Lot Manar</option>
<option value="lot_mawhoub">Lot Mawhoub</option>
<option value="lot_mawhoub_awatef">Lot Mawhoub Awatef</option>
<option value="lot_mharchi">Lot Mharchi</option>
<option value="lot_millitaire">Lot Millitaire</option>
<option value="lot_mounia">Lot Mounia</option>
<option value="lot_m_sserdi">Lot M'sserdi</option>
<option value="lot_nakhil">Lot Nakhil</option>
<option value="lot_saada">Lot Saada</option>
<option value="lot_saidi">Lot Saidi</option>
<option value="lot_sakhi">Lot Sakhi</option>
<option value="lot_soultani">Lot Soultani</option>
<option value="lot_talhaoui">Lot Talhaoui</option>
<option value="lot_talhaoui_(rte_sidi_yahya)">Lot Talhaoui (Rte Sidi Yahya)</option>
<option value="lot_taoufiq_boulouiz">Lot Taoufiq Boulouiz</option>
<option value="lot_wassilah">Lot Wassilah</option>
<option value="lotissement_al_khalfaoui">Lotissement Al Khalfaoui</option>
<option value="lotissement_belhoucine+hay_al_hourya">Lotissement Belhoucine+Hay Al Hourya</option>
<option value="lotissement_ben_addi">Lotissement Ben Addi</option>
<option value="lotissement_rghioui_trik_taza">Lotissement Rghioui Trik Taza</option>
<option value="maksam">Maksam</option>
<option value="mbassou">Mbassou</option>
<option value="mechouar_lazari">Mechouar Lazari</option>
<option value="medina_kdima">Medina Kdima</option>
<option value="mohamed_belkhdar">Mohamed Belkhdar</option>
<option value="moulay_youssef">Moulay Youssef</option>
<option value="mounia">Mounia</option>
<option value="mouritanya">Mouritanya</option>
<option value="neiger">Neiger</option>
<option value="ouad_al_makhazine">Ouad Al Makhazine</option>
<option value="oued_issli">Oued Issli</option>
<option value="oued_nachef">Oued Nachef</option>
<option value="ould_chrif">Ould Chrif</option>
<option value="ouled_kadi">Ouled Kadi</option>
<option value="ouled_khouna">Ouled Khouna</option>
<option value="parc_lalla_aicha">Parc Lalla Aicha</option>
<option value="place_nejjarine">Place Nejjarine</option>
<option value="place_sidi_yahya">Place Sidi Yahya</option>
<option value="quartier_industriel">Quartier Industriel</option>
<option value="quartier_des_emirates">Quartier Des Emirates</option>
<option value="rabat">Rabat</option>
<option value="ras_ousfour">Ras Ousfour</option>
<option value="ras_ousfour_+el_maksam">Ras Ousfour +El Maksam</option>
<option value="residence_mouahidine+bloc_haouar">Résidence Mouahidine+Bloc Haouar</option>
<option value="riad">Riad</option>
<option value="route_bekkay_lahbil">Route Bekkay Lahbil</option>
<option value="route_bouknadel">Route Bouknadel</option>
<option value="route_el_aounia">Route El Aounia</option>
<option value="rue_jakarta">Rue Jakarta</option>
<option value="rue_sidi_driss">Rue Sidi Driss</option>
<option value="rue_talhaoui">Rue Talhaoui</option>
<option value="sedrat_bouamoud">Sedrat Bouamoud</option>
<option value="si_lakhdar">Si Lakhdar</option>
<option value="sid_el_mokhtar">Sid El Mokhtar</option>
<option value="sidi_aissa">Sidi Aissa</option>
<option value="sidi_maafa">Sidi Maafa</option>
<option value="sidi_yahya_sidi_maafa_el_qods">Sidi Yahya- Sidi Maafa-El Qods</option>
<option value="skiker">Skiker</option>
<option value="souk_mlililia">Souk Mlililia</option>
<option value="stade_charafi">Stade Charafi</option>
<option value="stade_charafi+mardi_boujamaa">Stade Charafi+Mardi Boujamaa</option>
<option value="tajziate_belhocine">Tajziate Belhocine</option>
<option value="takaddoume_i_et_ii">Takaddoume I et II</option>
<option value="tayert">Tayert</option>
<option value="tben">Tben</option>
<option value="tennis">Tennis</option>
<option value="trik_taza">Trik Taza</option>
<option value="village_et_touba_exterieur">Village et touba Extérieur</option>
<option value="village_moulay_el_miloud">Village Moulay El Miloud</option>
<option value="village_touba_interieur">Village Touba Interieur</option>
<option value="wifaq_1+hay_el_hassani">Wifaq 1+Hay El Hassani</option>
<option value="zerktouni">Zerktouni</option>