<option value="abi_rekrak">Abi Rekrak</option>
<option value="agdal_bas_(av._de_france_av_de_la_victoire)">Agdal Bas (Av. De France- Av, De La Victoire)</option>
<option value="agdal_haut_(avenue_de_france_av_ibn_roch)">Agdal Haut (Avenue De France- Av, Ibn Roch)</option>
<option value="ain_khallouia">Ain Khallouia</option>
<option value="akkari">Akkari</option>
<option value="al_farah">Al Farah</option>
<option value="al_inbiat">Al Inbiat</option>
<option value="al_wahda">Al Wahda</option>
<option value="amal">Amal</option>
<option value="amal_1">Amal 1</option>
<option value="amal_2">Amal 2</option>
<option value="amal_3">Amal 3</option>
<option value="amal_4">Amal 4</option>
<option value="amal_5">Amal 5</option>
<option value="amal_6">Amal 6</option>
<option value="ancienne_medina">Ancienne Médina</option>
<option value="av._allal_ben_abdellah">Av. Allal Ben Abdellah</option>
<option value="av._bouregreg">Av. Bouregreg</option>
<option value="avenue_fes_et_tarek_ibn_zyad">Avenue Fès et Tarek Ibn Zyad</option>
<option value="aviation">Aviation</option>
<option value="bd._mohamed_v">Bd. Mohamed V</option>
<option value="bir_kacem">Bir Kacem</option>
<option value="bouhlal">Bouhlal</option>
<option value="bouitate">Bouitate</option>
<option value="centre_ville">Centre Ville</option>
<option value="cite_administrative">Cité Administrative</option>
<option value="cite_foch">Cité Foch</option>
<option value="cite_olm">Cité Olm</option>
<option value="cite_yaacoub_al_mansour">Cite Yaacoub Al Mansour</option>
<option value="cym">Cym</option>
<option value="dar_essalam">Dar Essalam</option>
<option value="diour_jamaa">Diour Jamaa</option>
<option value="douar_rja_fellah">Douar Rja Fellah</option>
<option value="el_menzeh">El Menzeh</option>
<option value="el_mouadda">El Mouadda</option>
<option value="el_oufir">El Oufir</option>
<option value="ennahda">Ennahda</option>
<option value="ennahda_i">Ennahda I</option>
<option value="ennahda_ii">Ennahda II</option>
<option value="ennahda_iii">Ennahda III</option>
<option value="errachad">Errachad</option>
<option value="essabah">Essabah</option>
<option value="fadesa">Fadesa</option>
<option value="guich_loudaya">Guich Loudaya</option>
<option value="haj_kacem">Haj Kacem</option>
<option value="haj_slimane">Haj Slimane</option>
<option value="hassan">Hassan</option>
<option value="hay_el_fath">Hay El Fath</option>
<option value="hay_el_kheir">Hay El Kheir</option>
<option value="immeuble_karrakchou">Immeuble Karrakchou</option>
<option value="j5">J5</option>
<option value="kamra_nord">Kamra Nord</option>
<option value="kamra_sud">Kamra Sud</option>
<option value="karyoune">Karyoune</option>
<option value="kasbat_oudaya">Kasbat Oudaya</option>
<option value="kebibat">Kebibat</option>
<option value="kouass">Kouass</option>
<option value="ksar_labhar">Ksar Labhar</option>
<option value="la_cigogne">La Cigogne</option>
<option value="la_corniche">La Corniche</option>
<option value="laalou">Laalou</option>
<option value="lagza">Lagza</option>
<option value="les_ambassadeurs">Les Ambassadeurs</option>
<option value="les_orangers">Les Orangers</option>
<option value="lot_tazi">Lot Tazi</option>
<option value="mabilla">Mabilla</option>
<option value="marassa_saniat_gharbia">Marassa Saniat Gharbia</option>
<option value="massira">Massira</option>
<option value="mechouar">Mechouar</option>
<option value="medina">Medina</option>
<option value="mellah">Mellah</option>
<option value="mountalak">Mountalak</option>
<option value="mountazah">Mountazah</option>
<option value="ocean">Océan</option>
<option value="olm">Olm</option>
<option value="oum_kalthoum">Oum Kalthoum</option>
<option value="place_abdellah_chefchaouni">Place Abdellah Chefchaouni</option>
<option value="place_abraham_lincon">Place Abraham Lincon</option>
<option value="place_al_barid">Place Al Barid</option>
<option value="place_al_joulane">Place Al Joulane</option>
<option value="place_al_ouahda_al_ifriquia">Place Al Ouahda Al Ifriquia</option>
<option value="place_bab_tamesna">Place Bab Tamesna</option>
<option value="place_bruxelles">Place Bruxelles</option>
<option value="place_pi_et_ri">Place Pi et ri</option>
<option value="quartier_industriel">Quartier Industriel</option>
<option value="route_casablanca">Route Casablanca</option>
<option value="ryad_bas_(av_jacaranda_av._ibn_rochd)">Ryad Bas (Av, Jacaranda- Av. Ibn Rochd)</option>
<option value="ryad_haut_(av_jacaranda_autoroute_casa_fes)">Ryad Haut (Av, Jacaranda- Autoroute Casa-Fès)</option>
<option value="sahat_al_alaouine">Sahat Al Alaouine</option>
<option value="secteur_1">Secteur 1</option>
<option value="secteur_10">Secteur 10</option>
<option value="secteur_11">Secteur 11</option>
<option value="secteur_12">Secteur 12</option>
<option value="secteur_13">Secteur 13</option>
<option value="secteur_14">Secteur 14</option>
<option value="secteur_15">Secteur 15</option>
<option value="secteur_16">Secteur 16</option>
<option value="secteur_17">Secteur 17</option>
<option value="secteur_18">Secteur 18</option>
<option value="secteur_19">Secteur 19</option>
<option value="secteur_2">Secteur 2</option>
<option value="secteur_20">Secteur 20</option>
<option value="secteur_21">Secteur 21</option>
<option value="secteur_22">Secteur 22</option>
<option value="secteur_23">Secteur 23</option>
<option value="secteur_24">Secteur 24</option>
<option value="secteur_25">Secteur 25</option>
<option value="secteur_3">Secteur 3</option>
<option value="secteur_4">Secteur 4</option>
<option value="secteur_5">Secteur 5</option>
<option value="secteur_6">Secteur 6</option>
<option value="secteur_7">Secteur 7</option>
<option value="secteur_8">Secteur 8</option>
<option value="secteur_9">Secteur 9</option>
<option value="sidi_fateh">Sidi Fateh</option>
<option value="souika">Souika</option>
<option value="souissi">Souissi</option>
<option value="takaddoum">Takaddoum</option>
<option value="youssoufia">Youssoufia</option>
<option value="youssoufia_est">Youssoufia Est</option>
<option value="youssoufia_ouest">Youssoufia Ouest</option>