<option value="abc">Abc</option>
<option value="achbar">Achbar</option>
<option value="allal_ben_abdellah">Allal Ben Abdellah</option>
<option value="amouni">Amouni</option>
<option value="anas">Anas</option>
<option value="annahda">Annahda</option>
<option value="assalam">Assalam</option>
<option value="lot_aviation">Lot Aviation</option>
<option value="azib_drai">Azib Drai</option>
<option value="azib_zemouri">Azib Zemouri</option>
<option value="bd_my_youssef">Bd My Youssef</option>
<option value="bennis">Bennis</option>
<option value="biyada">Biyada</option>
<option value="lot_bled_jad">Lot Bled Jad</option>
<option value="boualam">Boualam</option>
<option value="castor">Castor</option>
<option value="chankit">Chankit</option>
<option value="cooperative_3_mars">Cooperative 3 Mars</option>
<option value="course">Course</option>
<option value="dabra">Dabra</option>
<option value="dar_bouaaoud">Dar Bouaaoud</option>
<option value="derb_my_el_hassan">Derb My El Hassan</option>
<option value="douar_essafa">Douar Essafa</option>
<option value="el_bahia">El Bahia</option>
<option value="el_majd">El Majd</option>
<option value="el_massira">El Massira</option>
<option value="essaada">Essaada</option>
<option value="quartierjrifate">QuartierJrifate</option>
<option value="habitat_d_urgence">Habitat D'urgence</option>
<option value="habitat_europeen">Habitat Europeen</option>
<option value="habitat_municipal">Habitat Municipal</option>
<option value="hay_bouab">Hay Bouab</option>
<option value="hay_hrait_bied">Hay Hrait Bied</option>
<option value="hay_mohammadi">Hay Mohammadi</option>
<option value="hay_rabat">Hay Rabat</option>
<option value="hay_riad">Hay Riad</option>
<option value="hay_salam">Hay Salam</option>
<option value="hay_trab_sini">Hay Trab Sini</option>
<option value="hōpital">Hōpital</option>
<option value="ijnnane">Ijnnane</option>
<option value="jenane_alane">Jenane Alane</option>
<option value="jenane_chakouri">Jenane Chakouri</option>
<option value="jenane_colonne_2">Jenane Colonne 2</option>
<option value="jrifat">Jrifat</option>
<option value="kachla_lkdima">Kachla Lkdima</option>
<option value="kaouki">Kaouki</option>
<option value="kariat_chems_loulya">Kariat Chems Loulya</option>
<option value="kariat_chems_soufla">Kariat Chems Soufla</option>
<option value="karyane_harouss">Karyane Harouss</option>
<option value="kliaa_sidi_ouassel_i">Kliaa Sidi Ouassel I</option>
<option value="kliaat_jrifat">Kliaat Jrifat</option>
<option value="quartier_laarisa">Quartier Laarisa</option>
<option value="lalla_aicha">Lalla Aicha</option>
<option value="lalla_asmaa">Lalla Asmaa</option>
<option value="lalla_hnia_hamria">Lalla Hnia Hamria</option>
<option value="lamyaa">Lamyaa</option>
<option value="laourini_1_et_2">Laourini 1 et 2</option>
<option value="lghdir_bourssass">Lghdir-Bourssass</option>
<option value="libiar">Libiar</option>
<option value="quartier_kliaa">Quartier Kliaa</option>
<option value="log_des_fonctionnaires_(108)">Log Des Fonctionnaires (108)</option>
<option value="lot_chifa">Lot Chifa</option>
<option value="lot_doukala">Lot Doukala</option>
<option value="lot_ghita">Lot Ghita</option>
<option value="lot_lourd">Lot Lourd</option>
<option value="lot_qods">Lot Qods</option>
<option value="lot_zitouna">Lot Zitouna</option>
<option value="medina_jdida">Medina Jdida</option>
<option value="medina_kdima">Medina Kdima</option>
<option value="miftah_elkhir">Miftah Elkhir</option>
<option value="mouna">Mouna</option>
<option value="najah_al_amir">Najah Al Amir</option>
<option value="okba_bni_nafii">Okba Bni Nafii</option>
<option value="oued_el_bacha">Oued El Bacha</option>
<option value="oumnia">Oumnia</option>
<option value="ourida_1">Ourida 1</option>
<option value="ourida_2">Ourida 2</option>
<option value="place_de_l_independance">Place De L'independance</option>
<option value="plateau">Plateau</option>
<option value="port">Port</option>
<option value="qods">Qods</option>
<option value="quartier_industriel">Quartier Industriel</option>
<option value="quodia_bayda">Quodia Bayda</option>
<option value="rahat_rih">Rahat Rih</option>
<option value="safi_1">Safi 1</option>
<option value="safi_3">Safi 3</option>
<option value="safi2">Safi2</option>
<option value="saida_1">Saida 1</option>
<option value="saida_2">Saida 2</option>
<option value="sana_1_et_2">Sana 1 et 2</option>
<option value="sania_jemra">Sania Jemra</option>
<option value="sania_lhamri">Sania Lhamri</option>
<option value="sania_zine_abbidine">Sania Zine Abbidine</option>
<option value="sidi_abdelkrim">Sidi Abdelkrim</option>
<option value="sidi_abdelkrim+jenane_colonne_2">Sidi Abdelkrim+Jenane Colonne 2</option>
<option value="sidi_boudhab">Sidi Boudhab</option>
<option value="sidi_bouzid">Sidi Bouzid</option>
<option value="sidi_ouassel_ii">Sidi Ouassel II</option>
<option value="smis_triki">Smis Triki</option>
<option value="takabrout">Takabrout</option>
<option value="tanguer">Tanguer</option>
<option value="tarik_jorf_lihoudi">Tarik Jorf Lihoudi</option>
<option value="tikhribinte">Tikhribinte</option>
<option value="village_espagnol">Village Espagnol</option>
<option value="village_taybi">Village Taybi</option>
<option value="wiaam">Wiaam</option>
<option value="zaouiat_sidi_ouassel">Zaouiat Sidi Ouassel</option>
<option value="zine_abbidine">Zine Abbidine</option>
<option value="zouhour">Zouhour</option>