<option value="11_janvier">43111</option>
<option value="albouchra">Albouchra</option>
<option value="allee_chenguit">Allee Chenguit</option>
<option value="allee_jbel_angour">Allee Jbel Angour</option>
<option value="allee_jbel_arzoul">Allee Jbel Arzoul</option>
<option value="allee_jbel_el_ayyachi">Allee Jbel El Ayyachi</option>
<option value="allee_jbel_hibri">Allee Jbel Hibri</option>
<option value="allee_jbel_saghrou">Allee Jbel Saghrou</option>
<option value="allee_jbel_siroua">Allee Jbel Siroua</option>
<option value="allee_jbel_tizintichka">Allee Jbel Tizintichka</option>
<option value="allee_jbel_zerhoun">Allee Jbel Zerhoun</option>
<option value="allee_jebel_toubkal">Allee Jebel Toubkal</option>
<option value="allee_laayoune">Allee Laayoune</option>
<option value="allee_marrakech">Allee Marrakech</option>
<option value="allee_meknes">Allee Meknes</option>
<option value="allee_nouakchout">Allee Nouakchout</option>
<option value="allee_rabat">Allee Rabat</option>
<option value="avenue_2_mars">Avenue 2 Mars</option>
<option value="avenue_abderrahim_bouabid">Avenue Abderrahim Bouabid</option>
<option value="avenue_ain_aouda">Avenue Ain Aouda</option>
<option value="avenue_al_masira_al_khadra">Avenue Al Masira Al Khadra</option>
<option value="avenue_al_ourouba">Avenue Al Ourouba</option>
<option value="avenue_al_wahda">Avenue Al Wahda</option>
<option value="avenue_bed_bel_hassan_elouzzani">Avenue Bed Bel Hassan Elouzzani</option>
<option value="avenue_benguerir">Avenue Benguerir</option>
<option value="avenue_bouregureg">Avenue Bouregureg</option>
<option value="avenue_hassan_ii">Avenue Hassan II</option>
<option value="avenue_ibn_al_haitam">Avenue Ibn Al Haitam</option>
<option value="avenue_lalla_asmae">Avenue Lalla Asmae</option>
<option value="avenue_lalla_meriem">Avenue Lalla Meriem</option>
<option value="avenue_mohamed_v">Avenue Mohamed V</option>
<option value="avenue_moulay_youssef">Avenue Moulay Youssef</option>
<option value="avenue_oued_erromane">Avenue Oued Erromane</option>
<option value="avenue_said_hajji">Avenue Said Hajji</option>
<option value="avenue_sakia_el_hamra">Avenue Sakia El Hamra</option>
<option value="bab_bouhaja">Bab Bouhaja</option>
<option value="bab_chaafa">Bab Chaafa</option>
<option value="bab_hsain">Bab Hsain</option>
<option value="bab_sebta">Bab Sebta</option>
<option value="bayti_1_2_3_4_5">Bayti 1-2-3-4-5</option>
<option value="b_et_tana">B et tana</option>
<option value="bled_abdelmoula">Bled Abdelmoula</option>
<option value="bled_belaroussi">Bled Belaroussi</option>
<option value="bled_belbaraka">Bled Belbaraka</option>
<option value="bled_benachir">Bled Benachir</option>
<option value="bled_bendaoued_dar_el_hamra">Bled Bendaoued Dar El Hamra</option>
<option value="bled_bensaid">Bled Bensaid</option>
<option value="bled_el_gharbi">Bled El Gharbi</option>
<option value="bled_el_haj_el_guezzar">Bled El Haj El Guezzar</option>
<option value="bled_fabi">Bled Fabi</option>
<option value="bled_largo">Bled Largo</option>
<option value="bled_sbihi">Bled Sbihi</option>
<option value="bled_zniber">Bled Zniber</option>
<option value="blida">Blida</option>
<option value="boutouil">Boutouil</option>
<option value="cheikh_lamfaddal">Cheikh Lamfaddal</option>
<option value="chellaline">Chellaline</option>
<option value="desserte_rurale">Desserte Rurale</option>
<option value="diar_1_et_2">Diar 1 et 2</option>
<option value="diar_3">Diar 3</option>
<option value="diour_annajjar">Diour Annajjar</option>
<option value="douar_benmessaoud">Douar Benmessaoud</option>
<option value="douar_essahli">Douar Essahli</option>
<option value="douar_lhaj_mohamed_touil">Douar Lhaj Mohamed Touil</option>
<option value="dour_lamkhaznia">Dour Lamkhaznia</option>
<option value="eddoha_2">Eddoha 2</option>
<option value="ejnane">Ejnane</option>
<option value="el_ayyadia">El Ayyadia</option>
<option value="el_hammam_jdid">El Hammam Jdid</option>
<option value="el_harrarine">El Harrarine</option>
<option value="el_kharrouba">El Kharrouba</option>
<option value="el_mamounia">El Mamounia</option>
<option value="el_mkinssia">El Mkinssia</option>
<option value="essmahia">Essmahia</option>
<option value="hammam_chekaoui">Hammam Chekaoui</option>
<option value="hay_al_andalous">Hay Al Andalous</option>
<option value="hay_chemaou">Hay Chemaou</option>
<option value="hay_el_amal">Hay El Amal</option>
<option value="hay_el_hourria">Hay El Hourria</option>
<option value="hay_el_kifah_1_et_2">Hay El Kifah 1 et 2</option>
<option value="hay_el_mouhammadi">Hay El Mouhammadi</option>
<option value="hay_el_qods">Hay El Qods</option>
<option value="hay_el_wahda">Hay El Wahda</option>
<option value="hay_ennahda">Hay Ennahda</option>
<option value="hay_ennasr">Hay Ennasr</option>
<option value="hay_errahma">Hay Errahma</option>
<option value="hay_essafae">Hay Essafae</option>
<option value="hay_essalam">Hay Essalam</option>
<option value="hay_inbiaat">Hay Inbiaat</option>
<option value="hay_karima">Hay Karima</option>
<option value="hay_lafrougui">Hay Lafrougui</option>
<option value="hay_lalla_aicha">Hay Lalla Aicha</option>
<option value="hay_linbiat_charkia">Hay Linbiat Charkia</option>
<option value="hay_mohammad_alkamis">Hay Mohammad Alkamis</option>
<option value="hay_moulay_abdellah">Hay Moulay Abdellah</option>
<option value="hay_moulay_ismail">Hay Moulay Ismail</option>
<option value="hay_oued_eddahab">Hay Oued Eddahab</option>
<option value="hay_rizq">Hay Rizq</option>
<option value="hors_bab_chaafa">Hors Bab Chaafa</option>
<option value="hors_bab_sebta">Hors Bab Sebta</option>
<option value="hors_lakouass">Hors Lakouass</option>
<option value="immeubles_des_enseignants">Immeubles Des Enseignants</option>
<option value="immeubles_touargua">Immeubles Touargua</option>
<option value="kardouna">Kardouna</option>
<option value="kariat_oulad_moussa_ouest">Kariat Oulad Moussa Ouest</option>
<option value="la_cigogne">La Cigogne</option>
<option value="longeville">Longeville</option>
<option value="lot_al_mahatta">Lot Al Mahatta</option>
<option value="lot_annassim">Lot Annassim</option>
<option value="lot_arguana">Lot Arguana</option>
<option value="lot_assia">Lot Assia</option>
<option value="lot_bachir_2">Lot Bachir 2</option>
<option value="lot_bendahmane">Lot Bendahmane</option>
<option value="lot_bouregureg">Lot Bouregureg</option>
<option value="lot_cherkaoui">Lot Cherkaoui</option>
<option value="lot_el_amal">Lot El Amal</option>
<option value="lot_el_koumir">Lot El Koumir</option>
<option value="lot_el_mountazah">Lot El Mountazah</option>
<option value="lot_el_wafae">Lot El Wafae</option>
<option value="lot_lalla_meriem">Lot Lalla Meriem</option>
<option value="lot_lilys">Lot Lilys</option>
<option value="lot_marrakchi">Lot Marrakchi</option>
<option value="lot_oued_eddahab">Lot Oued Eddahab</option>
<option value="lot_oum_el_kheir">Lot Oum El Kheir</option>
<option value="lot_safa_2">Lot Safa 2</option>
<option value="lot_said_hajji">Lot Said Hajji</option>
<option value="lot_yousra_et_zarka">Lot Yousra et Zarka</option>
<option value="lot_zanfari">Lot Zanfari</option>
<option value="medina">Medina</option>
<option value="mellah">Mellah</option>
<option value="omar_2">Omar 2</option>
<option value="oued_eddahab">Oued Eddahab</option>
<option value="oulad_moussa_est">Oulad Moussa Est</option>
<option value="pepinnieres">Pepinnieres</option>
<option value="place_du_marche">Place Du Marche'</option>
<option value="quartier_al_wafae">Quartier Al Wafae</option>
<option value="quartier_de_la_base_aerienne">Quartier De La Base Aerienne</option>
<option value="quartier_el_baraka_1">Quartier El Baraka 1</option>
<option value="quartier_el_baraka_2">Quartier El Baraka 2</option>
<option value="quartier_el_farah">Quartier El Farah</option>
<option value="quartier_el_haouat">Quartier El Haouat</option>
<option value="quartier_el_wafae">Quartier El Wafae</option>
<option value="quartier_errachad">Quartier Errachad</option>
<option value="quartier_industriel">Quartier Industriel</option>
<option value="quartier_industriel_deroutekenitra">Quartier Industriel DeRouteKenitra</option>
<option value="ras_el_mae">Ras El Mae</option>
<option value="residence_al_bassatine">Residence Al Bassatine</option>
<option value="residence_al_farah">Residence Al Farah</option>
<option value="residence_al_kheir_(addoha)">Residence Al Kheir (Addoha)</option>
<option value="residence_annakhil">Residence Annakhil</option>
<option value="residence_bab_sala">Residence Bab Sala</option>
<option value="residence_belle_vue">Residence Belle Vue</option>
<option value="residence_des_enseignants">Residence Des Enseignants</option>
<option value="residence_naila">Residence Naila</option>
<option value="riad_sala">Riad Sala</option>
<option value="rmel">Rmel</option>
<option value="roustal">Roustal</option>
<option value="route_de_kenitra_said_hajji">Route De Kenitra - Said Hajji</option>
<option value="route_oulad_hlal">Route Oulad Hlal</option>
<option value="rue_kartage">Rue Kartage</option>
<option value="rue_nouadibou">Rue Nouadibou</option>
<option value="rue_sfax">Rue Sfax</option>
<option value="rue_soussa">Rue Soussa</option>
<option value="saf">Saf</option>
<option value="sala_aljadida_1">Sala Aljadida 1</option>
<option value="sala_aljadida_2">Sala Aljadida 2</option>
<option value="saniat_bouchaara_2">Saniat Bouchaara 2</option>
<option value="saniat_el_ghrablia">Saniat El Ghrablia</option>
<option value="saniat_el_haj_el_maati">Saniat El Haj El Maati</option>
<option value="saniat_el_mansouri">Saniat El Mansouri</option>
<option value="saniat_hammani">Saniat Hammani</option>
<option value="saniat_talbi">Saniat Talbi</option>
<option value="secteur_11_et12">Secteur 11 et12</option>
<option value="secteur_11_extension">Secteur 11 Extension</option>
<option value="secteur_12_extension">Secteur 12 Extension</option>
<option value="secteur_5_et_6">Secteur 5 et 6</option>
<option value="secteur_al_ouiame">Secteur Al Ouiame</option>
<option value="secteur_alqods">Secteur Alqods</option>
<option value="secteur_b_4">Secteur B 4</option>
<option value="secteur_c4">Secteur C4</option>
<option value="secteur_d_4">Secteur D 4</option>
<option value="secteur_e">Secteur E</option>
<option value="secteur_f">Secteur F</option>
<option value="secteurs_1_2_3_et_4">Secteurs 1-2-3- et 4</option>
<option value="secteurs_7_8_9_et_10">Secteurs 7-8-9 et 10</option>
<option value="secteurs_a_b_e">Secteurs A - B -E</option>
<option value="secteurs_c_d">Secteurs C- D</option>
<option value="sidi_abdellah">Sidi Abdellah</option>
<option value="sidi_idder">Sidi Idder</option>
<option value="sidi_moussa">Sidi Moussa</option>
<option value="souk_laghzel">Souk Laghzel</option>
<option value="souk_lakbir">Souk Lakbir</option>
<option value="tabriqu_et_1">Tabriqu et 1</option>
<option value="tabriqu_et_2">Tabriqu et 2</option>
<option value="talbia">Talbia</option>
<option value="zanata">Zanata</option>
<option value="zone_villas_de_1_a_1234">Zone Villas De 1 A 1234</option>
<option value="zones_a_b_c_d_e">Zones A-B-C-D-E</option>
<option value="zones_f_g_h_o_p_n">Zones F-G-H-O-P-N</option>
<option value="zones_k_j_t_f_r_v_w1_ml">Zones K -J-T-F-R-V-W1-Ml</option>