<option value="aazib_haj_kadour">Aazib Haj Kadour</option>
<option value="agence_de_bni_makada">Agence De Bni Makada</option>
<option value="ain_ktiou_et">Ain Ktiou et</option>
<option value="al_aouama">Al Aouama</option>
<option value="al_hafa">Al Hafa</option>
<option value="ancienne_medina">Ancienne Medina</option>
<option value="ancienne_route_de_l_aeroport">Ancienne Route De L'aeroport</option>
<option value="avenue_goutemberg">Avenue Goutemberg</option>
<option value="avenue_la_marche_verte">Avenue La Marche Verte</option>
<option value="avenue_mexique">Avenue Mexique</option>
<option value="avenue_moulay_rachid">Avenue Moulay Rachid</option>
<option value="avenue_moulay_youssef">Avenue Moulay Youssef</option>
<option value="avenue_moussa_bnou_nouceir">Avenue Moussa Bnou Nouceir</option>
<option value="avenue_prince_heritier">Avenue Prince Heritier</option>
<option value="bd._allal_bnou_abdellah">Bd. Allal Bnou Abdellah</option>
<option value="bd._de_pasteur">Bd. De Pasteur</option>
<option value="bd._hassani">Bd. HassanI</option>
<option value="bd._hassan_ii">Bd. Hassan II</option>
<option value="bd._la_resistance">Bd. La Resistance</option>
<option value="bd._mohamd_v">Bd. Mohamd V</option>
<option value="bd._moulay_ismail">Bd. Moulay Ismail</option>
<option value="ben_dibane">Ben Dibane</option>
<option value="branesse_i_et_ii">Branesse I et II</option>
<option value="castilla">Castilla</option>
<option value="centre_ville">Centre Ville</option>
<option value="collegio_internado">Collegio Internado</option>
<option value="complexe_hassani">Complexe Hassani</option>
<option value="dar_baroud">Dar Baroud</option>
<option value="dradeb">Dradeb</option>
<option value="esidence_zemouri">Esidence Zemouri</option>
<option value="gare_de_tanger">Gare De Tanger</option>
<option value="gzenaya">Gzenaya</option>
<option value="haoumat_bni_yder">Haoumat Bni Yder</option>
<option value="hay_jadid">Hay Jadid</option>
<option value="houmate_espagnol">Houmate Espagnol</option>
<option value="jamaa_moukraa">Jamaa Moukraa</option>
<option value="jbel_lekbir">Jbel Lekbir</option>
<option value="jnan_kabtane">Jnan Kabtane</option>
<option value="khoussafat">Khoussafat</option>
<option value="lala_chafia">Lala Chafia</option>
<option value="lot_boussouf">Lot Boussouf</option>
<option value="lot_massira">Lot Massira</option>
<option value="lot_saada">Lot Saada</option>
<option value="mahaj_mohamedvi">Mahaj MohamedVi</option>
<option value="marbel">Marbel</option>
<option value="merchane">Merchane</option>
<option value="mesnana">Mesnana</option>
<option value="mester_khouch">Mester Khouch</option>
<option value="quartier_al_moujahidine">Quartier Al Moujahidine</option>
<option value="msallah">Msallah</option>
<option value="place_9_avril">Place 9 Avril</option>
<option value="place_al_madina">Place Al Madina</option>
<option value="place_de_france">Place De France</option>
<option value="place_mozart">Place Mozart</option>
<option value="place_omman">Place Omman</option>
<option value="place_roudani">Place Roudani</option>
<option value="quartier_abdellatif">Quartier Abdellatif</option>
<option value="quartier_administartif">Quartier Administartif</option>
<option value="quartier_ain_hayani">Quartier Ain Hayani</option>
<option value="quartier_al_majd">Quartier Al Majd</option>
<option value="quartier_ali_bay">Quartier Ali Bay</option>
<option value="quartier_alia">Quartier Alia</option>
<option value="quartier_ard_bouhssein">Quartier Ard Bouhssein</option>
<option value="ard_daoula_bani_makada">Ard Daoula Bani Makada</option>
<option value="quartier_azibou">Quartier Azibou</option>
<option value="quartier_belle_vue">Quartier Belle Vue</option>
<option value="quartier_ben_kirane">Quartier Ben Kirane</option>
<option value="quartier_berouaka">Quartier Berouaka</option>
<option value="quartier_bir_aharchoun">Quartier Bir Aharchoun</option>
<option value="quartier_bir_chaeri">Quartier Bir Chaeri</option>
<option value="quartier_bir_chifa">Quartier Bir Chifa</option>
<option value="quartier_bni_makada">Quartier Bni Makada</option>
<option value="quartier_bni_makada_kdima">Quartier Bni Makada Kdima</option>
<option value="quartier_bnou_khaldoune">Quartier Bnou Khaldoune</option>
<option value="quartier_boughaz">Quartier Boughaz</option>
<option value="quartier_bouhoute_saada">Quartier Bouhoute Saada</option>
<option value="quartier_charf">Quartier Charf</option>
<option value="quartier_chat">Quartier Chat</option>
<option value="quartier_chouhada">Quartier Chouhada</option>
<option value="quartier_dhar_lehmam">Quartier Dhar Lehmam</option>
<option value="quartier_dorilla">Quartier Dorilla</option>
<option value="quartier_dradeb">Quartier Dradeb</option>
<option value="quartier_drissia_i">Quartier Drissia I</option>
<option value="quartier_drissia_ii">Quartier Drissia II</option>
<option value="quartier_el_oued">Quartier El Oued</option>
<option value="quartier_fatima_zohra">Quartier Fatima Zohra</option>
<option value="quartier_florencia">Quartier Florencia</option>
<option value="quartier_habiba">Quartier Habiba</option>
<option value="quartier_haj_mokhtar">Quartier Haj Mokhtar</option>
<option value="quartier_haoumat_12">Quartier Haoumat 12</option>
<option value="quartier_hassania">Quartier Hassania</option>
<option value="quartier_ibour">Quartier Ibour</option>
<option value="quartier_koucha">Quartier Koucha</option>
<option value="quartier_laachiri">Quartier Laachiri</option>
<option value="quartier_las_collinas">Quartier Las Collinas</option>
<option value="quartier_lehbouss">Quartier Lehbouss</option>
<option value="quartier_mabrouk">Quartier Mabrouk</option>
<option value="quartier_mabrouka">Quartier Mabrouka</option>
<option value="quartier_moh_paco">Quartier Moh Paco</option>
<option value="quartier_mrab_et">Quartier Mrab et</option>
<option value="quartier_nasr">Quartier Nasr</option>
<option value="quartier_nzaha">Quartier Nzaha</option>
<option value="quartier_ouahabi_zemmouri">Quartier Ouahabi - Zemmouri</option>
<option value="quartier_rgayae">Quartier Rgayae</option>
<option value="quartier_roudani">Quartier Roudani</option>
<option value="quartier_rouida">Quartier Rouida</option>
<option value="quartier_saada_i_ii_iii_iv_v">Quartier Saada I-II-III-IV-V</option>
<option value="quartier_safif">Quartier Safif</option>
<option value="quartier_salima">Quartier Salima</option>
<option value="quartier_sanaa_iii">Quartier Sanaa III</option>
<option value="quartier_sanae_ii">Quartier Sanae II</option>
<option value="quartier_sidi_boukhari">Quartier Sidi Boukhari</option>
<option value="quartier_souk_lebkar">Quartier Souk Lebkar</option>
<option value="quartier_souryenne">Quartier Souryenne</option>
<option value="quartier_warda">Quartier Warda</option>
<option value="quartier_zahara">Quartier Zahara</option>
<option value="quartier_zaoudia">Quartier Zaoudia</option>
<option value="route_boukhalef_(universite_abdelmalek_saadi)">Route Boukhalef (Université Abdelmalek Saadi)</option>
<option value="route_de_rabat">Route De Rabat</option>
<option value="route_de_tetouan">Route De Tétouan</option>
<option value="route_malabata">Route Malabata</option>
<option value="route_rmilat">Route Rmilat</option>
<option value="siaghine">Siaghine</option>
<option value="sidi_bouabid">Sidi Bouabid</option>
<option value="souanii_ii_iii_iv_v">SouaniI -II-III -IV - V</option>
<option value="souk_dakhel">Souk Dakhel</option>
<option value="tanger_al_majd">Tanger Al Majd</option>
<option value="tanger_zone_franche">Tanger Zone Franche</option>
<option value="tanja_balia">Tanja Balia</option>
<option value="val_fleuri">Val Fleuri</option>
<option value="zone_industrielle_al_majd">Zone Industrielle Al Majd</option>
<option value="zone_industrielle_de_mghogha">Zone Industrielle De Mghogha</option>
<option value="zone_industrielle_gzenaya">Zone Industrielle Gzenaya</option>
<option value="quartier_al_hanae_i_ii_iii">Quartier Al Hanae I, II,III</option>
<option value="lot_zemmouri">Lot Zemmouri</option>
<option value="lot_al_andalous">Lot Al Andalous</option>
<option value="lot_moubaraka">Lot Moubaraka</option>
<option value="quartier_salam">Quartier Salam</option>
<option value="lot_ikama">Lot Ikama</option>
<option value="lot_miramar">Lot Miramar</option>
<option value="lot_tingis">Lot Tingis</option>
<option value="lot_dhar_lmers">Lot Dhar Lmers</option>
<option value="lot_ratma">Lot Ratma</option>
<option value="quartier_bir_el_mokrae">Quartier Bir El Mokrae</option>
<option value="lot_ain_arouj">Lot Ain Arouj</option>
<option value="lot_chateau">Lot Chateau</option>
<option value="lot_belle_vue">Lot Belle Vue</option>
<option value="lot_arimas">Lot Arimas</option>
<option value="lot_facinta">Lot Facinta</option>
<option value="lot_oumnia">Lot Oumnia</option>
<option value="lot_lbhayar">Lot Lbhayar</option>
<option value="quartier_gharssat_lahgilat">Quartier Gharssat Lahgilat</option>
<option value="quartier_al_inache">Quartier Al Inache</option>
<option value="lot_al_bassatine">Lot Al Bassatine</option>
<option value="complexe_slimani_(nejma)">Complexe Slimani (Nejma)</option>
<option value="lot_bassou">Lot Bassou</option>
<option value="lot_banamaribo">Lot Banamaribo</option>
<option value="lot_mouna">Lot Mouna</option>
<option value="lot_rizk">Lot Rizk</option>
<option value="lot_oumkaltoum">Lot Oumkaltoum</option>
<option value="quartier_laadaoui">Quartier Laadaoui</option>
<option value="lot_pintoriska">Lot Pintoriska</option>
<option value="quartier_rosa_i_ii_iii">Quartier Rosa I, II, III</option>
<option value="quartier_california">Quartier California</option>
<option value="lot_charouit">Lot Charouit</option>
<option value="lot_altamira">Lot Altamira</option>
<option value="lot_benazaiz">Lot Benazaiz</option>
<option value="lot_el_fellah">Lot El Fellah</option>
<option value="lot_ribh">Lot Ribh</option>
<option value="lot_colorado">Lot Colorado</option>
<option value="quartier_mtafi">Quartier Mtafi</option>
<option value="lot_omrana">Lot Omrana</option>
<option value="place_aharar">Place Aharar</option>
<option value="quartier_ben_aliem">Quartier Ben Aliem</option>
<option value="place_el_massira_al_khadra">Place El Massira Al Khadra</option>
<option value="port_de_tanger">Port De Tanger</option>
<option value="quartier_ibn_batouta">Quartier Ibn Batouta</option>
<option value="lot_sanaoubar">Lot Sanaoubar</option>
<option value="lot_chicavila">Lot Chicavila</option>
<option value="lot_kadiria">Lot Kadiria</option>
<option value="quartier_amrah_chlouh">Quartier Amrah Chlouh</option>
<option value="route_de_la_montagne">Route De La Montagne</option>
<option value="lot_flandria">Lot Flandria</option>
<option value="quartier_messouda">Quartier Messouda</option>
<option value="quartier_draoua">Quartier Draoua</option>
<option value="quartier_kssaibi">Quartier Kssaibi</option>
<option value="quartier_belair">Quartier Belair</option>
<option value="quartier_slimani">Quartier Slimani</option>
<option value="quartier_pariente">Quartier Pariente</option>
<option value="quartier_najiba">Quartier Najiba</option>
<option value="lot_alou_et_te">Lot Alou et te</option>
<option value="complexe_amin">Complexe Amin</option>
<option value="ard_daoula_ben_dibane">Ard Daoula Ben Dibane</option>
<option value="quartier_topo_rabat">Quartier Topo Rabat</option>
<option value="quartier_bella_vista">Quartier Bella Vista</option>
<option value="quartier_industriel_mghogha_sghira">Quartier Industriel Mghogha Sghira</option>
<option value="quartier_jamaa">Quartier Jamaa</option>
<option value="lot_fadila">Lot Fadila</option>
<option value="lot_riad">Lot Riad</option>
<option value="quartier_illalif">Quartier Illalif</option>
<option value="quartier_beausejour">Quartier Beausejour</option>
<option value="quartier_abouri">Quartier Abouri</option>
<option value="lot_karima">Lot Karima</option>
<option value="quartier_bouhoute_drissia">Quartier Bouhoute Drissia</option>
<option value="complexe_habiba">Complexe Habiba</option>
<option value="lot_nahda">Lot Nahda</option>
<option value="complexe_ibn_batouta">Complexe Ibn Batouta</option>
<option value="lot_doha">Lot Doha</option>
<option value="quartier_mghogha_kbira">Quartier Mghogha Kbira</option>
<option value="quartiermghogha_sghira">Quartiermghogha Sghira</option>
<option value="quartier_mghogha_el_jadida">Quartier Mghogha El Jadida</option>
<option value="quartier_ain_jdid">Quartier Ain Jdid</option>
<option value="quartier_mghogha_tabchicha">Quartier Mghogha Tabchicha</option>
<option value="lot_zegoutia">Lot Zegoutia</option>
<option value="quartier_zoufri">Quartier Zoufri</option>
<option value="lot_jamila_jin_et">Lot Jamila Jin et</option>
<option value="lot_achouba">Lot Achouba</option>
<option value="lot_nahda_i_ii">Lot Nahda I, II</option>
<option value="lot_liberte3">Lot Liberte3</option>
<option value="lot_narjis">Lot Narjis</option>
<option value="quartier_jirari_iii_v">Quartier Jirari III, V</option>
<option value="quartier_jirari_i_ii">Quartier Jirari, I, II</option>
<option value="lot_yasmine">Lot Yasmine</option>
<option value="lot_ghorfa_1_2_3">Lot Ghorfa 1, 2, 3</option>
<option value="complexe_el_boustane">Complexe El Boustane</option>
<option value="complexerim">Complexerim</option>
<option value="lot_bni_touzine">Lot Bni Touzine</option>
<option value="complexe_bait_al_attik">Complexe Bait Al Attik</option>
<option value="complexe_bayti">Complexe Bayti</option>
<option value="lot_banque_populaire">Lot Banque Populaire</option>
<option value="complexe_ahlen">Complexe Ahlen</option>
<option value="quartier_mirador">Quartier Mirador</option>
<option value="quartier_ibn_khaldoun">Quartier Ibn Khaldoun</option>
<option value="lot_ibtissam">Lot Ibtissam</option>
<option value="lot_dhar_acherki">Lot Dhar Acherki</option>
<option value="lot_el_kheir_3">Lot El Kheir 3</option>
<option value="hay_el_ouch">Hay El Ouch</option>
<option value="hay_sidi_bouhaja">Hay Sidi Bouhaja</option>
<option value="hay_laouina">Hay Laouina</option>
<option value="quartier_kouraziana">Quartier Kouraziana</option>
<option value="quartier_bni_ouriaghle_i_ii">Quartier Bni Ouriaghle I, II</option>
<option value="quartier_bouch_et_ta">Quartier Bouch et ta</option>
<option value="quartier_bouillar">Quartier Bouillar</option>
<option value="quartier_kouadess_i_ii">Quartier Kouadess I, II</option>
<option value="quartier_lamkadam">Quartier Lamkadam</option>
<option value="immeuble_bouzina">Immeuble Bouzina</option>
<option value="quartier_haj_kadour">Quartier Haj Kadour</option>
<option value="quartier_sania_i_ii_iii_(bir_chifa)">Quartier Sania I, II, III (Bir Chifa)</option>
<option value="route_de_rabat">Route De Rabat</option>
<option value="route_de_rabat">Route De Rabat</option>
<option value="quartier_malabata">Quartier Malabata</option>
<option value="route_des_abattoires">Route Des Abattoires</option>
<option value="quartier_dhar_lahmam">Quartier Dhar Lahmam</option>
<option value="quartier_sania_(saada)">Quartier Sania (Saada)</option>
<option value="quartier_kssibat">Quartier Kssibat</option>
<option value="lot_al_amal">Lot Al Amal</option>
<option value="quartier_bourabaate">Quartier Bourabaate</option>
<option value="quartier_al_majd">Quartier Al Majd</option>
<option value="tanger_zone_franche_boukhalef">Tanger Zone Franche Boukhalef</option>
<option value="quartier_boutrika">Quartier Boutrika</option>
<option value="residence_yamania">Residence Yamania</option>
<option value="complexe_al_wafa">Complexe Al Wafa</option>
<option value="complexe_marjan">Complexe Marjan</option>
<option value="lot_al_hassani">Lot Al Hassani</option>
<option value="haoumat_12">Haoumat 12</option>
<option value="quartier_al_kherba">Quartier Al Kherba</option>
<option value="complexe_al_moustakbal">Complexe Al Moustakbal</option>
<option value="complexe_zemouri_iii">Complexe Zemouri III</option>
<option value="lot_el_kheir_1_et_2">Lot El Kheir 1 et 2</option>