<option value="aharach">Aharach</option>
<option value="ancien_medina">Ancien Médina</option>
<option value="av._biranzarane">Av. Biranzarane</option>
<option value="av._hassan_ii">Av. Hassan II</option>
<option value="av._kassou_oumaddah">Av. Kassou Oumaddah</option>
<option value="av._moulay_lhassa">Av. Moulay Lhassa</option>
<option value="av._moulay_youssef">Av. Moulay Youssef</option>
<option value="av._prince_heritier">Av. Prince Héritier</option>
<option value="av._riyad_aznak">Av. Riyad Aznak</option>
<option value="bab_rih">Bab Rih</option>
<option value="bab_zitouna">Bab Zitouna</option>
<option value="battoirs">Battoirs</option>
<option value="bd_mohamed_v">Bd Mohamed V</option>
<option value="bin_jradi">Bin Jradi</option>
<option value="bit_ghoulam">Bit Ghoulam</option>
<option value="bouqalal_tarafine">Bouqalal -Tarafine</option>
<option value="camp_coudert">Camp Coudert</option>
<option value="centre_ville">Centre Ville</option>
<option value="coucha_extension">Coucha Extension</option>
<option value="douar_bouhjar">Douar Bouhjar</option>
<option value="friouato">Friouato</option>
<option value="grand_mosque">Grand Mosque</option>
<option value="hay_achral_el_omomia">Hay Achral El Omomia</option>
<option value="hay_adarissa">Hay Adarissa</option>
<option value="hay_al_amal">Hay Al Amal</option>
<option value="hay_amane">Hay Amane</option>
<option value="hay_andalous">Hay Andalous</option>
<option value="hay_chouhada">Hay Chouhada</option>
<option value="hay_fath">Hay Fath</option>
<option value="hay_hassani_(jiyarine)">Hay Hassani (Jiyarine)</option>
<option value="hay_imam_malik">Hay Imam Malik</option>
<option value="hay_laymoun">Hay Laymoun</option>
<option value="hay_maghrib_arabi">Hay Maghrib Arabi</option>
<option value="hay_mariniyine">Hay Mariniyine</option>
<option value="hay_massira_1">Hay Massira 1</option>
<option value="hay_massira_2">Hay Massira 2</option>
<option value="hay_melha">Hay Melha</option>
<option value="hay_messaoudia">Hay Messaoudia</option>
<option value="hay_morabitine">Hay Morabitine</option>
<option value="hay_mostakbal">Hay Mostakbal</option>
<option value="hay_moulay_youssef">Hay Moulay Youssef</option>
<option value="hay_msila">Hay Msila</option>
<option value="hay_nahda">Hay Nahda</option>
<option value="hay_ouattassiyine">Hay Ouattassiyine</option>
<option value="hay_oued_eddahab_(douar_jdid)">Hay Oued Eddahab (Douar Jdid)</option>
<option value="hay_ourida">Hay Ourida</option>
<option value="hay_qods_1">Hay Qods 1</option>
<option value="hay_qods_2">Hay Qods 2</option>
<option value="hay_qods_3">Hay Qods 3</option>
<option value="hay_rachad">Hay Rachad</option>
<option value="hay_saada">Hay Saada</option>
<option value="hay_salam_(bahra)">Hay Salam (Bahra)</option>
<option value="hay_takaddoum_2">Hay Takaddoum 2</option>
<option value="hay_tkaddoum1">Hay Tkaddoum1</option>
<option value="haya_alaouyine">Haya Alaouyine</option>
<option value="jiyarine">Jiyarine</option>
<option value="lot_chafai">Lot Chafai</option>
<option value="lot_chifa">Lot Chifa</option>
<option value="lot_hassania">Lot Hassania</option>
<option value="quartier_industriel_1">Quartier Industriel 1</option>
<option value="quartier_industriel_2">Quartier Industriel 2</option>
<option value="quartier_saadiyine">Quartier Saadiyine</option>
<option value="rbayez">Rbayez</option>
<option value="route_fes">Route Fés</option>
<option value="sahat_tayarane">Sahat Tayarane</option>
<option value="sidi_mssabah">Sidi Mssabah</option>
<option value="taza_aljadida">Taza Aljadida</option>
<option value="taza_haut">Taza Haut</option>
<option value="trame_sanitaire">Trame Sanitaire</option>
<option value="zaouiat_alkabchia">Zaouiat Alkabchia</option>
<option value="ziri_ibn_atiya">Ziri Ibn Atiya</option>