<option value="24_hectares">24 Hectares</option>
<option value="50_hectares">50 Hectares</option>
<option value="abbadi">Abbadi</option>
<option value="abbadi_braika">Abbadi Braika</option>
<option value="abi_horaira">Abi Horaira</option>
<option value="ain_atig">Ain Atig</option>
<option value="al_moustakbal">Al Moustakbal</option>
<option value="andalousse">Andalousse</option>
<option value="centre_ville">Centre Ville</option>
<option value="cigal_cigalon">Cigal Cigalon</option>
<option value="comatrav">Comatrav</option>
<option value="contrebandier">Contrebandier</option>
<option value="derb_askar">Derb Askar</option>
<option value="derb_belmekki">Derb Belmekki</option>
<option value="derb_bennaceur">Derb Bennaceur</option>
<option value="derb_jdid">Derb Jdid</option>
<option value="derb_sahraoua">Derb Sahraoua</option>
<option value="douar_si_lamine">Douar Si Lamine</option>
<option value="fadlallah">Fadlallah</option>
<option value="fadli">Fadli</option>
<option value="fath_el_kheir">Fath El Kheir</option>
<option value="firdaouss">Firdaouss</option>
<option value="harhoura">Harhoura</option>
<option value="hirafiyines">Hirafiyines</option>
<option value="hoda">Hoda</option>
<option value="ittihad_arabi">Ittihad Arabi</option>
<option value="khalota">Khalota</option>
<option value="lamnassir">Lamnassir</option>
<option value="lazrak">Lazrak</option>
<option value="lazrek_nemsia">Lazrek Nemsia</option>
<option value="madwaz">Madwaz</option>
<option value="maghreb_arabi">Maghreb Arabi</option>
<option value="massira_1">Massira 1</option>
<option value="massira_2">Massira 2</option>
<option value="massira_3">Massira 3</option>
<option value="massrou_1">Massrou 1</option>
<option value="messrour_2">Messrour 2</option>
<option value="mkitaa">Mkitaa</option>
<option value="nahda_1">Nahda 1</option>
<option value="nahda_2">Nahda 2</option>
<option value="nemsia">Nemsia</option>
<option value="oued_eddahab">Oued Eddahab</option>
<option value="oulad_ogba">Oulad Ogba</option>
<option value="riad_oulad_mtaa">Riad Oulad Mtaa</option>
<option value="sable_d_or">Sable D'or</option>
<option value="sidi_mohamed_cherif">Sidi Mohamed Cherif</option>
<option value="skikina">Skikina</option>
<option value="talaa">Talaa</option>
<option value="temara_plage">Témara Plage</option>
<option value="val_d_or">Val D'or</option>
<option value="wifak">Wifak</option>
<option value="wifac_erac">Wifac Erac</option>