<option value="ain_khabbaz">Ain Khabbaz</option>
<option value="akba_el_halouf">Akba El Halouf</option>
<option value="atlas">Atlas</option>
<option value="avenida_place_el_adala">Avenida- Place El Adala</option>
<option value="avenue_casablanca">Avenue Casablanca</option>
<option value="avenue_des_far">Avenue Des Far</option>
<option value="avenue_el_massira_el_khadra">Avenue El Massira El Khadra</option>
<option value="avenue_mekki_nasiri">Avenue Mekki Nasiri</option>
<option value="avenue_mohamed_daoued">Avenue Mohamed Daoued</option>
<option value="avenue_sebta">Avenue Sebta</option>
<option value="bab_el_mkaber">Bab El Mkaber</option>
<option value="bab_el_okla">Bab El Okla</option>
<option value="bab_noider">Bab Noider</option>
<option value="bab_saida">Bab Saida</option>
<option value="bab_toute">Bab Toute</option>
<option value="balbodine">Balbodine</option>
<option value="bario_malaga">Bario Malaga</option>
<option value="boujarrahe">Boujarrahe</option>
<option value="boujdour">Boujdour</option>
<option value="bousafou">Bousafou</option>
<option value="centre_ville">Centre Ville</option>
<option value="dar_essedraouia">Dar Essedraouia</option>
<option value="dar_et_tayer">Dar et tayer</option>
<option value="feddane">Feddane</option>
<option value="ghersa_kbira">Ghersa Kbira</option>
<option value="gourna">Gourna</option>
<option value="haj_meki_nasiri">Haj Meki Nasiri</option>
<option value="haouma_tanjaoua">Haouma Tanjaoua</option>
<option value="haouta_said">Haouta Said</option>
<option value="hay_el_mdrassi">Hay El Mdrassi</option>
<option value="hospital_militaire">Hospital Militaire</option>
<option value="ibn_khaldoune">Ibn Khaldoune</option>
<option value="ichara">Ichara</option>
<option value="ifriquia">Ifriquia</option>
<option value="inara">Inara</option>
<option value="jamae_el_kbir">Jamae El Kbir</option>
<option value="jamae_el_khadra">Jamae El Khadra</option>
<option value="jamae_mezouak">Jamae Mezouak</option>
<option value="jbel_dersa">Jbel Dersa</option>
<option value="kheroness">Kheroness</option>
<option value="kodiate_el_hamd">Kodiate El Hamd</option>
<option value="kouilma">Kouilma</option>
<option value="lotisement_ain_melloul">Lotisement Ain Melloul</option>
<option value="lotisement_mounia">Lotisement Mounia</option>
<option value="lotisement_souani">Lotisement Souani</option>
<option value="louada">Louada</option>
<option value="marche_central">Marché Central</option>
<option value="medina">Medina</option>
<option value="mellah">Mellah</option>
<option value="mesdae">Mesdae</option>
<option value="mhanech_2">Mhanech 2</option>
<option value="mouklata">Mouklata</option>
<option value="moulay_el_abbas">Moulay El Abbas</option>
<option value="moulay_youssef">Moulay Youssef</option>
<option value="msalla_kdima">Msalla Kdima</option>
<option value="place_moulay_el_mehdi">Place Moulay El Mehdi</option>
<option value="quartier_administratif">Quartier Administratif</option>
<option value="quartier_el_matar">Quartier El Matar</option>
<option value="quartier_militaire">Quartier Militaire</option>
<option value="samsa">Samsa</option>
<option value="saniat_rmel">Saniat Rmel</option>
<option value="sidi_abdellah_el_fakhare">Sidi Abdellah El Fakhare</option>
<option value="sidi_bahrouri">Sidi Bahrouri</option>
<option value="sidi_talha">Sidi Talha</option>
<option value="souika">Souika</option>
<option value="souk_el_fouki">Souk El Fouki</option>
<option value="souk_zrae">Souk Zrae</option>
<option value="soukna_wa_taemir">Soukna Wa Taemir</option>
<option value="taboula">Taboula</option>
<option value="taffaline">Taffaline</option>
<option value="talaa">Talaa</option>
<option value="talaa_regulares">Talaa Regulares</option>
<option value="tarrafine">Tarrafine</option>
<option value="teknia">Teknia</option>
<option value="touabel">Touabel</option>
<option value="touibla">Touibla</option>
<option value="touilae">Touilae</option>
<option value="touta">Touta</option>
<option value="ziana">Ziana</option>
<option value="quartier_dar_mourcia">Quartier Dar Mourcia</option>
<option value="quartier_karian">Quartier Karian</option>
<option value="akba_chata">Akba Chata</option>
<option value="quatier_quare_d_heur">Quatier Quare D'heur</option>
<option value="quartier_borj">Quartier Borj</option>
<option value="lot_al_wikaya">Lot Al Wikaya</option>
<option value="quartier_orangina">Quartier Orangina</option>
<option value="quartier_laouziyine">Quartier Laouziyine</option>
<option value="quartier_ifriquia">Quartier Ifriquia</option>
<option value="quartier_tamouda">Quartier Tamouda</option>
<option value="quartier_koura_sbae">Quartier Koura Sbae</option>
<option value="qartier_bouenane">Qartier Bouenane</option>
<option value="quatier_boujdade">Quatier Boujdade</option>
<option value="quartier_ennakata">Quartier Ennakata</option>