<option value="">--</option>
<option value="1">Glaucomes</option>
<option value="2">Autres maladies ophtalmo</option>
<option value="3">Grossesse</option>
<option value="4">Infection génitale</option>
<option value="5">Fibromes et/ou kyste ovarien</option>
<option value="6">Dysmenorhée</option>
<option value="7">Autres problèmes gynéco-obstetriques</option>
<option value="8">Problèmes urologiques/ néphrologiques</option>
<option value="9">IST SIDA</option>
<option value="10">Blessure</option>
<option value="11">Gale</option>
<option value="12">Allergie et/ou dermatose</option>
<option value="13">Autres Problèmes Dermatologique</option>
<option value="14">HTA</option>
<option value="15">Anémie</option>
<option value="16">Autres maladie Cardio-vasculaire</option>
<option value="17">Traumatisme</option>
<option value="18">Psychose</option>
<option value="19">Maladie Neuro-lombaire</option>
<option value="20">Céphalées</option>
<option value="21">AEG</option>
<option value="22">Drépanocytose</option>
<option value="23">Néoplasie (tumeur…)</option>
<option value="24">autres </option>
