<option value="">--</option>
<option value="1">Antalgique / Analgésique</option>
<option value="2">Antiasthmatique</option>
<option value="3">Antibiotique</option>
<option value="4">Antimycosique</option>
<option value="5">Anti inflammatoire</option>
<option value="6">Antihistaminique</option>
<option value="7">Antigrippaux</option>
<option value="8">Antihémorroidaire</option>
<option value="9">Antiviraux</option>
<option value="10">Antiseptiques</option>
<option value="11">Médicaments de la toux (antitussif / expectorant)</option>
<option value="12">Collyres et pommade ophtalmiques</option>
<option value="13">Complexes vitaminiques et minéraux</option>
<option value="14">Contraceptif</option>
<option value="15">Corticoïdes</option>
<option value="16">Médicaments du diabète</option>
<option value="17">Médicaments cardio-vasculaires</option>
<option value="18">Médicaments gastro-entériques</option>
<option value="19">Médicaments gynéco</option>
<option value="20">Myorelaxants</option>
<option value="21">Psychotropes</option>
<option value="22">Topiques</option>
