<option value="1">Prise de RDV</option>
<option value="2">Consultation</option>
<option value="3">Analyses</option>
<option value="4">Kiné</option>
<option value="5">Imagerie</option>
<option value="6">Formalités administratives</option>
<option value="7">Pharmacie</option>
<option value="8">Achat matériel</option>
<option value="9">Visite</option>
<option value="10">Urgence</option>
<option value="11">Hospitalisation</option>
<option value="12">Entrée/sortant (Actes médicaux):</option>
