<option value="">--</option>
<option value="1">Pharmacie</option>
<option value="2">Cabinet dentaire privé</option>
<option value="3">Opticien privé</option>
<option value="4">Laboratoire d'analyses médicales privées</option>
<option value="5">Laboratoire d'imageries médicales privées</option>
<option value="6">Centre de santé primaire</option>
<option value="7">Centre de diagnostic</option>
<option value="8">Centre Hospitalier regional / provincial</option>
<option value="9">Centre Hospitalier universitaire</option>
<option value="10">Maison d'accouchement</option>
<option value="11">Association partenaires (ALCS, CEI, MERF, MDM...)</option>
<option value="12">Agence ONU (HCR, OIM...)</option>
<option value="13">Fournisseurs matériels privés</option>
<option value="14">Cabinet médical privé</option>
<option value="15">Clinique privé</option>
<option value="16">Autres services Caritas</option>
<option value="17">Autre</option>
