<option value="">--</option>
<option value="medicament">Médicaments</option>
<option value="consultation">Consultations</option>
<option value="lunette">Lunettes</option>
<option value="analyse">Analyses médicales</option>
<option value="imagerie">Imageries médicales</option>
<option value="cpn">Consultation pré-natale (CPN)</option>
<option value="pec">PEC et/ou suivi</option>
<option value="materiel">Matériels médicaux</option>
<option value="devis">Devis</option>
<option value="kine">Kiné</option>
