<option value="">--</option>
<option value="1">Contribution financière au loyer</option>
<option value="2">Hébergement d'urgence</option>
<option value="3">Contribution aux frais de transport</option>
<option value="4">Aide au retour</option>
<option value="5">Contribution financière à l'alimentation</option>
<option value="6">Crèche</option>
<option value="7">Douche</option>
<option value="8">Kit hygiène</option>
<option value="9">Kit naissance</option>
<option value="10">Couches</option>
<option value="12">Couvertures</option>
<option value="13">Matelas</option>
<option value="14">Vêtements</option>
<option value="15">Autres</option>
