<option value="">--</option>
<option value="1anneeENF">1° année ENF</option>
<option value="2anneeENF">2° année ENF</option>
<option value="3anneeENF">3° année ENF</option>
<option value="PS">Petite section</option>
<option value="MS">Moyenne section</option>
<option value="GS">Grande section</option>
<option value="CE1">CE1</option>
<option value="CE2">CE2</option>
<option value="CE3">CE3</option>
<option value="CE4">CE4</option>
<option value="CE5">CE5</option>
<option value="CE6">CE6</option>
<option value="CE7">CE7</option>
<option value="CE8">CE8</option>
<option value="CE9">CE9</option>
<option value="1annéelycee">1° année lycée</option>
<option value="1annéebac">1° année Bac</option>
<option value="2annéebac">2° année Bac</option>
