<option value="">--</option>
<option value="1">Établissement scolaire</option>
<option value="2">Organisme de formation</option>
<option value="3">Déléguation de l'éducation</option>
<option value="4">Académie</option>
<option value="5">Association</option>
<option value="6">Anapec</option>
<option value="7">Lieu d'apprentissage</option>
<option value="8">Lieu de stage</option>
<option value="9">Autre</option>
